Discontinue using deprecated methods in GCSToBigQueryOperator
apache/airflow pull request #10354
Opened 2020-08-17 03:17 UTC by coopergillan

Several methods used in `GCSToBigQueryOperator` are deprecated. Switch to use the preferred methods, updating parameters and tests as needed.

related: #10288

Note: I only had time to tackle the operator mentioned by the user who opened the issue. It looks like the other Big Query transfer operators have the same issue. I could tackle those at a later date.
---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

2020-08-17 03:18 UTC, coopergillan commented
@turbaszek and @mik-laj both chimed in over in the original issue https://github.com/apache/airflow/issues/10288.

2020-08-17 07:32 UTC, turbaszek requested changes

2020-08-17 07:32 UTC, turbaszek commented on airflow/providers/google/cloud/transfers/gcs_to_bigquery.py
> +            bq_hook.create_external_table(
This method is also deprecated

2020-08-17 07:32 UTC, turbaszek commented on airflow/providers/google/cloud/transfers/gcs_to_bigquery.py
> +            bq_hook.insert_job(configuration=dict(
That won't do:
```
airflow.exceptions.AirflowException: Unknown job type. Supported types: dict_keys(['load', 'copy', 'extract', 'query'])
```
as per docstring:
```
The configuration parameter maps directly to
            BigQuery's configuration field in the job object. See
            https://cloud.google.com/bigquery/docs/reference/v2/jobs for
            details.
```

So what I would suggest is:
- add `configuration` parameter to constructor
- if this parameter is passed then use `insert_job` method
- if not then show a deprecation warning that `Users should pass load job definition` and use the existing logic

Probably we should validate that only `load` job is passed... WDYT @edejong ?

2020-10-12 00:02 UTC, closed without merging

2020-11-23 08:56 UTC, turbaszek commented
@coopergillan any progress on this one?

2020-11-23 09:22 UTC, turbaszek commented
Hey @coopergillan do you have bandwitdth to continue this PR? It's quite important one as we have few issues around this operator 🔥 Maybe @juneoh would like to help?

2021-11-16 15:50 UTC, coopergillan commented
@turbaszek - sorry for the nearly-year-long silence. I am hhoping to take a look back into this as it appears that the issue https://github.com/apache/airflow/issues/10288 is still open.