Added Plexus as an Airflow provider
apache/airflow pull request #10591
Opened 2020-08-26 20:53 UTC by millertracy

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

2020-09-05 07:27 UTC, potiuk requested changes
Hey @millertracy -> reviewed it. Nice piece of provider :).

The main comment is about the settup.py change (plexus needs 'plexus' extra and arrow should be added there - also then plexus extra should be added to "all_devs/all" extras similarly to other extras.

Also then you will need to mark it as "provider" dependency in PROVIDERS_REQUIREMENTS. 

This should likely fix backport package problem that you have (airflow 1.10.10 does not have arrow as requirement, neither the generated backport package). 

There is also some work to make the docs work - some spellcheck problems from what I see.

One more NIT - It would also be great if you create a HowTo out of your example. You can see how other operators do that, but basically it is a very short "Howto" doc that extracts part of the "example_dag" and adds some description on what the operator does. 

Another part (but this is something that we have no full CI automation yet) is to turn the example dag into a runnable "system test". This is described in https://github.com/apache/airflow/blob/master/TESTING.rst#airflow-system-tests  - and it's not required, but it seems to be easy to do in your case as this is rather simple example you have.


We plan to automate system tests later this year and it would be great to have such easy-to-run system test in place. But this one is nice-to-havee.

This is actually the most powerful part of the exmple_dags

2020-09-05 07:27 UTC, potiuk commented on airflow/providers/plexus/hooks/plexus.py
> +    @property
Nice!

2020-09-05 07:27 UTC, potiuk commented on setup.py
> +    'arrow==0.16.0',
You should create a "plexus" extra and add "arrow" to the extra , rather than to install requirements.

2020-09-05 07:27 UTC, potiuk commented on tests/providers/plexus/operators/test_plexus.py
> +    @pytest.fixture
Nice! We do not use pytest fixtures too much (we allow both unit tests style and pytest ones). But I think it's good to have more examples of nice pytest fixtures.

2020-09-09 18:02 UTC, millertracy commented
> Hey @millertracy -> reviewed it. Nice piece of provider :).
> 
> The main comment is about the settup.py change (plexus needs 'plexus' extra and arrow should be added there - also then plexus extra should be added to "all_devs/all" extras similarly to other extras.
> 
> Also then you will need to mark it as "provider" dependency in PROVIDERS_REQUIREMENTS.
> 
> This should likely fix backport package problem that you have (airflow 1.10.10 does not have arrow as requirement, neither the generated backport package).
> 
> There is also some work to make the docs work - some spellcheck problems from what I see.
> 
> One more NIT - It would also be great if you create a HowTo out of your example. You can see how other operators do that, but basically it is a very short "Howto" doc that extracts part of the "example_dag" and adds some description on what the operator does.
> 
> Another part (but this is something that we have no full CI automation yet) is to turn the example dag into a runnable "system test". This is described in https://github.com/apache/airflow/blob/master/TESTING.rst#airflow-system-tests - and it's not required, but it seems to be easy to do in your case as this is rather simple example you have.
> 
> We plan to automate system tests later this year and it would be great to have such easy-to-run system test in place. But this one is nice-to-havee.
> 
> This is actually the most powerful part of the exmple_dags

@potiuk will i also need to add backward compatibility for airflow 1.10* by adding plexus hook/operator to the airflow.contrib package

2020-09-09 18:13 UTC, potiuk commented
@potiuk thank you! I will make those changes. will i also need to add backward compatibility for airflow 1.10* by adding plexus hook/operator to the airflow.contrib package?

No need. By adding it to the setup properly, backport provider is automatically created and tested, so no need to do anything.

2020-09-09 18:25 UTC, millertracy commented
> > @potiuk thank you! I will make those changes. will i also need to add backward compatibility for airflow 1.10* by adding plexus hook/operator to the airflow.contrib package?
> 
> No need. By adding it to the setup properly, backport provider is automatically created and tested, so no need to do anything.

That's great. Double checking though - i will need to reference the 1.10* compatibility in the README.md like the other providers correct? By referencing "Moved Hooks and Operators"?

2020-09-09 21:31 UTC, millertracy commented
@potiuk finished changes. is there anything else that needs to be done?

2020-09-10 06:57 UTC, potiuk commented
Almost perfect! Just remove the README file. We are going to generate one automatically when we release next wave of backports.

2020-09-10 15:25 UTC, potiuk approved these changes

2020-09-10 17:17 UTC, millertracy commented
@potiuk thanks for approving changes. 2 checks were cancelled, but it doesn't look related to my code. When should i expect a merge into the base branch?

2020-09-10 17:54 UTC, potiuk approved these changes
Cool stuff @millertracy ! Thanks for that! "Have One more provider we" as the old Yoda would say.

2020-09-10 17:54 UTC, merged