Added jupytercmd and fixed task failure when notify set as true in qubole operator
apache/airflow pull request #10599
Opened 2020-08-27 11:32 UTC by lordozb

Closes [#9252](https://github.com/apache/airflow/issues/9252)

**Description**
This PR adds jupytercmd in Qubole Operator which fires a JupyterNotebookCommand to the jupyter notebooks running on user's QDS account. Along with this, we have fixed a minor bug which caused the tasks to fail with _--notify_ is set in Qubole Operator.

2020-08-27 11:41 UTC, chattarajoy approved these changes

2020-08-28 17:53 UTC, chattarajoy commented
Upgrade the version of qds sdk to latest in the requirements.

2020-08-28 17:55 UTC, chattarajoy requested changes

2020-08-28 17:55 UTC, chattarajoy commented on airflow/providers/qubole/hooks/qubole.py
> +                    if value is True: # pylint: disable=too-many-nested-blocks
Add a test case for this?

2020-08-28 17:55 UTC, chattarajoy commented on airflow/providers/qubole/operators/qubole.py
>              :macros: macro values which were used in query
Add parameters for jupytercmd as well

2020-08-29 10:12 UTC, lordozb commented
@chattarajoy 
Master branch already has 1.16.0 version of qds-sdk

2020-09-03 09:28 UTC, msumit approved these changes

2020-09-03 09:30 UTC, merged