Always return a list from s3 list methods.
apache/airflow pull request #10774
Opened 2020-09-07 01:28 UTC by jmcarp

The `list_prefixes` and `list_keys` methods of the s3 hook return lists if the result isn't empty, and `None` otherwise. Some operators that use these methods break when the result is empty, because they expect to receive a list and not `None`. We could change the operators to handle `None`, but I think it makes more sense to return an empty list when the prefix or key list is empty instead. This matches the behavior of the aws sdk, and I think an empty list is a more reasonable return value than `None` if no prefixes or keys match the query.

2020-09-07 10:38 UTC, turbaszek approved these changes
Make sense to me 👌

2020-09-07 11:21 UTC, XD-DENG reviewed
Given it's a behaviour change, it should be mentioned in the CHANGELOG (someone may be using something like `X is None` to handle this currently, which will fail if this change is released)

2020-09-07 11:24 UTC, feluelle requested changes
LGTM, but I think we need a note about it in UPDATING.md ?!

2020-09-07 11:24 UTC, XD-DENG commented
To correct myself, rather than CHANGELOG, I meant `UPDATING.md` (https://github.com/apache/airflow/blob/master/UPDATING.md)

2020-09-07 17:15 UTC, jmcarp commented
Thanks, I updated `UPDATING.md`.

2020-09-08 07:33 UTC, feluelle approved these changes

2020-09-08 07:48 UTC, turbaszek approved these changes

2020-09-08 07:49 UTC, merged