Fix case of Python.
apache/airflow pull request #10960
Opened 2020-09-15 20:12 UTC by jbampton

Changed `python` to `Python`.

2020-09-17 12:36 UTC, potiuk commented on CHANGELOG.txt
> +- Requirements now depend on Python version (#7841)
Those refer to commit messages that cannot be changed so we better do not change them.

2020-09-17 12:43 UTC, potiuk requested changes
I love the change @jbampton , but I have two things to change:

* let's not change python -> Python in the release notes where we are referring to commits that are in the history (otherwise people and tools might have difficulty in finding them)

* the general rule we have in case of such changes that we do not only fix them, but also prevent them from happening in the future. In this case it should be rather easy - just adding another check in the .pre-commit.yml - using pygrep plugin (you will find some examples in there). It should be rather easy to add a case-sensitive regular expression that finds `python` as a word excluding those CHANGES and UPDATING files.

2020-09-17 12:43 UTC, potiuk commented on airflow/providers/databricks/PROVIDERS_CHANGES_2020.06.24.md
>  | [f6bd817a3](https://github.com/apache/airflow/commit/f6bd817a3aac0a16430fc2e3d59c1f17a69a15ac) | 2020-06-16  | Introduce &#39;transfers&#39; packages (#9320)
Also all those PROVIDERS_CHANGES are referring to the commits so I would not change those. There are many provider's changes files below - all of them should be exempted from that change.

2020-11-20 14:44 UTC, ashb requested changes
You've missed at least one case, and some of them are referring to things where it should be kept lower case.

2020-11-20 14:44 UTC, ashb commented on airflow/utils/cli_action_loggers.py
> +so that registered callbacks can be used all through the same Python process.
(Strictly speaking this is correct lowercase -- it's talking about the executable)

2020-11-20 14:44 UTC, ashb commented on airflow/utils/timezone.py
> +        # In case of Python 3.6 we want to do the same that pendulum does for python3.5
Missed `python3.5`.

2020-11-20 14:44 UTC, ashb commented on scripts/ci/images/ci_prepare_ci_image_on_ci.sh
> +        # first we pull base Python image. We will need it to re-push it after master build
Ones like this are referring to `docker pull python` - so not sure it makes sense here.

2020-11-20 14:44 UTC, ashb commented on scripts/ci/libraries/_build_images.sh
> +    # Python image version to use
Ditto -- is talking about `python:3.7` etc.

2021-03-13 00:29 UTC, closed without merging