Move dummy_operator.py to dummy.py (#11178)
apache/airflow pull request #11293
Opened 2020-10-06 07:51 UTC by kishvanchee

This change is related to #11178 for the `dummy_operator`

**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

2020-10-06 07:55 UTC, kishvanchee commented
@turbaszek @mik-laj Please review the changes.

2020-10-06 11:52 UTC, kishvanchee commented
I'm not sure how to fix **CI Build / Backport packages (pull_request)**. The error states 

```
Traceback (most recent call last):
  File "/import_all_provider_classes.py", line 60, in import_all_provider_classes
    _module = importlib.import_module(module_name)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/site-packages/airflow/providers/qubole/example_dags/example_qubole.py", line 24, in <module>
    from airflow.operators.dummy import DummyOperator
ModuleNotFoundError: No module named 'airflow.operators.dummy'
```
but this should have failed for imports from other places too right? I don't see this error popping up in the breeze environment.

```
root@b20475852b92:/opt/airflow# python
Python 3.6.12 (default, Sep 10 2020, 18:03:29) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from airflow.operators.dummy import DummyOperator as d1
>>> from airflow.operators.dummy_operator import DummyOperator as d2
>>> d2.__name__
'DummyOperator'
>>> d1.__name__
'DummyOperator'
```

2020-10-06 13:38 UTC, mik-laj commented
@kishvanchee c The files in the providers directory must be either compatible with Airflow 1.10.13, or they must be automatically refactor to be compatible. When we release Airflow 1.10.13 this problem will disappear. Details: https://github.com/apache/airflow/issues/11178
https://github.com/apache/airflow/issues/10152 Migration to Airflow 2.0
Now you can either revert all changes to the providers directory or add auto-refactor (preferred). To do it, add a new tuple here: https://github.com/apache/airflow/blob/9514cfe64b35289566c4e56c491c36b43c4fb737/backport_packages/refactor_backport_packages.py#L145-L155

2020-10-06 14:28 UTC, kishvanchee commented
@mik-laj Got it thanks. I'll make that change. How does this affect only certain operators and not all operators? Since so far I see only bash and python are incorporated, and now we'll incorporate dummy too.

2020-10-07 07:44 UTC, kishvanchee commented
@mik-laj please review the changes

2020-10-07 16:56 UTC, turbaszek requested changes
Please update occurrences of import of DummyOperator in docs so they use new path not deprecated one

2020-10-07 17:08 UTC, kishvanchee commented
@turbaszek Can you please confirm? I was excluding `docs/_api` from my search since I thought these would get generated automatically. I guess from your comment I'm wrong.

2020-10-07 17:14 UTC, turbaszek commented
We should fix all occurrences 😉

2020-10-10 10:54 UTC, turbaszek commented
@kishvanchee can you rebase please?

2020-10-11 16:59 UTC, turbaszek commented
@kishvanchee can you please rebase due to conflicts?

2020-10-11 17:18 UTC, turbaszek approved these changes
LGTM 🆗

2020-11-04 00:30 UTC, kaxil commented
Can you please rebase your PR on latest Master since we have applied [Black](https://github.com/apache/airflow/commit/4e8f9cc8d02b29c325b8a5a76b4837671bdf5f68) and [PyUpgrade](https://github.com/apache/airflow/commit/8c42cf1b00c90f0d7f11b8a3a455381de8e003c5) on Master.

It will help if your squash your commits into single commit first so that there are less conflicts.

2020-11-22 22:09 UTC, turbaszek commented
@kishvanchee any update on this one?

2020-11-23 18:26 UTC, kishvanchee commented
@turbaszek @kaxil Hi, I apologize for the delay. I'll update this by tomorrow afternoon IST.

2020-11-24 09:19 UTC, kishvanchee commented
@kaxil @turbaszek Can you please have a look now? I have updated, rebased and squashed the commits.

2020-11-24 09:54 UTC, turbaszek approved these changes
LGTM! The failed test is related to scheduler tests

2020-11-24 10:11 UTC, ashb requested changes
This needs a note added to UPDATING.md and UPGRADING_TO_2.0.md please

2020-11-24 10:28 UTC, kishvanchee commented
> This needs a note added to UPDATING.md and UPGRADING_TO_2.0.md please

Can you please point out where exactly? In UPDATING.md I found a section ** Changes to import paths **. I couldn't find something similar in UPGRADING_TO_2.0.md.

2020-11-24 10:31 UTC, ashb commented
Oh yes, there's nothing in there (perhaps there should be) -- so just UPDATING.md will be fine

2020-11-24 11:04 UTC, kishvanchee commented
@ashb can you please have a look?

2020-11-28 23:46 UTC, ashb commented on UPDATING.md
> +| airflow.operators.dummy_operator.py | airflow.operators.dummy.py |
I'm surprised to see we don't have more info here/a table like this already!

2020-11-28 23:49 UTC, ashb commented on UPDATING.md
> +| airflow.operators.dummy_operator.py | airflow.operators.dummy.py |
There's this block further on.

```
#### Removed deprecated import mechanism

The deprecated import mechanism has been removed so the import of modules becomes more consistent and explicit.

For example: `from airflow.operators import BashOperator`
becomes `from airflow.operators.bash_operator import BashOperator`

```

2020-11-28 23:51 UTC, ashb commented on UPDATING.md
> +| airflow.operators.dummy_operator.py | airflow.operators.dummy.py |
```suggestion
| airflow.operators.dummy_operator.DummyOperator | airflow.operators.dummy.DummyOperator |
```

2020-12-01 21:27 UTC, ashb approved these changes

2020-12-01 21:28 UTC, ashb commented
@kishvanchee Could you rebase this please? And check if there are any new instances that have "snuck in" in the mean time.

2020-12-01 22:07 UTC, kishvanchee commented
@ashb Yes sure, I will do this tomorrow. Apologies for the delay.

2020-12-02 10:53 UTC, ashb commented
> @ashb Yes sure, I will do this tomorrow. Apologies for the delay.

The delay was all us, no need to apologise!

2020-12-07 23:58 UTC, kaxil commented
I think this needs updating https://github.com/apache/airflow/blob/23e743ec09bffe30a9a2b17cc873af5ef9d3cd9f/dev/provider_packages/refactor_provider_packages.py#L141-L145 too

2020-12-08 19:19 UTC, merged