Behaviour to install all airflow providers added
apache/airflow pull request #11529
Opened 2020-10-14 17:47 UTC by potiuk

In Airflow 2.0 we decided to split Airlow into separate providers.
this means that when you prepare core airflow package, providers
are not installed by default. This is not very convenient for
local development though and for docker images built from sources,
where you would like to install all providers by default.

A new INSTALL_ALL_AIRFLOW_PROVIDERS environment variable controls
this behaviour now. It is is set to "true", all packages including
provider packages are installed. If missing or set to false, only
the core provider package is installed.

For Breeze, the default is set to "true", as for those cases you
want to install all providers in your environment. Similarly if you
build the production image from sources. However when you build
image using github tag or pip package, you should specify
appropriate extras to install the required provider packages.

Note that if you install Airflow via 'pip install .' from sources
in local virtualenv, provider packages are not going to be
installed unless you set INSTALL_ALL_AIRFLOW_PROVIDERS to "true".

Fixes #11489

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

2020-10-14 18:10 UTC, potiuk commented
Hey @ashb @kaxil  @turbaszek, others. I looked how to solve the installation problem described in #11489 and failing Kubernetes builds (caused likely by the provider split) and I believe i found the best approach. I think we want to keep this:

* in any setup where we use packages, we want to install separately airflow and providers
* in any setup where we use sources, we want to install airflow + providers together for development convenience

The proposal I have is a variable INSTALL_PROVIDERS_FROM_SOURCES. When this flag is "true", airflow will install providers from sources, when it is missing or anything else but "true", it will install only airflow core.  By default in Breeze and when building images from sources I set this variable to "true" (but it can be set to false by --skip-installing-airflow-providers flag so that you can also install a "bare" airflow in Breeze or prepare a "bare" image without any providers easily. Together with in-progess #11464 (I will have to add conditional dependencies there and rebase on top of this) it will have exactly the desired effect:

* when installing airflow with Breeze from sources (both prod and CI), we continue installing all providers from sources like we have in 1.10. Extras will not cause installing of apache-airflow-providers-* as those dependencies will be disabled in this case. You can also disable installing all providers by ``-skip-install0ing-airlfow-providers``

* when installing airflow with Breeze  from PyPI or GitHub, only the providers required by "extras" will be installed

* when installing airflow locally with "." (without -e) only bare Airflow will be installed, provders will only be available if you happen to be in the airflow directory or if you install provider packages manually. You can also set INSTALL_PROVIDER_SOURCES="true" before installation and then all providers will be installed as in 1.10.

* when installing airflow locally with -e '.'  - providers will be automatically installed and available. Since 'airflow' is taken direclty from sources, providers are there and they will be importable.


I tested all the above scenarios and I think it makes perfect sense. Let me know what you think.

2020-10-14 19:35 UTC, potiuk commented on IMAGES.rst
>  |                                          |                                          | dockerignore                             |
```suggestion
|                                          |                                          | dockeri gnore                            |
```

2020-10-14 19:35 UTC, potiuk commented on docs/production-deployment.rst
> +|                                          |                                          | dockerignore                             |
```suggestion
|                                          |                                          | docker ignore                            |
```

2020-10-14 19:40 UTC, mik-laj approved these changes

2020-10-14 19:41 UTC, kaxil commented on IMAGES.rst
> +|                                          |                                          | dockeri gnore                            |
```suggestion
|                                          |                                          | dockerignore                            |
```

2020-10-14 19:42 UTC, kaxil requested changes

2020-10-14 19:42 UTC, kaxil commented on INSTALL
> +You can also install airflow in development mode where not
incomplete sentence

2020-10-14 19:46 UTC, kaxil commented on CONTRIBUTING.rst
> +variable to ``true``.
```suggestion
In Airflow 1.10 all those providers were installed together within one single package and when you installed
airflow locally, from sources, they were also installed. In Airflow 2.0, providers are separated out,
and not installed together with the core, unless you set ``INSTALL_PROVIDERS_FROM_SOURCES`` environment
variable to ``true``.
```

2020-10-14 19:46 UTC, kaxil commented on CONTRIBUTING.rst
> +In Breeze - which is a development variable, INSTALL_PROVIDERS_FROM_SOURCES is set to true, but you
```suggestion
In Breeze - which is a development variable, ``INSTALL_PROVIDERS_FROM_SOURCES`` is set to true, but you
```

2020-10-14 19:47 UTC, kaxil commented on CONTRIBUTING.rst
> +* 'apache-airflow-backport-provider-*
```suggestion
* 'apache-airflow-backport-provider-*'
```

2020-10-14 19:50 UTC, kaxil reviewed
Minor suggestions left

2020-10-14 21:00 UTC, potiuk commented
All resolved @kaxil!

2020-10-15 11:02 UTC, kaxil approved these changes

2020-10-17 09:16 UTC, merged