JSON serialization of dates fix
apache/airflow pull request #11540
Opened 2020-10-15 00:26 UTC by QuinRiva

closes: #11370
---

JSON serialization thows errors if date/datetime fields are in the table.  Converting those fields to strings before serialization solves this issue.

Additionally add the DATETIME (which is separate to timestamp) as a typemap for converting a field to bigquery.  This has the unfortunate side-effect of converting DATE to DATETIME as the MSSQL DBAPI doesn't distinguish between DATE and DATETIME (both type 2).

2020-10-16 15:39 UTC, ashb reviewed
Please add unit tests.

2020-10-19 10:01 UTC, ashb requested changes
Please add unit tests.

2020-11-04 00:27 UTC, kaxil commented
Can you please rebase your PR on latest Master since we have applied [Black](https://github.com/apache/airflow/commit/4e8f9cc8d02b29c325b8a5a76b4837671bdf5f68) and [PyUpgrade](https://github.com/apache/airflow/commit/8c42cf1b00c90f0d7f11b8a3a455381de8e003c5) on Master.

It will help if your squash your commits into single commit first so that there are less conflicts.

2020-12-25 21:53 UTC, potiuk commented
Is this something we should finish/merge @ashb/@kaxil ?  it looks needed :)

2020-12-31 14:47 UTC, mik-laj commented
@potiuk  This is about integration with Google, so looks like we'll have to take care of it.

2021-03-06 00:33 UTC, closed without merging