Unauthenticated access with RBAC to URL has_dag_access results lose r…
apache/airflow pull request #11592
Opened 2020-10-16 17:52 UTC by mpermana

…edirection #11591

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

2020-10-16 18:33 UTC, dimberman commented
Hi @mpermana good to hear from you :). Can you please add some more details to the description? Also do we need to add any tests for this?

2020-10-16 20:35 UTC, mpermana commented
@dimberman Added elaborate  description , no we don't need test , you know me, thank you

2020-10-17 00:38 UTC, dimberman commented
@mpermana I know that we know eachother but that doesn't mean I'm going to merge untested code :). Especially since this fixes a bug, can you please write a unit test mimicking the failure so someone else doesn't break it in the future.

2020-10-17 01:57 UTC, Acehaidrey approved these changes
thank you for this fix!

2020-10-19 09:48 UTC, ashb requested changes
As mentioned in the Contributing guide https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#step-4-prepare-pr please add tests.

2020-10-21 01:28 UTC, mpermana commented
@ashb  Added test

The checks have 10 skipped and 1 neutral, are they ok?

2020-10-21 06:52 UTC, ashb requested changes
Yes, those skipped tests are fine (we skip some builds on PRs)

Just the small changes please

2020-10-21 06:52 UTC, ashb commented on tests/www/test_decorators.py
> +from mock import Mock
```suggestion
from unittest.mock import Mock
```

2020-10-21 06:52 UTC, ashb commented on tests/www/test_decorators.py
> +class TestDecorators(TestCase):
```suggestion
class TestDecorators:
```

With pytest being used now we don't need to inherit from TestCase anymore

2020-10-21 06:52 UTC, ashb commented on tests/www/test_decorators.py
> +from unittest import TestCase
```suggestion
```

2020-10-22 02:02 UTC, mpermana commented
@ashb any idea why files that i dont change failed test: airflow/providers/sftp/hooks/sftp.py

2020-10-22 06:43 UTC, mpermana commented
@ashb Looks like now only 1 failing check and thats not due to my change:

Run pydocstyle....................................................................................................................Failed
- hook id: pydocstyle
- exit code: 1

airflow/providers/google/cloud/hooks/cloud_memorystore.py:546 in public method `get_conn`:

2020-10-23 03:54 UTC, mpermana commented
@ashb Test passed now after rebase

2020-10-23 16:07 UTC, ashb requested changes
Suggestions not applied (or got unapplied?)

2020-10-24 02:57 UTC, mpermana commented
> Suggestions not applied (or got unapplied?)

sorry, suggestions was applied then got lost when i rebased, now it is there

2020-10-26 13:01 UTC, ashb approved these changes

2020-10-26 13:01 UTC, merged