update variables names in _in_container_script_init.sh
apache/airflow pull request #11750
Opened 2020-10-22 17:56 UTC by OliverWBurke

local variable switched to lower case

closes one of the items on :#10576

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

2020-10-22 18:00 UTC, potiuk requested changes
Great stuff. Though I think the env VAR is really a constant and should be read only

2020-10-22 18:00 UTC, potiuk commented on scripts/in_container/_in_container_script_init.sh
> +in_container_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
```suggestion
IN_CONTAINER_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
readonly IN_CONTAINER_DIR
```

2020-10-22 18:00 UTC, potiuk commented on scripts/in_container/_in_container_script_init.sh
> +. "${in_container_dir}/_in_container_utils.sh"
```suggestion
. "${IN_CONTAINER_DIR}/_in_container_utils.sh"
```

2020-11-04 00:25 UTC, kaxil commented
Can you please rebase your PR on latest Master since we have applied [Black](https://github.com/apache/airflow/commit/4e8f9cc8d02b29c325b8a5a76b4837671bdf5f68) and [PyUpgrade](https://github.com/apache/airflow/commit/8c42cf1b00c90f0d7f11b8a3a455381de8e003c5) on Master.

It will help if your squash your commits into single commit first so that there are less conflicts.

2021-03-01 00:30 UTC, closed without merging