Remove thrift as a core dependency
apache/airflow pull request #13471
Opened 2021-01-04 23:27 UTC by kaxil

`thrift` is a dependency for Apache Hive and it is not required by Core Airflow:

```
airflow/providers/apache/hive/hooks/hive.py:489:        # This is for pickling to work despite the thrift hive client not
airflow/providers/apache/hive/hooks/hive.py:500:        """Returns a Hive thrift client."""
airflow/providers/apache/hive/hooks/hive.py:502:        from thrift.protocol import TBinaryProtocol
airflow/providers/apache/hive/hooks/hive.py:503:        from thrift.transport import TSocket, TTransport
airflow/providers/apache/hive/hooks/hive.py:531:            from thrift_sasl import TSaslClientTransport
airflow/providers/apache/hive/sensors/hive_partition.py:41:    :param metastore_conn_id: reference to the metastore thrift service
airflow/providers/apache/hive/sensors/metastore_partition.py:28:    queries generated by the Metastore thrift service when hitting
airflow/providers/apache/hive/sensors/named_hive_partition.py:36:    :param metastore_conn_id: reference to the metastore thrift service
```

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

2021-01-04 23:48 UTC, kaxil commented
Test failure is unrelated -- Master is broken

2021-01-05 07:27 UTC, XD-DENG approved these changes
This change itself is good to me.

One more point (not sure if we should cover together here): dependency `thrift_sasl` is under `kerberos` currently, but actually its only usage (imported) is in Hive Hook. Is a fix needed for that?

2021-01-05 07:53 UTC, turbaszek approved these changes

2021-01-05 09:02 UTC, potiuk requested changes
When we remove (and only when you remove)  anything from the list here, we should increase PIP_DEPENDENCIES_EPOCH_NUMBER approproately. I updated the outdated description in in #13409 and we should update increase the PIP_DEPENDENCIES_EPOCH_NUMBER number to point to both Dockerfile and Dockerfile.ci and to the right name. Let's merge #13409 first and then we can rebase on top of it, change the EPOCH and get it removed.

2021-01-07 12:18 UTC, ashb commented
> When we remove (and only when you remove) anything from the list here, we should increase PIP_DEPENDENCIES_EPOCH_NUMBER approproately. I updated the outdated description in in #13409 and we should update increase the PIP_DEPENDENCIES_EPOCH_NUMBER number to point to both Dockerfile and Dockerfile.ci and to the right name. Let's merge #13409 first and then we can rebase on top of it, change the EPOCH and get it removed.

Except in this case we haven't actually removed the dep, at least not what is installed via the extras ;)

2021-01-07 13:06 UTC, potiuk commented
> Except in this case we haven't actually removed the dep, at least not what is installed via the extras ;)

True. I just prefer to be cautious and do it always. The way how PIP treats `install requires` when doing eager dependency update (so after it gets merged) might work in unexpected ways - depending if thrift is pre-installed before or not. 

But yeah, probably in this case there are no scenarios where it would hurt us.

2021-01-07 13:07 UTC, potiuk approved these changes

2021-01-07 13:08 UTC, potiuk commented
It's OK for me. Just do it on your own risk ;)

2021-01-07 20:00 UTC, merged