add ability to pass region_name to EmrAddStepsOperator
apache/airflow pull request #13791
Opened 2021-01-20 15:46 UTC by andriisoldatenko

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

2021-01-20 15:53 UTC, subkanthi approved these changes

2021-01-20 20:52 UTC, RosterIn requested changes

2021-01-20 20:52 UTC, RosterIn commented on airflow/providers/amazon/aws/operators/emr_add_steps.py
> +        self.region_name = region_name
```suggestion
        self.region_name = region_name
```

2021-02-01 17:02 UTC, feluelle approved these changes

2021-02-01 17:05 UTC, feluelle commented
I re-ran the jobs, because one was failing(, I think unrelated).

2021-02-05 04:23 UTC, dstandish commented
> possible fix for #13785

this is not strictly necessary, and not strictly a bug.  region is configurable in the airflow connection (and if using system creds, of course configurable on your system).  

you add kwargs for aws client by putting `config_kwargs` in conn extra: https://github.com/apache/airflow/blob/master/airflow/providers/amazon/aws/hooks/base_aws.py#L371

2021-02-08 10:05 UTC, feluelle commented
True. But it is a "possible fix" isn't it?

It still makes sense to configure the region at this stage. We also have done this for other aws operator as far as I remember.

2021-02-08 10:49 UTC, dstandish commented
yeah my offering of that solution with the status quo is not meant to indicate oppostion, just saying, you can to this with airflow conn and that's what that user ought to do

having this kindof thing also configurable as params can be convenient and i offer no objection to its addition here :)

small correction on my comment above... as ash pointed out on that issue ... you can put region at top level in conn extra (i think the key is `region_name` and don't need to nest it under `config_kwargs`... a little easier that way

2021-03-31 00:47 UTC, closed without merging