Fix S3ToFTPOperator
apache/airflow pull request #13796
Opened 2021-01-20 19:22 UTC by JavierLopezT

Recently this operator was merged, and even though the tests was passed, the file that the operator creates in the FTP server is empty. This solves the problem.

2021-01-20 19:23 UTC, potiuk commented on airflow/providers/amazon/aws/transfers/s3_to_ftp.py
> +        The desired filename bust be specified here.
```suggestion
        The desired filename must be specified here.
```

2021-01-20 19:24 UTC, potiuk approved these changes
Approve with a small nit :)

2021-01-20 20:48 UTC, RosterIn commented on airflow/providers/amazon/aws/transfers/s3_to_ftp.py
> +        The desired filename must be specified here.
```suggestion
        The desired file name must be specified here.
```

2021-02-05 03:55 UTC, dstandish commented on airflow/providers/amazon/aws/transfers/s3_to_ftp.py
> +        The desired file name must be specified here.
```suggestion
    :param ftp_path: The ftp remote path where the file will be stored, inclusive of filename.
```

2021-02-05 03:55 UTC, dstandish commented on airflow/providers/amazon/aws/transfers/s3_to_ftp.py
> +        establish a connection to S3.
was correct before

2021-02-06 17:20 UTC, mik-laj commented on airflow/providers/amazon/aws/transfers/s3_to_ftp.py
>      This operator enables the transferring of files from S3 to a FTP server.
```suggestion
    This operator enables the transferring of files from S3 to a FTP server.

```
It's needed to build docs.

2021-04-16 16:04 UTC, xinbinhuang commented
@JavierLopezT can you fix the pylint error thanks :)

2021-05-04 09:22 UTC, ashb requested changes
An easier fix/smaller change:

Add `os.seek(local_tmp_file, os.SEEK_SET, 0)` and keep the rest of the code the same..

2021-05-04 09:22 UTC, ashb commented on airflow/providers/amazon/aws/transfers/s3_to_ftp.py
> +        aws_conn_id='aws_default',
Please don't change the order of the parameters.

2021-05-06 12:58 UTC, JavierLopezT commented
> An easier fix/smaller change:
> 
> Add `os.seek(local_tmp_file, os.SEEK_SET, 0)` and keep the rest of the code the same..

With your suggestion I get the error:
`AttributeError: module 'os' has no attribute 'seek'`

I have tried also with 
`s3_obj.seek(local_tmp_file, os.SEEK_SET, 0)`

and then I get
AttributeError: 's3.Object' object has no attribute 'seek'

2021-06-10 16:33 UTC, jhtimmins commented
@ashb can you take another look to see if your requested changes have been addressed?

2021-06-11 16:37 UTC, ashb submitted a review, later dismissed
Please use `local_tmp_file.seek(0)` instead of changing how we download the object from S3, as it makes the change much smaller!

2021-06-11 17:15 UTC, JavierLopezT commented
> Please use `local_tmp_file.seek(0)` instead of changing how we download the object from S3, as it makes the change much smaller!

I think I've just uploaded the change you requested

2021-06-17 11:34 UTC, potiuk approved these changes

2021-06-17 11:35 UTC, merged