Add `exists_ok` flag
apache/airflow pull request #14026
Opened 2021-02-02 13:28 UTC by uma66

Add an `exists_ok` flag to `BigQueryCreateEmptyTableOperator` and `BigQueryCreateEmptyDatasetOperator`.
It makes it possible to ignore "already exists" errors.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

2021-02-06 16:32 UTC, ephraimbuddy requested changes
Just nitpicking here, LGTM

2021-02-06 16:32 UTC, ephraimbuddy commented on airflow/providers/google/cloud/operators/bigquery.py
> +    :param exists_ok: If ``True``, ignore "already exists" errors when creating the DATASET.
```suggestion
    :param exists_ok: If ``True``, ignore "already exists" errors when creating the dataset.
```

2021-02-06 16:32 UTC, ephraimbuddy commented on airflow/providers/google/cloud/operators/bigquery.py
> +    :param exists_ok: If ``True``, ignore "already exists" errors when creating the DATASET.
```suggestion
    :param exists_ok: If ``True``, ignore "already exists" errors when creating the dataset.
```

2021-02-06 18:43 UTC, ephraimbuddy approved these changes

2021-02-13 13:30 UTC, turbaszek approved these changes

2021-02-13 13:31 UTC, merged