Remember expanded task groups in localStorage
apache/airflow pull request #14661
Opened 2021-03-08 13:35 UTC by yuqian90

This PR makes the web UI restore previously expanded TaskGroups when the page is refreshed or re-opened. This is to preserve the look of the DAG across sessions. This is done by storing the list of expanded group_ids in `localStorage`.

2021-03-08 18:03 UTC, bbovenzi commented
Good idea! I like the pruning as well for when Dags change.
+1

2021-03-08 19:19 UTC, ryanahamilton requested changes
@yuqian90 this is a nice feature, thank you!

We're in the process of migrating all of our JavaScript to external files (#14115) so we can integrate linting in our pre-commit hooks (#14154). There is some syntax currently that doesn't align with our current config. Would you mind updating those (left comments inline) to save us some time with these other efforts? (please double-check that my suggestions are indeed correct)

2021-03-08 19:19 UTC, ryanahamilton commented on airflow/www/templates/airflow/graph.html
> +          localStorage.removeItem(focused_group_key(dag_id))
```suggestion
          localStorage.removeItem(focused_group_key(dag_id));
```

2021-03-08 19:19 UTC, ryanahamilton commented on airflow/www/templates/airflow/graph.html
> +          localStorage.removeItem(focused_group_key(dag_id))
```suggestion
          localStorage.removeItem(focused_group_key(dag_id));
```

2021-03-08 19:19 UTC, ryanahamilton commented on airflow/www/templates/airflow/graph.html
> +      }
```suggestion
      function get_all_group_ids(group) {
        var children = [group.id];

        for (const [key, val] of Object.entries(group.children)) {
          if (val.children != undefined) {
            // group
            const sub_group_children = get_all_group_ids(val);
            for (const id of sub_group_children) {
              children.push(id);
            }
          }
        }
        return children;
      }
```

2021-03-08 19:19 UTC, ryanahamilton commented on airflow/www/templates/airflow/graph.html
> +          return `expanded_groups_${dag_id}`
```suggestion
          return `expanded_groups_${dag_id}`;
```

2021-03-08 19:19 UTC, ryanahamilton commented on airflow/www/templates/airflow/graph.html
> +          return `focused_group_${dag_id}`
```suggestion
          return `focused_group_${dag_id}`;
```

2021-03-08 19:19 UTC, ryanahamilton commented on airflow/www/templates/airflow/graph.html
> +            localStorage.setItem(focused_group_key(dag_id), node_id)
```suggestion
            localStorage.setItem(focused_group_key(dag_id), node_id);
```

2021-03-08 19:19 UTC, ryanahamilton commented on airflow/www/templates/airflow/graph.html
> +
```suggestion
        if (focus) {
          focus_group(node_id);
        }

```

2021-03-08 19:19 UTC, ryanahamilton commented on airflow/www/templates/airflow/graph.html
> +        remove_expanded_group(node_id, node)
```suggestion
        remove_expanded_group(node_id, node);
```

2021-03-08 19:19 UTC, ryanahamilton commented on airflow/www/templates/airflow/graph.html
> +        const all_group_ids = new Set(get_all_group_ids(nodes))
```suggestion
        const all_group_ids = new Set(get_all_group_ids(nodes));
```

2021-03-08 19:19 UTC, ryanahamilton commented on airflow/www/templates/airflow/graph.html
> +        expanded_groups = Array.from(expanded_groups).filter(group_id => all_group_ids.has(group_id))
```suggestion
        expanded_groups = Array.from(expanded_groups).filter(group_id => all_group_ids.has(group_id));
```
```suggestion
        expanded_groups = Array.from(expanded_groups).filter(group_id => all_group_ids.has(group_id))
```

2021-03-08 19:19 UTC, ryanahamilton commented on airflow/www/templates/airflow/graph.html
> +        localStorage.setItem(expanded_groups_key(dag_id), JSON.stringify(expanded_groups))
```suggestion
        localStorage.setItem(expanded_groups_key(dag_id), JSON.stringify(expanded_groups));
```

2021-03-08 19:19 UTC, ryanahamilton commented on airflow/www/templates/airflow/graph.html
> +        localStorage.setItem(expanded_groups_key(dag_id), JSON.stringify(Array.from(expanded_groups)))
```suggestion
        expanded_groups.add(node_id);
        localStorage.setItem(expanded_groups_key(dag_id), JSON.stringify(Array.from(expanded_groups)));
```

2021-03-08 19:19 UTC, ryanahamilton commented on airflow/www/templates/airflow/graph.html
> +        localStorage.setItem(expanded_groups_key(dag_id), JSON.stringify(Array.from(expanded_groups)))
```suggestion
        const child_group_ids = get_all_group_ids(node);
        child_group_ids.forEach(child_id => expanded_groups.delete(child_id));
        localStorage.setItem(expanded_groups_key(dag_id), JSON.stringify(Array.from(expanded_groups)));
```

2021-03-08 19:19 UTC, ryanahamilton commented on airflow/www/templates/airflow/graph.html
> +        })
```suggestion
        node.children.forEach(function (child_node) {
            if (expanded_groups.has(child_node.id)) {
                expand_group(child_node.id, g.node(child_node.id), false);
                expand_saved_groups(expanded_groups, child_node);
            }
        });
```

2021-03-08 19:19 UTC, ryanahamilton commented on airflow/www/templates/airflow/graph.html
> +    prune_invalid_saved_group_ids()
```suggestion
    prune_invalid_saved_group_ids();
```

2021-03-08 19:19 UTC, ryanahamilton commented on airflow/www/templates/airflow/graph.html
> +    const focus_node_id = localStorage.getItem(focused_group_key(dag_id))
```suggestion
    const focus_node_id = localStorage.getItem(focused_group_key(dag_id));
```

2021-03-08 19:19 UTC, ryanahamilton commented on airflow/www/templates/airflow/graph.html
> +    const expanded_groups = get_saved_groups(dag_id)
```suggestion
    const expanded_groups = get_saved_groups(dag_id);
```

2021-03-08 19:19 UTC, ryanahamilton commented on airflow/www/templates/airflow/graph.html
> +    expand_group(null, nodes)
```suggestion
    expand_group(null, nodes);
```

2021-03-08 19:19 UTC, ryanahamilton commented on airflow/www/templates/airflow/graph.html
> +    expand_saved_groups(expanded_groups, nodes)
```suggestion
    expand_saved_groups(expanded_groups, nodes);
```

2021-03-08 19:19 UTC, ryanahamilton commented on airflow/www/templates/airflow/graph.html
> +      focus_group(focus_node_id)
```suggestion
    if (g.hasNode(focus_node_id)) {
       focus_group(focus_node_id);
    }
     
```

2021-03-12 15:10 UTC, ryanahamilton approved these changes
@yuqian90 thank you for making those updates! I tested this out locally and it works great.

2021-03-12 15:11 UTC, merged