Ensure we use ti.queued_by_job_id
apache/airflow pull request #14795
Opened 2021-03-15 09:30 UTC by atrbgithub

Ensure that we use ti.queued_by_job_id when searching for pods.

When a task is adopted by a new scheduler, the id of the current task is used:
https://github.com/apache/airflow/blob/feb6b8107e1e01aa1dae152f7b3861fe668b3008/airflow/executors/kubernetes_executor.py#L620-L623

When this is successful the task instance is updated, and `queued_by_job_id` is updated with the id of the current scheduler:
https://github.com/apache/airflow/blob/feb6b8107e1e01aa1dae152f7b3861fe668b3008/airflow/jobs/scheduler_job.py#L1877-L1878

Therefore when we search for the pod labels on subsequent scheduler relaunches, we must search for pods using the `queued_by_job_id` and not `external_executor_id`, as we are currently doing:
https://github.com/apache/airflow/blob/feb6b8107e1e01aa1dae152f7b3861fe668b3008/airflow/executors/kubernetes_executor.py#L592

`external_executor_id` is static and never appears to be updated when tasks are adopted. 

This relates to https://github.com/apache/airflow/issues/13808

2021-03-15 14:57 UTC, ashb commented
Paging @dimberman

2021-03-16 16:01 UTC, samwedge commented
It would be great to get a steer on whether this change is acceptable/safe, even if the PR isn't approved at this stage.

2021-03-17 15:24 UTC, eejbyfeldt commented
The celery_executor also uses `external_executor_id` in its implementation of `try_adopt_task_instances`:
https://github.com/apache/airflow/blob/2a2adb3f94cc165014d746102e12f9620f271391/airflow/executors/celery_executor.py#L469-L470
Does it also experience these problems?

2021-03-17 16:48 UTC, ashb requested changes, later dismissed
Okay, I understand the problem, but this doesn't quite feel like the right fix. I'm digging in a problem to look at what a better fix might be.

Additionally you will need to add unit tests the cover this case please.

2021-03-19 10:08 UTC, samwedge commented
Hi Ash,

Not sure we want to spend time adding unit tests if you don't feel this is the right fix.

Do we think a better solution would be to merge `queued_by_job_id` and `external_executor_id`? As far as I can see, they serve the same purpose.

2021-03-19 10:58 UTC, ashb commented
Hi @samwedge There could be value in the unit tests anyway, as they should show the problem is fixed (i.e. that the task is not adopted tiwce/orphaned) without getting in to implementation details.

But it's also cool if you want to hold off on doing this for now.

2021-03-19 15:55 UTC, samwedge commented
Thanks. I agree if we can get a nice generic test in place that doesn't have any implementation detail, then it's worth adding in.

That said, I've been looking at where to make the change. My first thought was in `test_kubernetes_executor` as this is the executor we have changed. But really, the bug only shows itself when calling `SchedulerJob.adopt_or_reset_orphaned_tasks()`. Adding a test here means setting up a `KubernetesExecutor` with a lot of mocking/patching. And I'm not sure this is the best place for it.

Alternatively, do you think this is a candidate for a system test?

2021-03-29 11:24 UTC, samwedge commented
@ashb Just wondered if you had any further thoughts on my previous message. In particular, where the unit test might live. It will need to test the integration between `SchedulerJob` and the `KubernetesExecutor`. I don't want to muddy the existing test files, which seem to test each in isolation.

2021-03-29 18:56 UTC, dimberman commented
@samwedge are you able to reproduce the error in a system test? I think if you can make it fail then a system test should be sufficient here.

2021-04-06 12:41 UTC, samwedge commented
> @samwedge are you able to reproduce the error in a system test? I think if you can make it fail then a system test should be sufficient here.

Sorry for the silence @dimberman, trying to find some time to work on this. I'm fine with the unit and integration tests, but have never run the system tests before. I'll take a look and drop a message on Slack if I have any issues.

2021-04-22 16:41 UTC, ashb commented
I was so wrong on this. I didn't realise that we are already re-setting ti.queued_by_job_id on adoption.

(Given _I wrote that code_ I probably should do. But, well, 2020 was looooong.)

2021-04-23 21:43 UTC, kaxil commented
@samwedge @atrbgithub Can we merge https://github.com/autotraderuk/airflow/pull/2 and rebase the PR on master please so that we can merge it

2021-04-26 13:41 UTC, kaxil approved these changes

2021-04-26 21:19 UTC, merged