Remove dags_folder path from dag.fileloc
apache/airflow pull request #14900
Opened 2021-03-19 18:19 UTC by JCoder01

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

2021-03-19 18:25 UTC, XD-DENG requested changes, later dismissed
May you please clarify why you need this change and why it's generally useful to other users as well? e.g., I personally prefer to include dags foler path.

2021-03-19 18:35 UTC, JCoder01 commented
@XD-DENG see https://github.com/apache/airflow/issues/8061. If you your workers have have their dags in a different location than the scheduler then the command passed to Celery doesn't work. e.g. if your scheduler has `/opt/airflow/dags` but on your worker the dags are at `/var/airflow` (or in my case in my home dir) then the airflow command that is passed to the worker includes `--subdir /opt/airflow/dags` and files because the dags are actually in a different location. I would also like to point out that this is not new functionality, it existed before and has since broke.

2021-03-19 18:45 UTC, XD-DENG commented
Hi @JCoder01 , even though what you are referring to is not a new functionality, `fileloc` has been an absolute path along the way.

What I would suggest are:
- have a proper PR description here to share why this change is needed. If you didn't provide the link to the Issue, people (at least me) do not know where this PR's idea is coming from.
- I would encourage more concrete discussion on whether the requirement/need raised in the Issue https://github.com/apache/airflow/issues/8061 has to be addressed in this way (or if this is the best way). I don't yet have a good proposal, hence I will cancel my review so that any other committer who finds this change good enough can merge.

2021-03-20 12:32 UTC, JCoder01 commented
Closing MR, "Fixed" this in my local install by monkey patching `TaskInstance.generate_command` in airflow_local_settings.py

2021-03-20 12:32 UTC, closed without merging