Infinite pools: Make their `total_slots` be `maxint`-like instead of `-1`
apache/airflow pull request #15247
Opened 2021-04-07 09:43 UTC by bperson

Should fix #14515.

I saw 3 ways of fixing it:
1. do a DB migration to represent an infinite pool with `maxint` slots instead of `-1`.
2. do the same thing but at runtime in `slots_stats`.
3. get `_executable_task_instances_to_queued` to understand `-1` pools, changing all code operating on `pool_slots_free` and `open_slots ` [#](https://github.com/apache/airflow/blob/master/airflow/jobs/scheduler_job.py#L908) [#](https://github.com/apache/airflow/blob/master/airflow/jobs/scheduler_job.py#L975) [#](https://github.com/apache/airflow/blob/master/airflow/jobs/scheduler_job.py#L992) [#](https://github.com/apache/airflow/blob/master/airflow/jobs/scheduler_job.py#L1045) [#](https://github.com/apache/airflow/blob/master/airflow/jobs/scheduler_job.py#L1060)

As to why I chose 2:
1. could be a decent alternative but it's a DB migration with all the complexities inherent to it.
2. is relatively non-intrusive: it's almost free to do it at runtime and it keeps the change completely in the core Python part of Airflow ( in case someone out there directly creates pools by inserting them in his DB 😨 )
3. has the benefit of truly handling infinite pools but I doubt anyone has reached a scale where it matters ( we're talking about a pool with `9223372036854775807` slots here on my system ), plus it increases the overall complexity of that function which is close to the core of the scheduler, we might as well try to keep it as lean as possible.

2021-04-07 14:35 UTC, uranusjr commented
If typing is applied well to the related code path, declaring `total` (and `open` since it’s calculated from it) to `Optional[int]` instead would be a better variant to option 3.

2021-05-27 14:37 UTC, ashb commented on airflow/models/pool.py
> +                total_slots = maxsize
The one downside to this is that it would then be logged as `9223372036854775807 slots free` etc.

It breaks/is lying about the type, but how about:

```suggestion
                total_slots = float('inf')  # type: ignore
```

Because this has all the properties we want:

- Anything subtracted from it is still infinity
- It is greater than any actual number.

2021-05-27 14:37 UTC, ashb requested changes
See comment

2021-06-04 13:39 UTC, bperson commented on airflow/models/pool.py
> +                total_slots = maxsize
Great idea, and existing log end up pretty solid too:
```
[2021-06-04 13:37:28,963] {scheduler_job.py:993} INFO - Figuring out tasks to run in Pool(name=infinite_pool) with inf open slots and 1 task instances ready to be queued
[2021-06-04 13:37:28,963] {scheduler_job.py:1021} INFO - DAG SchedulerJobTest.test_infinite_pool has 0/16 running and queued tasks
[2021-06-04 13:37:28,963] {scheduler_job.py:1086} INFO - Setting the following tasks to queued state:
	<TaskInstance: SchedulerJobTest.test_infinite_pool.dummy 2016-01-01 00:00:00+00:00 [scheduled]>
```

2021-06-11 13:23 UTC, uranusjr commented
Eh, what is the bot doing?

2021-06-11 13:42 UTC, potiuk commented
Strange

2021-06-11 14:49 UTC, ashb approved these changes

2021-06-11 16:04 UTC, ashb commented
@bperson We've got a test failure:

```   E       AssertionError: assert {'default_poo... 'total': -1}} == {'default_poo...'total': inf}}
  E         Omitting 1 identical items, use -vv to show
  E         Differing items:
  E         {'test_pool': {'open': -1, 'queued': 1, 'running': 1, 'total': -1}} != {'test_pool': {'open': inf, 'queued': 1, 'running': 1, 'total': inf}}
  E         Use -v to get the full diff
```

2021-06-12 07:43 UTC, bperson commented
@ashb sorry about that, it should be better now ( though Ci seems to be stuck in an endless 404-ing loop right now 😅 )

2021-06-14 11:32 UTC, ashb commented
I have rebased to latest main, hopefully that should fix the 404

2021-06-14 13:21 UTC, ashb commented
Damnit pymsql:

> TypeError: unsupported operand type(s) for -: 'float' and 'decimal.Decimal'

2021-06-22 08:31 UTC, merged