Refactor: added type annotation
apache/airflow pull request #16668
Opened 2021-06-25 20:19 UTC by AliMuhammadOfficial

Refactor: added type annotation
---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

2021-06-26 19:19 UTC, potiuk commented
Some static chceks are failling. I highly recommend to install pre-commit locally to fix them automatically

2021-06-27 06:20 UTC, uranusjr commented on tests/build_provider_packages_dependencies.py
> +        self.filename: str = filename
I don’t think this is needed, Mypy is able to infer this from the argument type IIRC.

2021-06-27 08:08 UTC, uranusjr requested changes

2021-06-27 08:08 UTC, uranusjr commented on tests/build_provider_packages_dependencies.py
> +
```suggestion
    def __init__(self, filename: str) -> None:
```

(suggested by flake8)

2021-06-27 16:01 UTC, uranusjr approved these changes
Pylint is still complaining but that’s not for this PR to handle 😞

2021-06-27 18:14 UTC, merged