Move ci images to ghcr.io
apache/airflow pull request #16797
Opened 2021-07-04 13:33 UTC by potiuk

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

2021-07-04 22:51 UTC, uranusjr requested changes
Not comprehensive, I only browsed through the documentation files and some of the build scropts

2021-07-04 22:51 UTC, uranusjr commented on BREEZE.rst
> +              -- github-image-id 9a621eaa394c0a0a336f8e1b31b35eff4e4ee86e' - pull/use image with SHA
Typo?

2021-07-04 22:51 UTC, uranusjr commented on BREEZE.rst
> +        to pull/push images.
```suggestion
        For GitHub repository, '--github-repository' can be used to choose repository
        to pull/push images.
```

2021-07-04 22:51 UTC, uranusjr commented on CI.rst
> +to be able to write to the registry.
```suggestion
We use `GitHub Container Registry <https://docs.github.com/en/packages/guides/about-github-container-registry>`_.
``GITHUB_TOKEN`` is needed to push to the registry and we configured scopes of the tokens in our jobs
to be able to write to the registry.
```

2021-07-04 22:51 UTC, uranusjr commented on CI.rst
> +  the released Production Airflow images. It is at https://dockerhub.com/apache/airflow
```suggestion
* **GitHub Image Registry** - image registry used as build cache for CI jobs.
  It is at https://ghcr.io/apache/airflow
* **DockerHub Image Registry** - image registry used to pull base Python images and (manually) publish
  the released Production Airflow images. It is at https://dockerhub.com/apache/airflow
```

2021-07-10 16:44 UTC, potiuk commented
All fixed, but it depends on #16780  which must be merged first

2021-07-12 15:35 UTC, potiuk commented
Ok. Rebased after merge of the prev. Pr :)

2021-07-12 15:35 UTC, potiuk commented
@uranusjr  ?

2021-07-14 01:46 UTC, uranusjr approved these changes
So much duplication but I assume it's unavoidable.

2021-07-14 05:39 UTC, merged

2021-07-14 05:44 UTC, potiuk commented
> So much duplication but I assume it's unavoidable.

We will remove some of those when we change breeze to pyhon. But yeah, some duplication when it comes to names of files at least is unavoidable I think as we have things  out- and in- container.