Fix issue #17371
apache/airflow pull request #17408
Opened 2021-08-04 10:31 UTC by vijayakumarpattanashetti

closes: #17371

Fixed the bug with SparkKubernetesOperator in loading the file.

2021-08-04 10:49 UTC, uranusjr requested changes

2021-08-04 10:49 UTC, uranusjr commented on airflow/providers/cncf/kubernetes/operators/spark_kubernetes.py
> +            body=open(self.application_file).read(),
Don’t do this. Use either `with open(...)` or `pathlib.Path(...).read_text()` instead.

Also, please specify `encoding="utf8")`.

2021-08-09 18:51 UTC, vijayakumarpattanashetti commented
Hi @uranusjr , modified the code. Kindly review.

2021-08-11 05:42 UTC, uranusjr commented on airflow/providers/cncf/kubernetes/operators/spark_kubernetes.py
> +        with open(self.application_file, 'r', encoding='utf-8') as app_file:
The `r` part is not technically needed, but this is also fine.

2021-08-11 05:42 UTC, uranusjr approved these changes

2021-08-11 05:44 UTC, uranusjr requested changes
Wait no, I don’t think this is right. `application_file` can be either a path *or a JSON string*, so just passing it to `open` is wrong.

2021-08-11 05:51 UTC, vijayakumarpattanashetti commented
> Wait no, I don’t think this is right. `application_file` can be either a path _or a JSON string_, so just passing it to `open` is wrong.

No, `application_file` should only take the path to the files with the extensions `template_ext = ('.yaml', '.yml', '.json')`.

2021-08-11 07:02 UTC, uranusjr commented
That’s not what the documentation says.

2021-08-14 21:05 UTC, potiuk approved these changes

2021-08-14 21:19 UTC, potiuk commented
You need to rebase to latest master

2021-08-25 09:17 UTC, eladkal commented
@vijayakumarpattanashetti static checks are failing. can you please fix it?

2021-09-30 13:24 UTC, eladkal commented
@vijayakumarpattanashetti static checks and tests are still failing. can you please address it and rebase?

2021-11-23 00:06 UTC, closed without merging