Simplify bug report template
apache/airflow pull request #17561
Opened 2021-08-11 21:12 UTC by potiuk

By looking at several tens of issues recently I think I got a bit
better understanding on what people are actually reporting and
which information is really important - and I think the report
template might be vastly shortened, leaving only the important
parts:

* removed some comments that were repetitve and a bit too polite
  (strenghtening the necessity of filling all details
* remove kernel. It's useless and default uname -a produced
  some superfluous artifacts (Github recognising that as issues)
* comment stressing that Airflow version/OS is mandatory
* deployment is now a separate entry detailing all options

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

2021-08-12 18:42 UTC, uranusjr commented
LGTM. I wonder if we should add a “are you interested in submitting a PR to fix this” question like we do in the feature request template. I’ve been in many situations the reporter actually has the issue pretty much worked out and I only needed to ask that question to get a PR. It’d be nice to skip that step.

2021-08-12 21:41 UTC, jedcunningham requested changes

2021-08-12 21:41 UTC, jedcunningham commented on .github/ISSUE_TEMPLATE/bug_report.md
> +<!-- Please include version your deployment tools: docker-compose, k8s, helm, etc -->
```suggestion
<!-- Please include your deployment tools and versions: docker-compose, k8s, helm, etc -->
```

2021-08-12 21:41 UTC, jedcunningham commented on .github/ISSUE_TEMPLATE/bug_report.md
> +**Deployment: Virtualenv/ VM / Docker-compose / K8S / Helm Chart / Managed Airflow Service**:
```suggestion
**Deployment**:

<!-- e.g. Virtualenv / VM / Docker-compose / K8S / Helm Chart / Managed Airflow Service -->
```

2021-08-12 23:52 UTC, potiuk commented
> LGTM. I wonder if we should add a “are you interested in submitting a PR to fix this” question like we do in the feature request template. I’ve been in many situations the reporter actually has the issue pretty much worked out and I only needed to ask that question to get a PR. It’d be nice to skip that step.

Crossed my mind to - we have similar question in "Feature request" and I was also wondering why not here, I thought it might be  a little intimidating, and preventing people from raising an issue, but I think I can make it look good.

2021-08-12 23:58 UTC, potiuk commented
Applied comments :)

2021-08-13 14:09 UTC, jedcunningham commented on .github/ISSUE_TEMPLATE/bug_report.md
> +**OS**:
I think we should flip the order of OS and provider versions.

2021-08-13 14:09 UTC, jedcunningham commented on .github/ISSUE_TEMPLATE/bug_report.md
> +Airflow is a community-managed project and we love to bring new contributors in.
```suggestion
Airflow is a community-managed project and we love to bring new contributors in.
Find us in #airflow-how-to-pr on Slack!
```

2021-08-13 14:09 UTC, jedcunningham commented on .github/ISSUE_TEMPLATE/bug_report.md
> +This is not required, but we are happy to guide you in contribution process
```suggestion
This is absolutely not required, but we are happy to guide you in contribution process
```

2021-08-13 15:55 UTC, potiuk commented on .github/ISSUE_TEMPLATE/bug_report.md
> +**OS**:
Why? I actually deliberately replaced them, thinking that more often that not the problems will be connected with the OS than provider. When I think about an issue raised it's 

`I am running Airflow on MacOS and I have those providers installed`.  The "MacOS" is often much more important which providers are installed. I think providers are important in very small percentage of issues :)

2021-08-13 16:10 UTC, jedcunningham commented on .github/ISSUE_TEMPLATE/bug_report.md
> +**OS**:
To me it makes sense to have airflow version info and os/deployment info grouped 🤷‍♂️. I'm not picky though.

2021-08-13 16:10 UTC, jedcunningham approved these changes

2021-08-13 16:18 UTC, merged