add more information to PodLauncher timeout error
apache/airflow pull request #17953
Opened 2021-08-31 21:08 UTC by jameslamb

Thanks very much for all the work that has gone into v2 of `KubernetesPodOperator`!

This PR proposes two small changes (one for documentation, one to a log message in `PodLauncher`), which I think might help others in debugging task failures when using this operator.

## Description

In my recent experience with `KubernetesPodOperator` (using `airflow` 2.1.0), I've found that for some classes of issues which cause a task to fail, it can be difficult to diagnose them from only the information in the Airflow UI.

For problems where kubernetes is able to create a pod but one or more of its containers fails to start, I've found that the task logs in the Airflow UI look something like this:

```text
[WARN] Pod not yet started: some-pod-amhk4t
[WARN] Pod not yet started: some-pod-amhk4t
[WARN] Pod not yet started: some-pod-amhk4t
...
...
packages/airflow/providers/cncf/kubernetes/utils/pod_launcher.py", line 131, in start_pod
    raise AirflowException("Pod took too long to start")
airflow.exceptions.AirflowException: Pod took too long to start
```

My first thought seeing that log message was "oh ok maybe image pulling is taking a while and I just need to set a higher timeout". My second thought was "ok..'too long' according to what configuration?".

I've found that the Airflow task logs can look like that for any of the following issues:

* referencing a secret that doesn't exist in the target namespace
* requesting an `image` that your pod isn't authorized to pull (e.g., it's in a private repository and you failed to specify `imagePullSecrets`)
* referencing a volume that does not exist

In these cases, diagnosing the issue requires going directly to kubernetes to get the pod events.

I hope that the changes in this PR might save others some debugging time in the future.

Thanks very much for your time and consideration.

2021-09-02 06:58 UTC, ephraimbuddy requested changes
We should also add a test to ensure this exception message is not altered in the future accidentally

2021-09-02 06:58 UTC, ephraimbuddy commented on airflow/providers/cncf/kubernetes/utils/pod_launcher.py
> +                        "for structural errors like a missing imagePullSecret."
```suggestion
                        "for structural errors like a missing imagePullSecret, non-existing Volume etc"
```
What do you think?

2021-09-04 16:57 UTC, jameslamb commented
> We should also add a test to ensure this exception message is not altered in the future accidentally

Ok sure, I can try to do that.

2021-09-04 17:00 UTC, jameslamb commented on airflow/providers/cncf/kubernetes/utils/pod_launcher.py
> +                        "for structural errors like a missing imagePullSecret."
I think this addition might be confusing. The behavior I've mentioned in the PR description can happen if you reference a volume that does not exist, but I think some people might interpret "non-existing Volume" to mean "you forgot to add a necessary volume to the pod spec".

I don't think it's necessary for this message to be an exhaustive list, so I think just having one example  and the advice to go look at pod events is enough.

That said, I'm not a maintainer here so if you still prefer this addition I'd be happy to accept it.

2021-10-09 05:02 UTC, jameslamb commented
@ephraimbuddy ok, I think this is ready for review!

Sorry for the delay in responding to your request. I'm new to contributing to Airflow, so it took me a little while to figure out the test setup and how to mock my way into the point where the exception modified in this PR is raised.

2021-10-09 07:12 UTC, ephraimbuddy approved these changes

2021-10-09 18:15 UTC, jedcunningham commented on airflow/providers/cncf/kubernetes/utils/pod_launcher.py
> +                        "for structural errors like a missing imagePullSecret."
Maybe we should be even more generic, something like this:

```suggestion
                        "to determine why the pod didn't start quickly enough."
```

2021-10-10 04:39 UTC, jameslamb commented on airflow/providers/cncf/kubernetes/utils/pod_launcher.py
> +                        "for structural errors like a missing imagePullSecret."
Sure! I've proposed some new language in https://github.com/apache/airflow/pull/17953/commits/a78f858fc73f426d1205025583e694ef898adc1d.

I think another reference to timeouts (like "didn't start quickly enough") should be avoided. My goal with this pull request is to make it clearer that while this error is triggered by a timeout, it can be observed in situations where configuration or permission issues mean that the pod will NEVER start correctly.

I opened this based on my personal experience using `KubernetesPodOperator`, where I didn't realize I had a typo in the name of an `imagePullSecret`, observed a task failing with this error about timeouts, and spent some time testing higher values of `startup_timeout` trying to resolve the issue.

In my experience so far with `KubernetesPodOperator`, such k8s configuration errors are common and I hope that this error message will save others some time by making it clear that they should check k8s errors before just trying to increase the timeout.

2021-10-12 15:50 UTC, jedcunningham commented on airflow/providers/cncf/kubernetes/utils/pod_launcher.py
> +                        "for structural errors like a missing imagePullSecret."
I see where you are going but as an example, just last week I saw a case where no nodes had enough free resources. There are a ton of reasons why the timeout could be missed, I'm not sure singling out structural errors makes sense to me. I'd rather have no examples in every single exception and just point people to the events. I hear you on the double timeouts reference though. Maybe this instead? Short and sweet:

```
f"Pod took longer than {startup_timeout} seconds to start (startup_timeout)."
" Check the pod events in kubernetes to determine why."
```

Another factor here is that the events should also be logged in the task log (in theory). Did this not happen for you? Feels a little weird to tell folks to "go look at k8s pod events" when it should be logged alongside the same message 🤷‍♂️

2021-10-12 16:40 UTC, jameslamb commented on airflow/providers/cncf/kubernetes/utils/pod_launcher.py
> +                        "for structural errors like a missing imagePullSecret."
> I'd rather have no examples in every single exception and just point people to the events

Ok sure! I'll update to that

> Another factor here is that the events should also be logged in the task log (in theory). Did this not happen for you?

Logging events is turned off by default in `KubernetesPodOperator`.

https://github.com/apache/airflow/blob/b8d06e812ac56af6b0d17830c63b705ace9d4959/airflow/providers/cncf/kubernetes/operators/kubernetes_pod.py#L214

2021-10-12 16:59 UTC, jameslamb commented on airflow/providers/cncf/kubernetes/utils/pod_launcher.py
> +                        "for structural errors like a missing imagePullSecret."
Simplified the message in https://github.com/apache/airflow/pull/17953/commits/b7e54b461f9bdd237ee4ed77fbe4d196bb53037b

2021-10-12 17:15 UTC, jedcunningham approved these changes

2021-10-12 17:16 UTC, jedcunningham commented on airflow/providers/cncf/kubernetes/utils/pod_launcher.py
> +                        "for structural errors like a missing imagePullSecret."
> Logging events is turned off by default

Ah, well that would do it 🙃

2021-10-12 21:19 UTC, merged