[AIRFLOW-510] Hide "paused" DAGs on the HomeView unless "Shown"
apache/airflow pull request #1799
Opened 2016-09-14 20:23 UTC by btallman

Dear Airflow Maintainers,

Please accept this PR that addresses the following issues:
- *https://issues.apache.org/jira/browse/AIRFLOW-510*

Testing Done:
- UI only, and as far as I can tell, we don't have UI test coverage yet

2016-09-14 21:15 UTC, jbalogh commented
Shouldn't showing them be the default? I only go to the dag list page to pause and unpause dags. Hiding the paused dags means I have to learn where to toggle showing the paused dags before I can unpause it.

2016-09-15 04:28 UTC, btallman commented
I'm not sure about your install, but in ours, the HomeView needs to be primarily a dashboard of current status. And there is no simple way to hide old DAGs. The default view for a developer is very different from that of a DevOps person.

2016-09-15 05:57 UTC, btallman commented
I added screenshots to the PR, so people can see.

2016-09-15 17:33 UTC, jbalogh commented
It sounds like you're using Pause as a proxy for hiding old dags? That seems like a somewhat orthogonal problem.

I use Pause as a temporary state when we need to make operational changes, so having the HomeView show paused dags is pretty important for understanding our current status.

2016-09-15 17:46 UTC, zodiac commented
I would prefer if show paused dags were the default (ie without any query params passed) and users could optionally hide paused dags

2016-09-15 17:47 UTC, zodiac commented on airflow/www/templates/airflow/dags.html
> +      var dt = $('#dags').dataTable({
Use a more descriptive variable name

2016-09-15 17:47 UTC, zodiac commented on airflow/www/templates/airflow/dags.html
> +//      debugger;
what's this?

2016-09-15 17:49 UTC, zodiac commented on airflow/www/views.py
> +            unfiltered_webserver_dags = [dag for dag in dagbag.dags.values() if not dag.parent_dag]
if we're adding yet another filter to the existing ones we need to rename the variables `do_filter`, `unfiltered_webserver_dags` etc

2016-09-15 17:49 UTC, ldct requested changes

2016-09-15 17:50 UTC, btallman commented
That actually requires a config param, as the links would no longer solve
the underlying issue. The point is to have the default uncluttered so you
can scan the HomeView. Having to click a link to get to the Scanable View
makes not a useful feature. Basically, you only need to un-pause something
once, but you need to scan the list regularly.

Thanks,
Ben

--
Ben Tallman - 503.680.5709

On Thu, Sep 15, 2016 at 10:46 AM, Li Xuanji <notifications@github.com>
wrote:

> I would prefer if show paused dags were the default (ie without any query
> params passed) and users could optionally hide paused dags
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/apache/incubator-airflow/pull/1799#issuecomment-247399763>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAKnfkcrsj519oa8zK6y4nIsgx86_8U6ks5qqYSSgaJpZM4J9M0y>
> .
>

2016-09-15 18:01 UTC, zodiac commented
how about sorting the dags so that paused ones are displayed last? would that fit your use-case?

2016-09-15 18:06 UTC, btallman commented
Well, not really.

Given the number of DAGs that get loaded into the DB over time, we need to
have a default hidden state for many of them. Pause works well for this, as
it means we are also hiding items that aren't accidentally running. Really,
we don't want them in the list, and our experience is that this is a
challenge for us, as we get into the hundreds of DAGs over time.

To be clear, we can run this as a cherry pick, but I can't really imagine
that this isn't a useful tool for most if not all users in a mature
installation.

Thanks,
Ben

--
Ben Tallman - 503.680.5709

On Thu, Sep 15, 2016 at 11:01 AM, Li Xuanji <notifications@github.com>
wrote:

> how about sorting the dags so that paused ones are displayed last? would
> that fit your use-case?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/apache/incubator-airflow/pull/1799#issuecomment-247403735>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAKnfgnfgTXQLZDhfryZnGMsb2MpOcdaks5qqYgPgaJpZM4J9M0y>
> .
>

2016-09-15 18:12 UTC, btallman commented
That is true Jeff, that's what I'm doing. How do you hide "old" dags?

Thanks,
Ben

--
Ben Tallman - 503.680.5709

On Thu, Sep 15, 2016 at 10:34 AM, Jeff Balogh <notifications@github.com>
wrote:

> It sounds like you're using Pause as a proxy for hiding old dags? That
> seems like a somewhat orthogonal problem.
>
> I use Pause as a temporary state when we need to make operational changes,
> so having the HomeView show paused dags is pretty important for
> understanding our current status.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/apache/incubator-airflow/pull/1799#issuecomment-247396489>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAKnfpSCu1FWjsKv3-fabbaUnBVYCLSmks5qqYGIgaJpZM4J9M0y>
> .
>

2016-09-15 20:47 UTC, jbalogh commented
> That is true Jeff, that's what I'm doing. How do you hide "old" dags?

We don't have old dags. I think your team uses dags much differently than we do. Come to my meetup talk next week to hear more! 😉

2016-09-15 21:25 UTC, zodiac commented
> How do you hide "old" dags?

One way is to delete them :)

2016-09-15 21:27 UTC, btallman commented
Yeah. That complicates historical lookup though... I agree that pause is orthogonal, but it actually solves or problem without adding a new field.

Get Outlook for iOS




On Thu, Sep 15, 2016 at 2:25 PM -0700, "Li Xuanji" <notifications@github.com> wrote:













How do you hide "old" dags?




One way is to delete them :)



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

2016-09-22 06:34 UTC, gwax commented
It seems like it might be possible to get the best of all worlds via parameters in the airflow.cfg file. Perhaps default behavior stays show everything sorted alphabetical but with addition of a "Hide Paused" link.

Then there could be a config section for the UI (if there isn't already) with an option for `hide_paused` that determines whether they hide by default. And possibly even a `sort_paused_last` option as well.

2016-09-22 16:49 UTC, jbalogh commented
Is it worth adding a `retired` knob to the dag model? I feel a little conflicted about that since it's almost the same thing as `paused`, but with a slightly more permanent intention.

I hope we can avoid adding more branches in config since that's hard for developers to work with and hard for users to understand.

2016-10-01 07:27 UTC, r39132 commented
@btallman 

I suggest adding 2 new configuration vars to airflow.cfg:

- `hide_paused_dags` (defaulted to False)
  * This determines whether the DAG Overview page hides DAGs by default. For your org, you may strongly consider setting it to True since you'd like to unclutter your UI.
- `enable_show_hide_paused_dags` (defaulted to False)
  * This determines whether your new feature is enabled/disabled. By default, it will be disabled and the expectation is that the DAG Overview page will look the same as it does today

At Agari, we sometimes pause a DAG and then forget to re-enable it. Hiding paused DAGs would make it easier for us to forget to re-enable them. However, I believe this feature is useful enough to allow merging given an additional configuration parameters.

Another thing I think you need to think about is that your paused dags are still getting parsed. The new scheduler launches a subprocess to parse each dag file.  You can look at `process_file` in `jobs.py`.

2016-10-02 05:02 UTC, zodiac commented
> That complicates historical lookup though...

What do you mean by historical lookup?

2016-10-07 04:44 UTC, r39132 commented
@btallman Any movement on this? I don't think that @zodiac's comment is a blocker. My proposal is that you can add your feature but hidden behind some configs.

2016-10-07 19:49 UTC, btallman commented
Finishing the dag.backfill=False first, but will circle back on this
hopefully today.

Thanks,
Ben

--
Ben Tallman - 503.680.5709

On Thu, Oct 6, 2016 at 9:44 PM, Sid Anand <notifications@github.com> wrote:

> @btallman <https://github.com/btallman> Any movement on this? I don't
> think that @zodiac <https://github.com/zodiac>'s comment is a blocker. My
> proposal is that you can add your feature but hidden behind some configs.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/apache/incubator-airflow/pull/1799#issuecomment-252151855>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAKnfiv798pn1vOl2DyEppoXpezc8TQ_ks5qxc4pgaJpZM4J9M0y>
> .
>

2016-10-08 03:25 UTC, r39132 commented
@btallman great. I will be on call starting next Tuesday and then traveling in Asia the week after, so unless you want to week 2+ weeks on me, best to get it in ASAP.

2016-10-08 18:03 UTC, r39132 commented
@btallman You have a bad merge/rebase here! You've recommitted 50+ previous commits. You'll need to rectify it before this can be considered.

2016-10-12 18:53 UTC, btallman commented
Going to pull this one back, looking at the feedback, and streamline it based on a few of the comments.

2016-10-12 18:54 UTC, closed without merging