[AIRFLOW-591] Contribution: Integration with datadog
apache/airflow pull request #1851
Opened 2016-10-23 21:46 UTC by gtoonstra

Dear Airflow Maintainers,

Please accept this PR that addresses the following issues:
https://issues.apache.org/jira/browse/AIRFLOW-591

Testing Done:
- A unit test is in place for the sensor, which also tests parts of the hook. I system tested the remainder, because a remote service setup is needed to really test this end-to-end.

Looking forward to your comments.

2016-10-24 09:02 UTC, r39132 commented
Interesting.. we use DataDog.. will review and test the PR and get back to you soon.

2016-10-25 05:08 UTC, msumit commented
+1 for idea.. we also use datadog..

2016-10-25 18:57 UTC, alexvanboxel commented
+1 we're evaluating dog, I'll have a talk with our service manager if he likes to try it.

2016-10-28 13:49 UTC, alexvanboxel commented
Maybe add a comment of the extra dependency that needs to be included.

2016-10-31 14:14 UTC, skudriashev requested changes

2016-10-31 14:14 UTC, skudriashev commented on airflow/contrib/hooks/datadog_hook.py
> +    """
Looks like this is wrong place for the docstring.

2016-10-31 14:14 UTC, skudriashev commented on airflow/contrib/hooks/datadog_hook.py
> +    """
Same here.

2016-10-31 14:14 UTC, skudriashev commented on airflow/contrib/hooks/datadog_hook.py
> +            end=now-to_seconds_ago,
Whitespaces around `-` (pep8)

2016-10-31 14:14 UTC, skudriashev commented on airflow/contrib/sensors/datadog_sensor.py
> +        if len(response) > 0:
Just:

```python
    return len(response) > 0
```

2016-10-31 18:01 UTC, gtoonstra commented
I fixed the obvious docstrings. I looked into the whitespaces around - (pep8), but when these are parameters it's supposed to be like this. I ran flake8 and it started complaining when I inserted the spaces.

2016-11-01 07:53 UTC, skudriashev commented
@gtoonstra,

> I fixed the obvious docstrings. I looked into the whitespaces around - (pep8), but when these are parameters it's supposed to be like this. I ran flake8 and it started complaining when I inserted the spaces.

Just make it consistent with previous line.

2016-11-01 17:24 UTC, gtoonstra commented
@skudriashev : I tried doing that, but PEP8 prescribes to not use spaces when the equals sign is used as a keyword argument or default parameter value: 

> Don't use spaces around the = sign when used to indicate a keyword argument or a default parameter value.

The first one is a basic assignment. I'm not sure if one of the options of PEP8 is turned off?

E251 unexpected spaces around keyword / parameter equals

If that warning is turned off, I'll make the change and move forward.

2016-11-02 04:22 UTC, skudriashev commented
@gtoonstra, I've tried locally:

```bash
$ pip install flake8
$ pip freeze
...
flake8==3.0.4
```

```bash
$ flake8 airflow/contrib/hooks/datadog_hook.py
...
tmp.py:58:48: E226 missing whitespace around arithmetic operator                                                                                                                                                                             
tmp.py:98:20: E226 missing whitespace around arithmetic operator
...

Fixing this two lines make linting pass fine.

2016-11-02 06:56 UTC, gtoonstra commented
Allright, flake8 wasn't failing for me because since 2012 E226 is ignored by default. I had to enable this with --select=E226 to get flake8 to complain. Probably you've got this configured on by default. Should be fixed now.

2016-11-03 07:14 UTC, r39132 commented
@gtoonstra can you go ahead and update setup.py with the new dependency (i.e. datadog). You can list it in the extras_require section, such as we do for packages like s3 and postgres, so that you can do `pip install "airflow[s3, postgres]"`

2016-11-03 07:16 UTC, r39132 commented
Also, please squash your commits.

2016-11-04 17:46 UTC, gtoonstra commented
Changes made, commits squashed.

2016-11-14 07:17 UTC, r39132 commented
+1

2016-11-14 07:21 UTC, closed without merging