Update Kubernetes library version and backport pickle-fix for Loggers
apache/airflow pull request #18797
Opened 2021-10-07 09:28 UTC by ashb

Previously we pinned this version as v12 as a change to Kube library
internals meant v1.Pod objects now have a logger object inside them, and
couldn't be pickled on Python 3.6.

To fix that we have "backported" the change in Python 3.7 to make Logger
objects be pickled "by name". (In Python 3.7 the change adds
`__reduce__` methods on to the Logger and RootLogger objects, but here
we achieve it `copyreg` stdlib module so we don't monkeypatch
anything.)

This fix is also applied in to airflow core in a separate commit, but we
also apply it here in the provider so that cncf.kubernetes client
library can be updated but still used with older versions of Airflow
that don't have this fix in.

I think we should *NOT* merge this until after 2.2.0 RC is cut, as I don't think we have time to test the kube client upgrade doesn't break anything before the planned RC release.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

2021-10-07 09:31 UTC, ashb commented
Maybe it is worth splitting this in two actually -- add the reducer for logging to core, but leave the Kube client library version unchanged?

2021-10-07 09:32 UTC, kaxil commented
> Maybe it is worth splitting this in two actually -- add the reducer for logging to core, but leave the Kube client library version unchanged?

Yeah 2 PRs does make sense.

2021-10-07 09:49 UTC, kaxil approved these changes

2021-10-07 13:43 UTC, potiuk approved these changes

2021-10-07 14:26 UTC, jedcunningham approved these changes

2021-10-12 13:52 UTC, ashb commented
Merging now 2.2.0 is out.

2021-10-12 13:53 UTC, ashb commented
Wait -- making sure tests actually run first 😁

2021-11-12 11:48 UTC, ashb commented
Green enough. Merging to mainline for 2.3 -- we shouldn't pull this in to 2.2 series.

2021-11-12 11:48 UTC, ashb commented
Oh wait, the helm tests were cancelled. Those one's probably are important to run. 👀

2021-11-12 11:53 UTC, uranusjr requested changes

2021-11-12 11:53 UTC, uranusjr commented on tests/kubernetes/test_client.py
> +            configuration = Configuration()
```suggestion
        try:
            configuration = Configuration.get_default_copy()
        except AttributeError:
            configuration = Configuration()
```

2022-01-03 11:10 UTC, uranusjr approved these changes

2022-01-03 11:27 UTC, ashb commented
Hmmm helm tests are still timing out here, which means something is not right

2022-01-04 12:01 UTC, ashb commented
Better now after a rebase.

2022-01-04 12:09 UTC, merged

2022-01-17 09:29 UTC, eladkal commented
Removing 2.3.0 milestone as this PR is in the provider release cycle.
Was released in `apache-airflow-providers-cncf-kubernetes` version 3.0.1