Add Guide for Apache Pinot
apache/airflow pull request #18930
Opened 2021-10-13 04:56 UTC by sharon2719

closes: https://github.com/apache/airflow/issues/8194

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

2021-10-13 12:03 UTC, theodesp commented on docs/apache-airflow-providers-apache-beam/operators.rst
> +has the ability to download or available on  the local filesystem (provide the absolute path to it).
```suggestion
has the ability to download or available on the local filesystem (provide the absolute path to it).
```

2021-10-13 12:03 UTC, theodesp commented on docs/apache-airflow-providers-apache-pinot/pinot-operators.rst
> +with low latency. It is suited in contexts where fast analytics,such as aggregations,
```suggestion
with low latency. It is suited in contexts where fast analytics, such as aggregations,
```

2021-10-14 19:15 UTC, eladkal commented
@sharon2719 The static checks are failing. Can you please fix it?

2021-10-14 19:25 UTC, eladkal requested changes

2021-10-14 19:25 UTC, eladkal commented on docs/apache-airflow-providers-apache-beam/operators.rst
> +
Please revert this addition of new line

2021-10-14 19:25 UTC, eladkal commented on docs/apache-airflow/concepts/operators.rst
> +==========
Please revert this change

2021-10-14 19:25 UTC, eladkal commented on docs/apache-airflow-providers-apache-pinot/pinot-operators.rst
> +for (TransformFunction argument : arguments) {
The guide should be about the Airflow operators/hooks.
Specifically: `PinotDbApiHook`  / `PinotAdminHook` 
https://github.com/apache/airflow/blob/main/airflow/providers/apache/pinot/hooks/pinot.py

2021-10-14 19:25 UTC, sharon2719 commented
Do you mind if you can assist me on that issue?

On Thu, Oct 14, 2021, 10:15 PM eladkal ***@***.***> wrote:

> @sharon2719 <https://github.com/sharon2719> The static checks are
> failing. Can you please fix it?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/apache/airflow/pull/18930#issuecomment-943650307>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AS3ZWV7XJYHQKXP437BBE5LUG4T6XANCNFSM5F4IANHQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-10-16 07:33 UTC, eladkal requested changes

2021-10-16 07:33 UTC, eladkal commented on docs/apache-airflow-providers-apache-beam/operators.rst
> +
```suggestion
```

2021-10-16 07:33 UTC, eladkal commented on docs/apache-airflow/concepts/operators.rst
> +==========
```suggestion
=========
```

2021-10-16 07:46 UTC, eladkal approved these changes
Overall LGTM :) 
Left some comments to address

@josh-fell can you take a look at the example DAG?

2021-10-16 07:46 UTC, eladkal commented on docs/apache-airflow-providers-apache-pinot/operators.rst
> +For more information,please see the documentation at `Apache Pinot improvements for PinotAdminHook<https://github.com/apache/incubator-pinot/pull/4110>`
Why do we link to a PR and not to official documentation?

2021-10-16 07:46 UTC, eladkal commented on docs/apache-airflow-providers-apache-pinot/operators.rst
> +This hook uses standard-SQL endpoint since PQL endpoint is soon to be deprecated.
```suggestion
This hook uses standard-SQL endpoint. PQL endpoint is removed in updated versions of pinotdb library. For more information see `library documentation  <https://docs.pinot.apache.org/users/clients/python>`
```

2021-10-16 07:46 UTC, eladkal commented on airflow/providers/apache/pinot/example_dags/example_pinot_dag.py
> +from airflow.providers.apache.pinot.hooks.pinot import PinotDbApiHook
```suggestion
from airflow.providers.apache.pinot.hooks.pinot import PinotAdminHook, PinotDbApiHook
```

2021-10-16 07:53 UTC, sharon2719 commented
Thanks if there is anything else that needs changes let me know with the
dags example.

On Sat, 16 Oct 2021 at 10:46, github-actions[bot] ***@***.***>
wrote:

> The PR is likely OK to be merged with just subset of tests for default
> Python and Database versions without running the full matrix of tests,
> because it does not modify the core of Airflow. If the committers decide
> that the full tests matrix is needed, they will add the label 'full tests
> needed'. Then you should rebase to the latest main or amend the last commit
> of the PR, and push it with --force-with-lease.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/apache/airflow/pull/18930#issuecomment-944875517>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AS3ZWV2EYUKU6E3HSJZ2P3DUHEUWRANCNFSM5F4IANHQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-10-16 13:02 UTC, josh-fell commented on airflow/providers/apache/pinot/example_dags/example_pinot_dag.py
> +    start_date=days_ago(2),
We are currently transitioning all of the example DAGs (and later docs) away from using `days_ago(n)` for `start_date` to a static value since it's best practice when writing pipelines. New examples should use a static `start_date` value.  The updates have been using `datetime()`; the actual value doesn't matter.

2021-10-16 13:02 UTC, josh-fell commented on airflow/providers/apache/pinot/example_dags/example_pinot_dag.py
> +        dag=dag,
The `dag=dag` can be removed since the `DAG` object is being used as a context manager which takes care of passing this arg to all operators.

2021-10-16 13:02 UTC, josh-fell commented on airflow/providers/apache/pinot/example_dags/example_pinot_dag.py
> +        dag=dag,
Would it be possible to show different args for `pinot` and `pinot_options` parameters? Otherwise, seeing as the same args are used for every operator in the DAG, these ideally should be present as `default_args` at the DAG level. However, because the operator documentation is referencing the example DAG, moving the args to `default_args` loses the main context for showcasing the operators in the documentation.

Updating the args to be different between the two would preclude the `default_args` use.  I'm not sure if they need to be the same value when using these operators together in a pipeline though.

2021-10-16 13:02 UTC, josh-fell commented on docs/apache-airflow-providers-apache-pinot/operators.rst
> +`Apache Pinot <https://pinot.apache.org/>`__ is a column-oriented, open-source,distributed data store written in Java. Pinot is designed to execute OLAP querieswith low latency. It is suited in conte
Small nit for spaces:
> ... a column-oriented, open-source,distributed data store written in Java

"... column-oriented, open-source, distributed data store written in Java"

> ... such as aggregations,are needed

"... such as aggregations, are needed ...

2021-10-16 13:02 UTC, josh-fell commented on docs/apache-airflow-providers-apache-pinot/operators.rst
> +For more information,please see the documentation at `Apache Pinot improvements for PinotAdminHook<https://github.com/apache/incubator-pinot/pull/4110>`
Another small nit for a space between "information,please"

2021-10-16 13:02 UTC, josh-fell commented on docs/apache-airflow-providers-apache-pinot/operators.rst
> +For more information, please see the documentation at `Pinot documentation on querrying data <https://docs.pinot.apache.org/users/api/querying-pinot-using-standard-sql>`
"querrying" should be spelled "querying"

2021-10-18 08:28 UTC, eladkal requested changes
There is an error that needs to be fixed:
```
  "/opt/airflow/airflow/providers/apache/pinot/example_dags/example_pinot_dag.py",
  line 28, in <module>
      start_date=datetime(),
  TypeError: Required argument 'year' (pos 1) not found
```

2021-10-18 08:28 UTC, eladkal commented on docs/apache-airflow-providers-apache-pinot/operators.rst
> +`Apache Pinot <https://pinot.apache.org/>`__ is a column-oriented, open-source,distributed data store written in Java. Pinot is designed to execute OLAP querieswith low latency. It is suited in conte
```suggestion
`Apache Pinot <https://pinot.apache.org/>`__ is a column-oriented, open-source, distributed data store written in Java. Pinot is designed to execute OLAP queries with low latency. It is suited in contexts where fast analytics, such as aggregations are needed on immutable data, possibly, with real-time data ingestion.
```

2021-10-27 07:30 UTC, sharon2719 reviewed
Changed already

2021-10-27 07:31 UTC, sharon2719 reviewed
Changed already

2021-11-04 18:14 UTC, eladkal commented
@sharon2719 There are still many unrelated changes in the branch (lower than before tough) please remove all unrelated code changes you can see in https://github.com/apache/airflow/pull/18930/files the files that you are modifying

2022-01-01 00:07 UTC, closed without merging