Jinja templates should be rendered in dict keys
apache/airflow pull request #18938
Opened 2021-10-13 11:34 UTC by zbstof

Currently keys stay unrendered which is confusing for the users and require workaround like explicitly using `Variable.get`, which is evaluated eagerly during dag rendering, leading to further need for workarounds.

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

2021-10-13 11:47 UTC, potiuk requested changes
We need to have some test cases for that

2021-10-13 12:15 UTC, potiuk commented
Wel. The fact that there was a test for that indicates that there **could** be a reason. I cannot think of any as well, but It's better to check it. This is quite crucial part of the code, so I would not like to spoil something.

@BasPH, @kaxil - I'd love to hear your thoughts here. Maybe there is a good reason for not rendering the keys?

2021-10-13 12:54 UTC, BasPH commented
It wasn't me :) This was added a long time ago -> https://github.com/apache/airflow/pull/4292/files

Technically I don't see anything wrong with also templating the keys 👍

2021-10-14 14:51 UTC, potiuk approved these changes

2021-11-12 00:55 UTC, kaxil reviewed
This is a change in behaviour for keys, can you add this change in UPDATING.md please?

2021-12-19 18:50 UTC, eladkal commented
@zbstof can you please address above comment and rebase?

2021-12-20 16:48 UTC, zbstof commented
@eladkal, @kaxil  
I've accidentally closed PR, please re-open
I've also added an entry in `UPDATING.md`, please check if it's good enough

2022-02-13 10:17 UTC, zbstof commented
Ping

нд, 13 лют. 2022, 02:08 користувач github-actions[bot] <
***@***.***> пише:

> This pull request has been automatically marked as stale because it has
> not had recent activity. It will be closed in 5 days if no further activity
> occurs. Thank you for your contributions.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/apache/airflow/pull/18938#issuecomment-1037598181>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAKPUA5YQLUDFE7A4BFSBQLU23ZBLANCNFSM5F465FCQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>

2022-04-01 23:09 UTC, houqp approved these changes

2022-04-01 23:09 UTC, houqp commented
@zbstof , there is a formatting issue that needs to be fixed

2022-04-04 15:19 UTC, potiuk commented
Hmm. This one is very "lightly" breaking change. I can't imagine that someone intentionally had keys containing {{}} but we cannot rule it out completely.

Makes me think that we should really add a flag controlling this behaviour and raise a deprecation warning in case it is disabled and we find a key that contains jinja.

2022-04-12 18:09 UTC, zbstof commented
What's the easiest way of checking whether a string contains jinja2 template. Substring check? I assume jinja templates could be more complex than that

2022-04-12 19:21 UTC, zbstof commented
Can some of you point me to the example of the flag that @potiuk suggested?

2022-04-12 19:23 UTC, potiuk commented
> Can some of you point me to the example of the flag that @potiuk suggested?

Just a new config like all the other: https://github.com/apache/airflow/blob/main/airflow/config_templates/config.yml

2022-04-19 06:09 UTC, potiuk commented
Any news there @zbystof ?

2022-04-20 18:50 UTC, zbstof commented
Something like this, please check. Although due to https://github.com/apache/airflow/pull/22003, changes to `UPDATING.md` are lost

2022-06-13 08:17 UTC, potiuk commented
Conflicts need to be fixed - can you fix them please @zbstof ?

2022-06-13 12:29 UTC, zbstof commented
Fixed conflicts and rebased

2022-06-19 18:26 UTC, potiuk commented
But the tests are failing.

2022-06-29 09:11 UTC, eladkal commented
Tests are still failing
```
tests/models/test_baseoperator.py::TestBaseOperator::test_render_template_with_flag: AssertionError: assert {'key_2': 'ba... foo }}_1': 1} == {'key_2': 'ba...key_bar_1': 1}
  Omitting 1 identical items, use -vv to show
  Left contains 1 more item:
  {'key_{{ foo }}_1': 1}
  Right contains 1 more item:
  {'key_bar_1': 1}
```

2022-07-09 18:38 UTC, zbstof commented
I'm going to have to ask for a bit of help here - why my mocking of the flag doesn't work in the test? Or maybe I'm approaching this test in a completely wrong way?

2022-07-09 18:40 UTC, zbstof commented
I'm going to ask for a bit of help here - why my test does not mock flag value here? Or maybe I'm approaching the test in a completely wrong way?

2022-07-12 09:22 UTC, potiuk commented
Typical problem (been there done that) when you are not used to patching. See the "patching in the wrong place": https://alexmarandon.com/articles/python_mock_gotchas/

2022-09-01 00:14 UTC, closed without merging