Align EcsOperator with DockerOperator capabilities
apache/airflow pull request #19030
Opened 2021-10-17 05:46 UTC by asaf400

Hello, I would like some opinions on this PR, it has no open issue,
but it's something I have encountered and fix locally in Airflow 2.0.2, and the code hasn't change in main branch.

Please note this PR has two main changes:

- adding a missing feature, aligning functionality with similar Operator
- refactoring for efficiency and responsivness sake

1. DockerOperator has** the option to send the entire container log into xcom return_value, not just the last line
EcsOperator doesn't have this option, it defaults to only sending the last line, This commit changes that behaviour, adding xcom_all parameter to the Operator, to enable sending all logs lines.

2. In addition, the get_last_log_message function has been refactored,
In an edge case where the log is bigger than 1 MB (up to 10,000 log events) as per aws docs,
it is possible that the function would cause more than one 'GetLogEvents' AWS API call because it defaults to read the logstream/group from beginning,
and using deque with queue size of 1, it would iterate over the entire generator yields, calling get_log_events as much as it needs,
just so that when the generator is exhausted, the queue would keep only the last event, this is a waste of time and data transfer,
AWS get_log_events method has start_from_head parameter, which can be used to actually tail the event log instead of reading from head!
in combination with a single next() yield, we can ensure we only call get_log_events once, and within the response, grab the last message

** DockerOperator is actually also unstable in regard to xcoms, see issue #18874 and PR #19027

2021-10-17 07:47 UTC, zigius requested changes

2021-10-17 07:47 UTC, zigius commented on airflow/providers/amazon/aws/operators/ecs.py
> +    def _get_log_events(self, start_from_head=True, skip: int = 0) -> Generator:
linting

2021-10-17 07:47 UTC, zigius commented on airflow/providers/amazon/aws/operators/ecs.py
> +    def _get_log_events(self, start_from_head=True, skip: int = 0) -> Generator:
also, add typing to `start_from_head`? and change the order of the params to make sure you preserve backwards compatibility? 
`def _get_log_events(self, skip: int = 0, start_from_head: bool = True) -> Generator:`

2021-10-17 10:35 UTC, uranusjr commented on airflow/providers/amazon/aws/operators/ecs.py
> +    def _get_log_events(self, start_from_head=True, skip: int = 0) -> Generator:
Maybe even make `start_from_head` kwarg-only:

```suggestion
    def _get_log_events(self, skip: int = 0, *, start_from_head: bool = True) -> Generator:
```

This makes signature compatibility easier in the future.

2021-10-27 01:16 UTC, uranusjr requested changes
Please also fix the linter (static check) errors. See the contribution guide for instructions to set up linters locally so you can run the checks before pushing.

2021-10-27 01:16 UTC, uranusjr commented on airflow/providers/amazon/aws/operators/ecs.py
>              return None
This `IndexError` will not work. You probably want `StopIteration` instead.

2021-10-27 01:16 UTC, uranusjr commented on airflow/providers/amazon/aws/operators/ecs.py
> +        return [log['message'] for log in deque(self._get_log_events())]
Using `deque` here is useless here since you end up holding all the messages in memory anyway.

```suggestion
    def get_all_log_messages(self) -> Optional[list]:
        return [log['message'] for log in self._get_log_events()]
```

2021-10-27 01:16 UTC, uranusjr commented on airflow/providers/amazon/aws/operators/ecs.py
> +        xcom_all: Optional[bool] = False,
Why can't this be a simple `bool`? What would passing in `None` mean?

2021-12-18 00:07 UTC, closed without merging