Update CONTRIBUTORS_QUICK_START.rst
apache/airflow pull request #19042
Opened 2021-10-18 09:14 UTC by OyinOlamide

I am Oyinkansola Awosan, an Outreachy applicant for the December to March cohort. I noticed there was an error in the second block of code under the "Pyenv and setting up virtual-env" part of the guide. There was a letter 's' that was causing problems in the 'checking required packages' command.
I have corrected the error. This way other people who want to contribute to Apache won't face this issue I faced.
Thank you. :)

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

2021-10-18 12:06 UTC, uranusjr commented on CONTRIBUTORS_QUICK_START.rst
> +       sqlite libsqlite3-dev default-libmysqlclient-dev libmysqlclient-dev postgresql
Actually, since we'll be installing Python with pyenv anyway, I don't think we even need the `python3-dev` package at all. Both `build-essential` and `libsqlite3-dev` can be removed as well since they are already installed in the command above.

2021-10-18 12:13 UTC, ephraimbuddy requested changes
Other places you should update too are:

- https://github.com/apache/airflow/blob/1571f80546853688778c2a3ec5194e5c8be0edbd/breeze#L276-L277
- https://github.com/apache/airflow/blob/c747bce135c5bcbc92645c226cb90fd99dc62be5/INSTALL#L10-L11

2021-10-18 19:20 UTC, potiuk commented on CONTRIBUTORS_QUICK_START.rst
> +       sqlite libsqlite3-dev default-libmysqlclient-dev libmysqlclient-dev postgresql
Yeah I wonder where it came from :)

2021-10-18 22:04 UTC, OyinOlamide commented
> > @potiuk @ephraimbuddy @uranusjr I have updated and made the pull requests. Please let me know if there's another way I can help or anything else I can do to get the PR merged. Thank you!
> 
> Follow the links I posted in my comment above. Locate it and change it too

I have done that @ephraimbuddy 
Those links also have pull requests now.
You can check them out below.
https://github.com/apache/airflow/pull/19056
https://github.com/apache/airflow/pull/19055

2021-10-19 22:37 UTC, OyinOlamide commented
I think I have done that now @potiuk and @ephraimbuddy . Please take a look and let me know if there is any way I can make this better. Thank you! :)

2021-10-19 23:52 UTC, potiuk approved these changes

2021-10-20 10:39 UTC, ephraimbuddy commented on INSTALL
> +                 sqlite default-libmysqlclient-dev libmysqld-dev postgresql
I _think_ we need `build-essential` and `libsqlite3-dev` here.

Apart from the contributors quick start doc. We need this here and also in breeze.
cc: @uranusjr

2021-10-20 11:16 UTC, uranusjr commented on INSTALL
> +                 sqlite default-libmysqlclient-dev libmysqld-dev postgresql
Yes we do. The quick start does not need them because they are installed by a previous command, but that's not the case here.

2021-10-20 11:22 UTC, ephraimbuddy commented on INSTALL
> +                 sqlite default-libmysqlclient-dev libmysqld-dev postgresql
@OyinOlamide

2021-10-20 11:24 UTC, ephraimbuddy commented on INSTALL
> +                 sqlite default-libmysqlclient-dev libmysqld-dev postgresql
Also add `python3-dev` as well

2021-10-20 11:38 UTC, OyinAwosan commented on INSTALL
> +                 sqlite default-libmysqlclient-dev libmysqld-dev postgresql
@ephraimbuddy I did not remove `libsqlite3-dev`
Do you want me to add it somewhere in the code?

2021-10-20 11:48 UTC, ephraimbuddy commented on INSTALL
> +                 sqlite default-libmysqlclient-dev libmysqld-dev postgresql
Yes. add `build-essential python3-dev libsqlite3-dev` to the code you changed in airflow/INSTALL  and airflow/breeze

2021-10-20 11:48 UTC, uranusjr commented on INSTALL
> +                 sqlite default-libmysqlclient-dev libmysqld-dev postgresql
You should add it here and the line you changed in `BREEZE`.

2021-10-20 13:27 UTC, OyinOlamide commented
Hello @ephraimbuddy @uranusjr @potiuk I think I have carried out these changes now. Please take a look at my last commit and let me know.
Thank you so much for your time and patience. :)

2021-10-20 13:27 UTC, ephraimbuddy approved these changes

2021-10-20 14:01 UTC, ephraimbuddy commented on INSTALL
> +                 sqlite default-libmysqlclient-dev libmysqld-dev postgresql
Just noticed you still have `libmysqlclient-dev` instead of libmysqlclient-dev

2021-10-20 14:16 UTC, OyinAwosan commented on INSTALL
> +                 sqlite default-libmysqlclient-dev libmysqld-dev postgresql
@ephraimbuddy Sorry, but this change is not clear. Both strips of code you mentioned in your last comment seem to be the same or am I missing something?

2021-10-20 14:29 UTC, ephraimbuddy commented on INSTALL
> +                 sqlite default-libmysqlclient-dev libmysqld-dev postgresql
Sorry, I meant `libmysqld-dev` instead of `libmysqlclient-dev`.

The change should be:
```
sudo apt install build-essential python3-dev libsqlite3-dev openssl \
                 sqlite default-libmysqlclient-dev libmysqlclient-dev postgresql
```

2021-10-20 14:46 UTC, OyinAwosan commented on INSTALL
> +                 sqlite default-libmysqlclient-dev libmysqld-dev postgresql
@ephraimbuddy Alright, I was not aware of this before. Should this particular change take effect in all three files or just .breeze and INSTALL?

2021-10-20 15:04 UTC, ephraimbuddy commented on INSTALL
> +                 sqlite default-libmysqlclient-dev libmysqld-dev postgresql
Just breeze and install

2021-10-20 16:34 UTC, potiuk approved these changes

2021-10-20 16:51 UTC, OyinAwosan commented on INSTALL
> +                 sqlite default-libmysqlclient-dev libmysqld-dev postgresql
I've done that now @ephraimbuddy 
Please check it out and let me know. Thank you for your patience and help.

2021-10-20 18:53 UTC, merged