use DefaultAzureCredential if login not provided for Data Factory
apache/airflow pull request #19079
Opened 2021-10-19 15:46 UTC by sdebruyn

closes: #19077 

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

2021-10-20 08:05 UTC, eladkal requested changes

2021-10-20 08:05 UTC, eladkal commented on airflow/providers/microsoft/azure/hooks/data_factory.py
> +
```suggestion

```

2021-10-20 08:05 UTC, eladkal commented on airflow/providers/microsoft/azure/hooks/data_factory.py
> +
to fix static tests

2021-10-20 14:42 UTC, josh-fell commented on docs/apache-airflow-providers-microsoft-azure/connections/adf.rst
> +1. Fallback on `DefaultAzureCredential
This item should be number 2 in the list.

2021-10-20 15:12 UTC, sdebruyn commented
Thank you for assisting me with this PR! It's my first Airflow PR and I have a hard time setting the repo up locally. If you wouldn't mind, feel free to reach out to me on Slack to help me to set it up. It will save me time with future contributions.

2021-10-21 12:10 UTC, eladkal requested changes

2021-10-21 12:10 UTC, eladkal commented on airflow/providers/microsoft/azure/hooks/data_factory.py
> +            credential=credential,
Can we test this?
https://github.com/apache/airflow/blob/main/tests/providers/microsoft/azure/hooks/test_azure_data_factory.py

2021-10-21 13:46 UTC, sdebruyn commented on airflow/providers/microsoft/azure/hooks/data_factory.py
> +            credential=credential,
How do I run these?

2021-10-21 18:14 UTC, josh-fell commented on airflow/providers/microsoft/azure/hooks/data_factory.py
> +            credential=credential,
Check out [this doc](https://github.com/apache/airflow/blob/main/TESTING.rst#airflow-unit-tests). It details how to run unit tests locally within a couple IDEs or Breeze/virtualenv.

2021-11-06 21:21 UTC, sdebruyn commented on airflow/providers/microsoft/azure/hooks/data_factory.py
> +            credential=credential,
@eladkal @josh-fell test added :) thank you for your patience with my first PR!

2021-11-07 13:03 UTC, potiuk approved these changes

2021-11-07 13:04 UTC, potiuk commented
@eladkal WDYT?

2021-11-07 16:30 UTC, eladkal approved these changes

2021-11-07 16:42 UTC, merged