Increment Stats counter for task instance SLA misses
apache/airflow pull request #19102
Opened 2021-10-20 09:37 UTC by doddsiedodds

Increment a new named stats counter for task instance SLA misses, following
the existing naming convention of other task instance Stats.

2021-10-25 07:52 UTC, uranusjr commented on tests/dag_processing/test_processor.py
> -        sla_callback.assert_not_called()
Why is this removed?

2021-10-25 07:55 UTC, doddsiedodds commented on tests/dag_processing/test_processor.py
> -        sla_callback.assert_not_called()
It shouldn't have been, I originally started by adding the stats increment counter later in the sla management code and so I had switched this for an `assert_called_once`, Must have just not reverted this line.  Will reinstate.

2021-10-25 07:57 UTC, doddsiedodds commented on tests/dag_processing/test_processor.py
> -        sla_callback.assert_not_called()
Fixed, thanks

2021-10-25 08:10 UTC, uranusjr requested changes

2021-10-25 08:10 UTC, uranusjr commented on tests/dag_processing/test_processor.py
> +        self.clean_db()
This is automatically called after every test is run, so you don't need to call it in your test.

2021-10-25 08:10 UTC, uranusjr commented on tests/dag_processing/test_processor.py
> +            )
```suggestion
            dag, task = create_dummy_dag(
                dag_id='test_sla_miss_stats',
                task_id='dummy',
                schedule_interval="0 0 * * *",
                catchup=True,
                default_args={
                    'start_date': test_start_date,
                    'sla': datetime.timedelta(hours=1),
                },
                session=session,
            )
```

Since you created a session, it's best to reuse it across all calls. (Please also do this for other functions where applicable.)

2021-10-25 08:15 UTC, doddsiedodds commented on tests/dag_processing/test_processor.py
> +        self.clean_db()
Removed

2021-10-25 08:17 UTC, doddsiedodds commented on tests/dag_processing/test_processor.py
> +            )
Done

2021-10-25 08:18 UTC, uranusjr approved these changes

2021-11-03 14:54 UTC, doddsiedodds commented
Please can this be merged? I don't think there's anything left from my side

2021-11-08 17:56 UTC, potiuk commented
You need to at least rebase to see if the tests are not caused by your change

2021-11-08 17:58 UTC, doddsiedodds commented
Ok, I rebased and the test ran to success 2 weeks ago but my comment wasn't acknowledged... Will rebase again

2021-11-08 18:03 UTC, potiuk commented
> Ok, I rebased and the test ran to success 2 weeks ago but my comment wasn't acknowledged... Will rebase again

Yeah. It happens sometimes, I often rebase my PR a number of times. We have pretty active project. Most of the people work for free here, and they are often busy, so some iterations and delays in reviews are expected at times.

2021-11-08 18:11 UTC, doddsiedodds commented
No worries, just wasn't clear to me if there was somewhere I should be chasing up. Have rebased now

2021-11-15 09:25 UTC, uranusjr approved these changes
We need another maintainer to take a look to get this merged.

2021-11-17 18:52 UTC, potiuk requested changes
Looks good but needs documentation update here: https://airflow.apache.org/docs/apache-airflow/stable/logging-monitoring/metrics.html

2021-12-13 15:59 UTC, eladkal commented
@doddsiedodds can you please address the comments?

2022-02-02 00:08 UTC, closed without merging