fix SagemakerProcessingOperator ThrottlingException
apache/airflow pull request #19195
Opened 2021-10-25 07:41 UTC by ChanglinZhou

Do not iterate all the processing jobs, because it's problematic.

closes: #16763

related  #19066

2021-10-25 07:44 UTC, uranusjr commented on airflow/providers/amazon/aws/hooks/sagemaker.py
> +        """
```suggestion
        """Query processing job existence."""
```

No need to explain something wrong if the solution is obviously correct.

2021-10-25 07:45 UTC, uranusjr commented on airflow/providers/amazon/aws/hooks/sagemaker.py
> +        except ClientError as e:
Does `ClientError` guarantee the job does not exist, or do we need to check the status code or something? 404?

2021-10-26 04:01 UTC, ChanglinZhou commented on airflow/providers/amazon/aws/hooks/sagemaker.py
> +        except ClientError as e:
I prefer fail fast. According to the test, ClientError.response['Error']['Code'] == 'ValidationException', when the job doesn't exist.

2021-10-26 04:05 UTC, uranusjr commented on airflow/providers/amazon/aws/hooks/sagemaker.py
> +            raise e
```suggestion
            raise
```

This preserves the original traceback, which is likely more useful for the user.

2021-10-26 04:21 UTC, ChanglinZhou commented on airflow/providers/amazon/aws/hooks/sagemaker.py
> +            raise e
updated

2021-10-26 04:22 UTC, uranusjr approved these changes
Assuming tests pass

2021-10-26 19:15 UTC, o-nikolas commented on airflow/providers/amazon/aws/hooks/sagemaker.py
> +        except ClientError as e:
While this API specifically throws only [ResourceNotFound](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_DescribeProcessingJob.html#API_DescribeProcessingJob_Errors) there are many errors that are common to all sagemaker APIs that could technically be thrown (see the list [here](https://docs.aws.amazon.com/sagemaker/latest/APIReference/CommonErrors.html)). For completeness I think it's worth checking directly for ResourceNotFound. It is also more future proof that way. Just my 2c

2021-10-28 08:17 UTC, ChanglinZhou commented on airflow/providers/amazon/aws/hooks/sagemaker.py
> +        except ClientError as e:
I use boto3 client to verify the api behavior, it returns validation exception rather than ResourceNotFound

2021-10-28 14:05 UTC, eladkal requested changes

2021-10-28 14:05 UTC, eladkal commented on airflow/providers/amazon/aws/hooks/sagemaker.py
> +        "Query processing job by name"
```suggestion
        """Query processing job by name"""
```
To fix static checks

2021-10-28 14:59 UTC, ChanglinZhou commented on airflow/providers/amazon/aws/hooks/sagemaker.py
> +        "Query processing job by name"
Fixed.

2021-10-28 18:13 UTC, o-nikolas approved these changes

2021-10-29 03:20 UTC, eladkal approved these changes

2021-10-29 03:23 UTC, eladkal commented on airflow/providers/amazon/aws/hooks/sagemaker.py
> +    def find_processing_job_by_name(self, processing_job_name: str) -> bool:
@ChanglinZhou is it possible to also test this function ?
https://github.com/apache/airflow/blob/main/tests/providers/amazon/aws/hooks/test_sagemaker.py

2021-10-29 05:37 UTC, ChanglinZhou commented on airflow/providers/amazon/aws/hooks/sagemaker.py
> +    def find_processing_job_by_name(self, processing_job_name: str) -> bool:
Added, and also, ResourceNotFound exception is handled.

2021-10-31 03:20 UTC, ChanglinZhou commented
I have tried the GitHub.com/apache/airflow main branch, the quarantined test fails.

2021-11-04 03:36 UTC, eladkal approved these changes

2021-11-04 06:49 UTC, merged