Fix log timezone in task log view (#19342)
apache/airflow pull request #19401
Opened 2021-11-04 05:43 UTC by calfzhou

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

2021-11-04 14:33 UTC, bbovenzi requested changes
@calfzou Looking good, but please add a description to the PR.

2021-11-05 01:49 UTC, calfzhou commented
> @calfzou Looking good, but please add a description to the PR.

@bbovenzi  description added 😄

2021-11-05 05:29 UTC, bbovenzi commented
We aren't importing `moment` or `Airflow` directly. You need to add them to the global declaration near the top of the file like so: `/* global document, window, $, moment, Airflow */`

2021-11-05 06:23 UTC, calfzhou commented
> We aren't importing `moment` or `Airflow` directly. You need to add them to the global declaration near the top of the file like so: `/* global document, window, $, moment, Airflow */`

fixed ~~

2021-11-05 16:04 UTC, bbovenzi approved these changes
Nice work!

2021-11-05 16:04 UTC, merged

2022-01-03 06:44 UTC, big1990id approved these changes

2022-05-19 03:24 UTC, freshlu11 commented
This bug occurs in 2.3.0 again [https://github.com/apache/airflow/blob/2.3.0/airflow/www/static/js/ti_log.js](url)

2022-05-19 04:00 UTC, calfzhou commented
> This bug occurs in 2.3.0 again [https://github.com/apache/airflow/blob/2.3.0/airflow/www/static/js/ti_log.js](url)

might caused by recent change: #23075

2022-05-19 07:15 UTC, potiuk commented
Can you please open a new issue for that ? Thanks in advance

2022-05-19 08:46 UTC, freshlu11 commented
ok, wait a moment