[AIRFLOW-729] Add Google Cloud Dataproc cluster creation operator
apache/airflow pull request #1971
Opened 2017-01-04 13:28 UTC by bodschut

Add an operator to create a Google Cloud Dataproc cluster with a given name in a given google cloud project.

The operator checks if there is already a cluster running with the provided name in the provided project.
If so, the operator finishes successfully. Otherwise, the operator issues a rest API call to initiate
the cluster creation and waits until the creation is successful before exiting. Most of the possible cluster customisation parameters available in dataproc are made available when constructing the operator.

Dear Airflow Maintainers,

Please accept this PR that addresses the following issues:
- https://issues.apache.org/jira/browse/AIRFLOW-729

Testing Done:
- Unittests not possible due to private google cloud connections. Extensive production testing has been performed.

2017-01-07 16:05 UTC, bolkedebruin requested changes
Some minor nits. Please check if you adhere to the commit guidelines (max columns)

2017-01-07 16:05 UTC, bolkedebruin commented on airflow/contrib/operators/dataproc_operator.py
> +                 zone='europe-west1-d',
Is this smart? Should this not be a required setting instead of having a default?

2017-01-07 16:05 UTC, bolkedebruin commented on airflow/contrib/operators/dataproc_operator.py
> +                logging.log(logging.INFO, "No state for cluster '%s'", self.cluster_name)
we use logging.info across airflow. Besides can this als be "debug"?

2017-01-07 16:05 UTC, bolkedebruin commented on airflow/contrib/operators/dataproc_operator.py
> +                logging.log(logging.INFO,
Idem as above

2017-01-07 16:05 UTC, bolkedebruin commented on airflow/contrib/operators/dataproc_operator.py
> +                    logging.log(logging.INFO,
Idem as above

2017-01-07 16:05 UTC, bolkedebruin commented on airflow/contrib/operators/dataproc_operator.py
> +            logging.log(logging.INFO,
Idem as above, debug seems more appropiate.

2017-01-07 16:05 UTC, bolkedebruin commented on airflow/contrib/operators/dataproc_operator.py
> +                logging.log(logging.INFO,
Idem as above

2017-01-07 16:05 UTC, bolkedebruin commented
cc @alexvanboxel

2017-01-07 19:34 UTC, alexvanboxel commented on airflow/contrib/operators/dataproc_operator.py
> +                 zone='europe-west1-d',
Agreed, this should not be a default

2017-01-08 09:22 UTC, alexvanboxel commented on airflow/contrib/operators/dataproc_operator.py
> +                logging.log(logging.INFO, "No state for cluster '%s'", self.cluster_name)
Hey @bolkedebruin , I actually don't agree here. Due to how logging is wired log messages under INFO will never be shown or you need to rebuild Airflow (I'm looking into it though...).

So INFO is very appropriate for Operators and Hooks. Results come in a separate logfile anyway, and you want to see how the progress of a Task goes.

2017-01-09 07:52 UTC, bodschut commented
Hi @bolkedebruin 

I changed the zone parameter to be required and adopted the logging.info method. However, I also feel that the INFO level is more appropriate to follow the task progress.

Another question: I see that that you adhere to the 90 characters limit for line lengths (original PEP-8 recommendation). However, I believe that sometimes this is bad for code readability... A lot of modern open source projects have already extended the limit to 120 characters (which is also the default in IDE's like pycharm). What do you think of this?

Thanks,
Bob

2017-01-09 09:56 UTC, alexvanboxel commented
@bolkedebruin I think it's good, if we get +1 for @criccomini I'll merge it in before tonight. I want to build a new alpha to run on our environment and would like to have this one and the other included.

2017-01-09 20:49 UTC, closed without merging