Showing approximate time remaining for next dag_run in Airflow UI
apache/airflow pull request #20273
Opened 2021-12-13 22:46 UTC by pateash

closes: #19098

### Description

It will be really helpful if we can add a dynamic message/tooltip which shows time remaining for next dagrun in UI.

### Use case/motivation

Although we have next_run available in UI, user has to look into schedule and find the timedifference between schedule and current time, It will be really convenient to have that information available on fingertips.

2021-12-13 22:49 UTC, pateash commented
![image](https://user-images.githubusercontent.com/16856802/145901296-ac6b45f6-1039-40c2-a44d-d5d1920ea3f5.png)

![image](https://user-images.githubusercontent.com/16856802/145901394-21d56863-d599-499e-b05e-dd44362cf3a0.png)

![image](https://user-images.githubusercontent.com/16856802/145901495-6923cc45-8563-4048-a358-b34d394f6a6b.png)

2021-12-13 23:05 UTC, pateash commented
![image](https://user-images.githubusercontent.com/16856802/145903054-dad6faf8-c29d-4938-8901-070ef8e93ec5.png)

![image](https://user-images.githubusercontent.com/16856802/145903095-a38e0dcc-7de9-4bff-8635-8791daa31e14.png)

2021-12-14 15:35 UTC, bbovenzi requested changes
Looks great. I just think we can improve the copy. Maybe `Next run in`? and then it doesn't need to be bold

2021-12-14 22:36 UTC, pateash commented
`

> Looks great. I just think we can improve the copy. Maybe `Next run in`? and then it doesn't need to be bold

@bbovenzi Sure, Is this looks good?
![image](https://user-images.githubusercontent.com/16856802/146090349-68ddc015-bca6-48d6-a0f5-e2f5d3d77e3a.png)

2021-12-16 17:14 UTC, bbovenzi commented on airflow/www/static/js/dag.js
> +      newTitle += `Next Run: ${approxTimeFromNow(nextRun.createAfter)}<br><br>`;
```suggestion
      newTitle += `Next Run ${approxTimeFromNow(nextRun.createAfter)}<br><br>`;
```
We can drop `:`

2021-12-16 17:15 UTC, bbovenzi approved these changes
nice work!

2021-12-16 17:17 UTC, merged