Bugfix for cleanup-pods command
apache/airflow pull request #20417
Opened 2021-12-20 06:33 UTC by humit0

When getting cleanup pods list, it requires to have `execution_date` label.
But from the [code](https://github.com/apache/airflow/blob/aa27d9f92ef261ce2bf2b0e1b3699c1ffd23307f/airflow/executors/kubernetes_executor.py#L319), it does not set `execution_date` label when trigger by scheduler.

So I remove `execution_date` label when get pod list.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

2021-12-20 13:20 UTC, kaxil requested changes
We can't just remove `execution_date` date alone as it will otherwise remove tasks from other execution_date or run_ids too.

We add a `run_id` or an `execution_date` to labels, see:

https://github.com/apache/airflow/blob/aa27d9f92ef261ce2bf2b0e1b3699c1ffd23307f/airflow/kubernetes/pod_generator.py#L369-L374

2021-12-21 01:15 UTC, humit0 commented
@kaxil From original code, it removes all success, evicted, and (failed & restartPolicy: Never) pods, not filter pod by `execution_date` or `run_id`.
So I think `execution_date` part is unnecessary.

2021-12-21 15:00 UTC, kaxil commented
> @kaxil From original code, it removes all success, evicted, and (failed & restartPolicy: Never) pods, not filter pod by `execution_date` or `run_id`. So I think `execution_date` part is unnecessary.

I will take another look later today or tomorrow

2021-12-27 21:10 UTC, kaxil approved these changes

2021-12-27 21:10 UTC, merged