Add non-ascii character support in xcom table
apache/airflow pull request #21460
Opened 2022-02-09 12:42 UTC by chenglongyan

closes: #14413

2022-02-09 13:38 UTC, ashb requested changes

2022-02-09 13:38 UTC, ashb commented on tests/models/test_xcom.py
> +        assert val == b'["\xe5\x89\x8d\xe6\x9c\x89\xe5\xa4\xa7\xe6\xa2\x85\xe6\x9e\x97"]'
This does not look like the correct JSONification of the characters.

The default `json.dumps)` uses `\uDDDD` sequences and roundtrips fine:

```
In [8]: json.dumps(x).encode("UTF-8")
Out[8]: b'["\\u524d\\u6709\\u5927\\u6885\\u6797"]'

In [9]: json.loads(_8)
Out[9]: ['前有大梅林']
```

2022-02-09 16:02 UTC, potiuk commented on tests/models/test_xcom.py
> +        assert val == b'["\xe5\x89\x8d\xe6\x9c\x89\xe5\xa4\xa7\xe6\xa2\x85\xe6\x9e\x97"]'
Yeah. Ensure_ascii does not work as you think it does https://bugs.python.org/issue13769

2022-02-11 02:51 UTC, chenglongyan commented on tests/models/test_xcom.py
> +        assert val == b'["\xe5\x89\x8d\xe6\x9c\x89\xe5\xa4\xa7\xe6\xa2\x85\xe6\x9e\x97"]'
@ashb I think this is correct json encoding, just not escaped to ascii encoding
[https://docs.python.org/3.6/library/json.html#character-encodings](https://docs.python.org/3.6/library/json.html#character-encodings)

except mentioned in #14413, sets ensure_ascii=False can reduce size of xcom.value:
    
    In [2]: len(json.dumps(["中文"]).encode("utf-8"))
    Out[2]: 16
  
    In [3]: len(json.dumps(["中文"], ensure_ascii=False).encode("utf-8"))
    Out[3]: 10

2022-02-14 16:01 UTC, ashb commented on tests/models/test_xcom.py
> +        assert val == b'["\xe5\x89\x8d\xe6\x9c\x89\xe5\xa4\xa7\xe6\xa2\x85\xe6\x9e\x97"]'
https://en.wikipedia.org/wiki/JSON#Character_encoding `\x` is not valid JSON.

2022-02-15 03:51 UTC, chenglongyan commented on tests/models/test_xcom.py
> +        assert val == b'["\xe5\x89\x8d\xe6\x9c\x89\xe5\xa4\xa7\xe6\xa2\x85\xe6\x9e\x97"]'
yes, it's hex bytes prefix of python...
https://docs.python.org/3/reference/lexical_analysis.html#:~:text=\xhh

2022-03-01 02:50 UTC, uranusjr commented
I’m not sure this fixes anything. By default, `json.dumps()` uses `ensure_ascii=True` and produces Unicode codepoint escape sequences, which should be able to be saved in any database configured in any encoding. Changing to `ensure_ascii=False` just makes the JSON string being serialised into a different value that still has the same characteristics.

I suspect this is not the correct fix, and the right fix to the original issue should be to remove `encode("UTF-8")`.

2022-03-01 13:24 UTC, potiuk commented
> I’m not sure this fixes anything. By default, `json.dumps()` uses `ensure_ascii=True` and produces Unicode codepoint escape sequences, which should be able to be saved in any database configured in any encoding. Changing to `ensure_ascii=False` just makes the JSON string being serialised into a different value that still has the same characteristics.
> 
> I suspect this is not the correct fix, and the right fix to the original issue should be to remove `encode("UTF-8")`.

Agree. Closing it.

2022-03-01 13:24 UTC, closed without merging