Fix annotations not getting added to cleanup pods
apache/airflow pull request #21484
Opened 2022-02-10 04:42 UTC by jonstacks

closes: #21469 

This PR propagates the `airflowPodAnnotations` that the documentation says is applied to all airflow pods to the pods launched by the `cleanup` cronojob. It also allows for setting `podAnnotations` specifically for the cleanup pods.

2022-02-10 14:14 UTC, thetaiter approved these changes

2022-02-11 04:40 UTC, jedcunningham requested changes
@jonstacks, overall looks good. Can you instead add test coverage in these 2 places:

https://github.com/apache/airflow/blob/5dc6338346deca8e5a9a47df2da19f38eeac0ce8/chart/tests/test_annotations.py#L284
https://github.com/apache/airflow/blob/5dc6338346deca8e5a9a47df2da19f38eeac0ce8/chart/tests/test_airflow_common.py#L69

Sorry, yes, it is a little messy - feel free to open a follow up PR doing some cleanup if you want.

2022-02-11 17:58 UTC, jonstacks commented
@jedcunningham, thanks for the review and feedback. Can you tell me if this is more in line with what you are thinking?

2022-02-11 23:10 UTC, jedcunningham approved these changes

2022-02-11 23:12 UTC, potiuk approved these changes

2022-02-11 23:12 UTC, merged

2022-02-11 23:14 UTC, jedcunningham commented
Thanks @jonstacks 🎉