Show import error for 'airflow dags list' CLI command
apache/airflow pull request #21991
Opened 2022-03-04 12:08 UTC by ephraimbuddy

When there's an import error in a dag, the dag doesn't show up in the list of dags
and there's no indication that there's an import error.
This PR fixes that

2022-03-04 16:29 UTC, jedcunningham requested changes

2022-03-04 16:29 UTC, jedcunningham commented on airflow/cli/commands/dag_command.py
> +        rich_print("[red][bold]Error:[bold] The following dags failed to load [red]")
```suggestion
        rich_print("[red][bold]Error:[/bold] The following dags failed to load")
```

2022-03-04 16:29 UTC, jedcunningham commented on airflow/cli/commands/dag_command.py
> +            rich_print(f"[red][bold]Broken DAG: {filename}: {stacktrace}[bold][red]")
```suggestion
            rich_print(f"[red][bold]Broken DAG {filename}:[/bold] {stacktrace}")
```

Not sure we even need to bold the filename?

2022-03-04 17:12 UTC, mik-laj commented
Won't that cause problem for scripts that process the output of this command? I think we should display import errors on stderr.

2022-03-04 17:14 UTC, mik-laj commented
Related PR: https://github.com/apache/airflow/pull/15087

2022-03-07 20:37 UTC, ephraimbuddy commented
> Related PR: #15087

What's your opinion about having `--show-import-error` option? I think printing the error in stderr without any option is OK.
Happy to hear what you think then I would work on it and add tests

2022-03-08 00:20 UTC, mik-laj commented
@ephraimbuddy, For me, displaying an error on stderr without any options is also OK. In the above-mentioned PR, I proposed to add a separate command as this would allow us to write scripts that process these import errors, but we can do it as a separate contribution.

2022-03-08 14:12 UTC, ephraimbuddy commented
@mik-laj I have created a separate command for import errors(PR: https://github.com/apache/airflow/pull/22084). Would wait for that to be merged and update this PR to just say that we have import errors and ask the users to run `airflow dags list-import-errors` to see the errors. WDYT?

2022-03-08 19:27 UTC, ephraimbuddy commented on tests/cli/commands/test_dag_command.py
> +            out = temp_stdout.getvalue()
```suggestion
        with contextlib.redirect_stderr(io.StringIO()) as temp_stderr:
            dag_command.dag_list_dags(args)
            out = temp_stderr.getvalue()
```

2022-03-08 19:42 UTC, mik-laj approved these changes

2022-03-08 19:57 UTC, jedcunningham approved these changes

2022-03-08 19:57 UTC, jedcunningham commented on airflow/cli/commands/dag_command.py
> +            "For details, run airflow dags list-import-errors",
```suggestion
            "For details, run `airflow dags list-import-errors`",
```
nit

2022-03-08 20:07 UTC, potiuk approved these changes

2022-03-08 23:43 UTC, merged