connection add CLI - validate the input params
apache/airflow pull request #22688
Opened 2022-04-01 13:04 UTC by Bowrna

closes: #22392
relates: #22392 

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

2022-04-04 10:45 UTC, potiuk reviewed
We will need two tests:

* (parameterized) test covering valid and invalid connection types for _valid_conn_type
* CLI test checking the warning messages (you will find some CLI tests in the code - we have quite good coverage

2022-04-04 11:42 UTC, Bowrna commented
> We will need two tests:
> 
> * (parameterized) test covering valid and invalid connection types for _valid_conn_type
> * CLI test checking the warning messages (you will find some CLI tests in the code - we have quite good coverage

@potiuk i will update this PR with tests

2022-04-06 06:15 UTC, uranusjr requested changes, later dismissed

2022-04-06 06:15 UTC, uranusjr commented on airflow/cli/commands/connection_command.py
> +def _valid_conn_type(conn_type: str) -> Tuple[bool, List[str]]:
Eagerly accessing valid conn types looks wrong to me (it’s slow). The `_get_connection_types()` function should live outside of this, and only called when `conn_type` is not valid.

This function should simply return a bool to indicate whether the conn type is valid.

2022-04-06 07:54 UTC, Bowrna commented
@uranusjr I have made the changes requested. Even if i move the `_get_connection_types()` function outside, i have to invoke that function to get the list of valid connection type. I could determine if the `conn-type` is valid or not after invoking  `_get_connection_types()` function. Could you explain to me if I am missing to understand any point you mentioned?

2022-04-06 08:00 UTC, uranusjr commented
Add a `@cache` decorator on the function

2022-04-06 08:00 UTC, uranusjr commented on airflow/cli/commands/connection_command.py
> +            )
Not sure `warnings.warn` is the right thing to do (not faimilar with how commands log things). Maybe `log.warning` is better?

2022-04-06 08:06 UTC, Bowrna commented
> Add a `@cache` decorator on the function

Yes that makes sense. I will add it @uranusjr

2022-04-06 08:44 UTC, Bowrna commented
@uranusjr Regarding warnings.warn I got the warning message when i tried to execute the command with invalid `conn-type`. Do I still have to use `log.warning`?

2022-04-06 18:00 UTC, uranusjr commented
I’m not sure, to be honest, maybe another maintainer can offer better advice.

2022-04-07 06:42 UTC, uranusjr commented on airflow/cli/commands/connection_command.py
> +@lru_cache(maxsize=None)
Use `@cache` from `airflow.compat` instead

2022-04-07 06:42 UTC, uranusjr commented on airflow/cli/commands/connection_command.py
> +    return is_valid
```suggestion
def _valid_conn_type(conn_type: str) -> bool:
    return conn_type in _get_connection_types()
```

(Do we still need this function now it’s simplied to just one line?)

2022-04-09 04:18 UTC, Bowrna commented
Do i have to make any other improvements in this code to get it merged? :)

2022-04-09 10:22 UTC, uranusjr approved these changes

2022-04-13 19:45 UTC, potiuk approved these changes

2022-04-13 19:45 UTC, merged