Fix Task Duration Calculation & Display
apache/airflow pull request #23173
Opened 2022-04-22 17:02 UTC by aschoe21

closes: #23169
Prevent moment from truncating the result of diff to zero decimal places

As moment.diff has the default behavior of truncating the decimal places of diff results (i.e. rounding down to the nearest integer), when the duration of a task run is less than a full second moment rounds the duration down to 0. This behavior results in the task duration rendering as empty/null rather than as the correct task run duration.

Moment's diff function accepts a third, optional boolean argument that dictates its result truncation behavior. By default this value is false which leads to the unwanted behavior described above. Setting this argument to true when calling diff will allow the result to exist as a decimal, fixing the situation where task run duration is rounded down to 0 seconds.

2022-04-22 17:50 UTC, frankcash commented
hi @aschoe21  could you include a screenshot of the functionality working as well?

2022-04-22 18:58 UTC, aschoe21 commented
> hi @aschoe21 could you include a screenshot of the functionality working as well?

Sure, here's a screenshot of the tooltip showing a task completing in 0.105Sec

![image](https://user-images.githubusercontent.com/37813918/164777383-c810d2d5-292b-487f-8bed-37525138852a.png)

2022-04-25 04:33 UTC, uranusjr commented
Would the decimal places always show, even when the duration is long? Ideally I’d only want them when the duration is <1 and not if it’s e.g. 105.378 seconds.

2022-04-25 13:01 UTC, bbovenzi commented
> Would the decimal places always show, even when the duration is long? Ideally I’d only want them when the duration is <1 and not if it’s e.g. 105.378 seconds.

Yes, and this also breaks down when duration is better shown as minutes, hours or even days. Overall, how we display durations in the UI is inconsistent and we should consolidate down to one format. I was playing around with that here: https://github.com/apache/airflow/pull/22996/files

What do you think of choosing the most important unit and then limiting to just 2 decimal places:
<img width="78" alt="Screen Shot 2022-04-25 at 8 59 59 AM" src="https://user-images.githubusercontent.com/4600967/165094270-c0935f9c-9913-4f36-a4d0-cb052e903f1b.png">
<img width="72" alt="Screen Shot 2022-04-25 at 8 59 55 AM" src="https://user-images.githubusercontent.com/4600967/165094272-83383e90-1c60-421b-960f-27d8afae05d3.png">

2022-04-25 16:04 UTC, ashb commented
I think if it's in to minutes or hours then `1h58m` is better `1.98h`

2022-05-17 14:14 UTC, bbovenzi requested changes
Let's update `convertSecondsToHumanReadable` in `main.js`:

- Only show decimal if seconds is less than 1
- If decimal is also 0, then lets return `<1ms`
- Switch `Hours` -> `h`, `Min` -> `m`, `Sec` -> `s`

I think with those changes this should be good to merge. Then we can update the rest of the UI and webserver to make sure duration is always displayed consistently.

2022-05-27 04:48 UTC, eladkal commented
@aschoe21 are you still working on this PR?

2022-07-17 00:12 UTC, closed without merging