[AIRFLOW-1236]: SlackPostOperator using Slack Incoming WebHook
apache/airflow pull request #2319
Opened 2017-05-22 08:13 UTC by forsberg

Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [ ] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-1236

### Description
- [ ] Improved operator for posting messages to Slack. Does not use deprecated slack token to authenticate. Uses Airflow Connection to keep credentials. 

### Tests
- [ ] Did not add any tests. Code is trivial, but you will probably tell me to add tests anyway? :-)

### Commits
- [ ] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

2017-05-22 09:00 UTC, skudriashev commented
@forsberg please remove `:` after [] in commit message to be consistent with all commits.

2017-05-22 09:12 UTC, forsberg commented
@skudriashev OK, Done. Also squashed into one commit.

2017-05-22 09:45 UTC, bolkedebruin requested changes
And yes please add tests :-), coverage should not decrease.

2017-05-22 09:45 UTC, bolkedebruin commented on airflow/operators/slack_operator.py
> +class SlackWebHookHook(BaseHook):
Please put this in its own hook file

2017-05-22 09:45 UTC, bolkedebruin commented on airflow/operators/slack_operator.py
> +        self.webhook_url = self.get_connection(conn_id).extra
You might want to be user friendly here as 'extra' is normally not required so some logging in case it isn't available could help.

2017-05-22 09:45 UTC, bolkedebruin commented on airflow/operators/__init__.py
> +    'slack_operator': ['SlackAPIOperator', 'SlackAPIPostOperator', 'SlackPostOperator'],
Are the other two API/APIPost still relevant?

2017-05-22 10:03 UTC, forsberg commented on airflow/operators/__init__.py
> +    'slack_operator': ['SlackAPIOperator', 'SlackAPIPostOperator', 'SlackPostOperator'],
Don't know, that would depend on if anyone are using them. I guess the SlackAPIOperator may be used by custom operators to implement functionality different than Post. 

Perhaps marking them as deprecated? Didn't want to do that without discussion.

2017-06-07 07:13 UTC, bolkedebruin commented on airflow/operators/__init__.py
> +    'slack_operator': ['SlackAPIOperator', 'SlackAPIPostOperator', 'SlackPostOperator'],
Deprecated is fine for 1.9.0 targeting.

2017-06-07 07:24 UTC, skudriashev commented on airflow/hooks/slack_webhook_hook.py
> +            logging.error("'extra' not defined on connection '%s'. SlackWebHookHook will fail" % self.conn_id)
Use lazy formatting here.

2017-06-07 07:25 UTC, skudriashev commented on airflow/operators/slack_operator.py
> +
This is redundant empty line according to pep8 (need to have 2 empty line before class declaration).

2017-06-07 07:25 UTC, skudriashev commented on airflow/operators/slack_operator.py
> +                      'https://www.youtube.com/watch?v=qGeZd6SovFI',
Need to have a whitespace before the url.

2017-06-07 07:27 UTC, skudriashev commented on tests/hooks/test_slack_webhook_hook.py
> +
Need to have 1 empty line at the end of the file (pep8).

2017-06-07 07:28 UTC, skudriashev commented
@forsberg, please keep your code by 80 symbols in line as much as possible.

2018-11-19 19:09 UTC, SamWildmo commented
@forsberg are you still working on this PR?

2018-12-11 19:18 UTC, forsberg commented
@SamWildmo Well. I have since changed job, so I'm not working neither with Airflow (although that might change) nor Slack anymore. But I guess I could try to find a few spare moments to finish this one off anyway.

2018-12-11 20:06 UTC, forsberg commented
However, I think it has been superseded by https://github.com/apache/incubator-airflow/pull/3129 which is already merged.

2018-12-11 20:06 UTC, closed without merging