[AIRFLOW-393] Add callback for file downloads
apache/airflow pull request #2372
Opened 2017-06-16 23:01 UTC by akosel

Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [ ] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-393] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-393

### Description
- [ ] Here are some details about my PR, including screenshots of any UI changes:

Allows a user to pass a callback when downloading an FTP file. An obvious benefit to this is offering a way to log progress as a file downloads. This __heavily__ borrows from @jlowin's [PR].(https://github.com/apache/incubator-airflow/pull/1704/files)

### Tests
- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

I see there's another [PR](https://github.com/apache/incubator-airflow/pull/2069) that has some testing written that it would probably make sense to build off of. Would it be possible to get that PR in?

### Commits
- [ ] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

2017-09-21 09:35 UTC, skudriashev requested changes

2017-09-21 09:35 UTC, skudriashev commented on airflow/contrib/hooks/ftp_hook.py
> +        if not callback:
Any tests for callback?

2017-09-21 09:35 UTC, skudriashev commented on airflow/contrib/hooks/ftp_hook.py
> +        self.log.info('Retrieving file from FTP: {}'.format(remote_full_path))
.format removes lazy formatting for logging. I wouldn't change that.

2017-09-21 09:35 UTC, skudriashev commented on airflow/contrib/hooks/ftp_hook.py
> +
This is redundant.

2017-09-21 09:35 UTC, skudriashev commented on tests/contrib/hooks/test_ftp_hook.py
> +        self.conn_mock.get_size.return_value = '213 1942'
Shouldn't you mock `size` instead of `get_size`?

2017-09-21 09:35 UTC, skudriashev commented on tests/contrib/hooks/test_ftp_hook.py
> +        self.conn_mock.get_size.return_value = '213 1942'
According to https://docs.python.org/2/library/ftplib.html#ftplib.FTP.size `size` returns `int`, not `str`.

2018-09-27 17:19 UTC, akosel commented on airflow/contrib/hooks/ftp_hook.py
> +        if not callback:
Added

2018-09-27 17:31 UTC, akosel commented
Better late than never...I'm not sure if @skudriashev is still a maintainer of Airflow, but if not, could I get another review/stamp?

2018-09-28 12:25 UTC, ashb requested changes

2018-09-28 12:25 UTC, ashb commented on airflow/contrib/hooks/ftp_hook.py
> +        :type callback: callable
Can we have some docs on what the callback is called with (what args), when it is called, what doesn't happen normally if you use a callback (i.e. I think it won't write any files.)

Also possibly as implemeneted now it would be better to make callback at local_full_path_or_bucket to be mutually exclusive - if a callback is passed the local_* argument is ignored.

2018-09-28 16:41 UTC, akosel commented on airflow/contrib/hooks/ftp_hook.py
> +        :type callback: callable
Good idea! I also added an example section to the docstring. If that seems excessive, I can remove it. Emphasis on the need to handle writing to the file inside of the custom callback if it is used.

2018-10-12 11:30 UTC, merged

2018-10-12 11:30 UTC, Fokko commented
LGTM. Thanks @akosel