Airflow 1413 Fix FTPSensor failing on error message with unexpected text.
apache/airflow pull request #2450
Opened 2017-07-17 09:20 UTC by mdziemianko

Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below fixing the issue outlined in https://issues.apache.org/jira/browse/AIRFLOW-1413

The FTPSensor relies on an error message returned by the FTPHook. The expected message is "Can't check for file existence" and is used to check for errors in following way:
try:
    hook.get_mod_time(self.path)
except ftplib.error_perm as e:
    error = str(e).split(None, 1)
    if error[1] != "Can't check for file existence":
        raise e
However on my system (Linux/Antregos) this message text is different, leading to inevitable dag termination. Moreover the actual format of the exception on my system is different and the split returns '-' instead of the actual message.

This patch changes the operation to inspect error code rather than message text.
It also adds option to ignore certain classes of errors such as Host Unavailable that are recoverable, thus the performed action can and should be retried according to ftp spec. The default setting is to fail on all errors in order to preserve current behaviour.

Additional test cases added in contrib/sensors/test_ftp_sensor.py

2018-10-14 06:36 UTC, ron819 commented
@Fokko

2018-12-11 15:42 UTC, ashb requested changes

2018-12-11 15:42 UTC, ashb commented on airflow/contrib/sensors/ftp_sensor.py
> +            return None
Returning None here feels like a way to silently mask errors in exceptional cases - returning e again here feels safer.

2018-12-11 15:42 UTC, ashb commented on airflow/contrib/sensors/ftp_sensor.py
> +        Create a new FTP sensor
```suggestion
        Create a new FTP sensor
        
```

There needs to be a blank line between the description and the params for this to render correctly

2018-12-11 15:42 UTC, ashb commented on airflow/contrib/sensors/ftp_sensor.py
> +                logging.info('Ftp error encountered: %s', str(e))
```suggestion
                self.log.info('Ftp error encountered: %s', str(e))
```

(And remove the import of `logging` at the top)

2018-12-11 15:43 UTC, ashb commented
(Better late than never with a review right? Sorry it took sooooo long!)

2018-12-12 23:21 UTC, mdziemianko commented
> (Better late than never with a review right? Sorry it took sooooo long!)

lol:) I forgot about this PR... will do the changes. Thanks.

2018-12-13 09:59 UTC, ashb approved these changes

2018-12-13 10:01 UTC, ashb commented on tests/contrib/sensors/test_ftp_sensor.py
>  if __name__ == '__main__':
Tests are now failing the style check here with:

> ./tests/contrib/sensors/test_ftp_sensor.py:96:1: E305 expected 2 blank lines after class or function definition, found 1

```suggestion

if __name__ == '__main__':
```

2018-12-14 09:00 UTC, Fokko commented
Restarted the failed job to check if the error is transient

2018-12-21 22:40 UTC, mdziemianko commented
seems like all checks passed...:)

2018-12-26 20:01 UTC, Fokko approved these changes
Thanks @mdziemianko

2018-12-26 20:01 UTC, merged