[AIRFLOW-1409] Parse ENV connections differently
apache/airflow pull request #2451
Opened 2017-07-17 15:32 UTC by lvicentesanchez

Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [X] My PR addresses the following [AIRFLOW-1409](https://issues.apache.org/jira/browse/AIRFLOW-1409) issues and references them in the PR title.

### Description
- [X] The method `_resolve_connection` has been modified to apply different logic when the connection was parsed from a environment variable. 

### Tests
- [X] My PR adds additional unit tests in `/tests/contrib/hooks/test_spark_submit_hook.py` to make sure that the new implementation can process connections defined as ENV variables correctly and that it doesn't break the existing functionality.

### Commits
- [X] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

2017-07-23 18:59 UTC, bolkedebruin commented
@lvicentesanchez please make your commit message more descriptive what your are changing and why. Your commit title is too broad.

@Fokko can you review please?

2017-07-24 09:25 UTC, Fokko commented
I have three questions, please check. Apart from that it looks good, nice addition of the tests.

2017-07-24 14:51 UTC, lvicentesanchez commented
@bolkedebruin I will amend the commit message and title.

@Fokko I can't see any questions in the PR review.

2017-08-18 19:36 UTC, bolkedebruin commented
@fokko ^^, did you "submit" your review?

2017-08-19 17:17 UTC, Fokko requested changes

2017-08-19 17:17 UTC, Fokko commented on airflow/contrib/hooks/spark_submit_hook.py
> +            # If we use an ENV to define the connection, master can be //local,
What is the `//local` and `//yarn` connection string? Afaik as I know this isn't a proper connection url. Could you please clarify?

2017-08-19 17:17 UTC, Fokko commented on airflow/contrib/hooks/spark_submit_hook.py
> +                conn_data['master'] = self._get_master_url(conn.host, conn.port)
Why are you picking a random element? If you want HA Spark, you should provide a comma separated list of available Spark masters: https://spark.apache.org/docs/latest/spark-standalone.html

2017-08-19 17:17 UTC, Fokko commented on airflow/contrib/hooks/spark_submit_hook.py
> +                conn = random.choice(self._get_connections_from_db(self._conn_id))
Maybe you could check if you can use `get_connections` instead of `_get_connections_from_db`. The `get_connections` also falls back on `_get_connections_from_db`, so I feel like we're duplicating the logic here.
https://github.com/apache/incubator-airflow/blob/master/airflow/hooks/base_hook.py

2017-08-19 17:17 UTC, Fokko commented
@lvicentesanchez @bolkedebruin I'm sorry, I forgot to submit the review like Bolke mentioned, should be visible now. Cheers

2017-08-22 10:00 UTC, lvicentesanchez commented
@Fokko @bolkedebruin I was on holidays, I will review the comments soon and make all the necessary changes.

2017-09-04 18:29 UTC, Fokko commented
@lvicentesanchez Did you find any time to fix this?

2018-11-09 22:24 UTC, holdenk commented
@lvicentesanchez  are you still working on this PR?

2018-12-31 22:51 UTC, closed without merging