Don't crash if operator_extra_links is a property
apache/airflow pull request #25332
Opened 2022-07-27 08:06 UTC by uranusjr

See issues like #25243, #24676, and #25215.

This makes operators that implement this as an instance property compatible for task-mapping. We still can't show those extra links (since they are only available against a concrete task), but at least they are runnable.

2022-07-27 13:49 UTC, potiuk requested changes
I thin k we should make a note about it somewhere in BaseOperatorLink docs and add warning.

We might fix it permanently in the future, but it might take some time. But if we cherry-pick that one to 2.3.4 or 2.4.0 will not have a long-term base operator link treatment improved, this will be an equal (and even worse) surprise to our users if it is not documented. 

Right now, the tasks crash and it's easy to see/report, but when the user will stop seeing the links where it is supposed to be,   still an issue they will open and we need to explain to them it is intended (with docs description explaining it).

Also a Warning in log in this case sounds very  appropriate, as this is pretty surprising  behaviour.

We can always update the docs later when we fix it properly and remove the warning - but this commit should have them IMHO.

2022-07-27 20:52 UTC, josh-fell commented
+1 on a warning or some active notification (maybe even a grayed out link button and a tooltip in the Task Instance modal) so functionality isn't "missing" silently.

2022-07-28 07:05 UTC, uranusjr commented
What do y’all think should be a good way to communicate this? This needs to be done during the DAG parcing phase so a log might not be as noticable, but showing a DagWarning feels a bit excessive to me.

2022-07-28 09:55 UTC, uranusjr commented
What does not work for you? Open a new issue for that, please.

2022-07-28 10:48 UTC, Taragolis commented
@uranusjr #25360

2022-07-28 13:27 UTC, potiuk commented
> What do y’all think should be a good way to communicate this? This needs to be done during the DAG parcing phase so a log might not be as noticable, but showing a DagWarning feels a bit excessive to me.

UI information (exactly as @josh-fell mentioned) where we see that links are there but not working (grayed out) with comment. This could be a separate PR @bbovenzi @pierrejeambrun  ?

2022-07-28 15:25 UTC, bbovenzi commented
> UI information (exactly as @josh-fell mentioned) where we see that links are there but not working (grayed out) with comment. This could be a separate PR @bbovenzi @pierrejeambrun ?

I like Josh's suggestion. We can do that if we add an extra error case in the [webserver](https://github.com/apache/airflow/blob/main/airflow/www/views.py#L3501)

2022-07-29 09:02 UTC, uranusjr commented
So essentially, we invent a “fake” extra link class, and use that if the mapped operator fails to access the real extra link attribute, and return some warning information from the webserver when the special extra link class is accessed?

2022-07-29 11:00 UTC, potiuk commented
> So essentially, we invent a “fake” extra link class, and use that if the mapped operator fails to access the real extra link attribute, and return some warning information from the webserver when the special extra link class is accessed?

If we can't do "real" extra link easily, that's kinda the best way to implement it.

2022-09-23 00:16 UTC, closed without merging