HostAliases support for scheduler and webserver
apache/airflow pull request #25484
Opened 2022-08-02 18:30 UTC by rrcrrcrrc

This PR adds `scheduler.hostAliases` and `webserver.hostAliases` parameter in helm chart in order to use [kubernetes HostAliases](https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/) in scheduler and webserver pods.

2022-08-02 19:26 UTC, rrcrrcrrc commented
Can we add this feature to Helm Chart 1.7.0?

2022-08-02 20:18 UTC, potiuk commented
> Can we add this feature to Helm Chart 1.7.0?

First it would have to be reviewed and apprved as all other PRs. You need to exercise a bit of patience to get there.

2022-08-03 21:19 UTC, jedcunningham reviewed
We should also do this for the other Airflow components (workers, triggerer, etc). Up to you if you want to do it here or leave it for someone else to implement.

2022-08-03 21:19 UTC, jedcunningham commented on tests/charts/test_scheduler.py
> +                "executor": "CeleryExecutor",
```suggestion
```

Don't need that, it's the default.

2022-08-03 21:19 UTC, jedcunningham commented on chart/values.yaml
> +  # https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/
I think we can get away without these.

```suggestion
```

2022-08-03 21:19 UTC, jedcunningham commented on chart/values.yaml
> +  #   - "test.hostname.two"
```suggestion
```

I think one example should be sufficient?

2022-08-03 21:19 UTC, jedcunningham commented on chart/values.schema.json
> +                            ]
```suggestion
```

Here as well.

2022-08-06 10:55 UTC, rrcrrcrrc commented
Already edited what you comment and added hostAlises to the triggerer component too. This would make hostAliases available for Scheduler, Worker, Triggerer and Webserver.

2022-08-08 15:50 UTC, jedcunningham commented on chart/templates/triggerer/triggerer-deployment.yaml
> +        {{- toYaml $topologySpreadConstraints | nindent 8 }}
```suggestion
        {{- toYaml $topologySpreadConstraints | nindent 8 }}
```

2022-08-08 15:51 UTC, jedcunningham approved these changes

2022-08-08 20:22 UTC, jedcunningham commented on chart/values.schema.json
> +                    "description": "Specify HostAliases for trigerer.",
```suggestion
                    "description": "Specify HostAliases for triggerer.",
```

2022-08-09 00:29 UTC, jedcunningham commented on tests/charts/test_webserver.py
> +
```suggestion

```

2022-08-09 06:05 UTC, jedcunningham commented on tests/charts/test_webserver.py
> +        assert "test.hostname" == jmespath.search("spec.template.spec.hostAliases[0].hostnames[0]", docs[0])
```suggestion
        assert "test.hostname" == jmespath.search("spec.template.spec.hostAliases[0].hostnames[0]", docs[0])

```

2022-08-10 18:27 UTC, pingzh approved these changes

2022-08-11 19:56 UTC, jedcunningham requested changes
Looks like you accidentally deleted some non-helm tests?

2022-08-12 16:22 UTC, rrcrrcrrc commented
> Looks like you accidentally deleted some non-helm tests?

Yes @jedcunningham , my fault, just wanna change the "indent" to "nindent". Can someone do it for all? This week I got not PC

2022-09-03 20:47 UTC, rrcrrcrrc commented
Hi, I don´t know what to do this this PR rigth now.. Literally is my first PR

2022-09-09 03:18 UTC, potiuk commented
> Hi, I don´t know what to do this this PR rigth now.. Literally is my first PR

If you deleted stuff accidentally, If you have no idea where things get wrong - close it, open a new one and start from scratch copying new code. This is nothing Airflow specific (though we use rebase workflow) - but you can read CONTRIBUTING.rst and possibly search the internet on rebasing, solving conflicts etc. If you have no experience, then start small and take your time to learn. No hurry - you can even take online courses. When you want to contribute to open-source you need ot be self-driven , self-learning and self sufficient and while some help and guidance is given, usually it is in the form of comments in PR for concrete changes or documentation (like CONTRIBUTING) written down for you to read and learn rathe than individual hand-holding and instructing step-by-step

2022-09-09 18:59 UTC, closed without merging