[AIRFLOW-1575] Add AWS Kinesis Firehose Hook for inserting batch records
apache/airflow pull request #2586
Opened 2017-09-08 22:20 UTC by sid88in

Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-1575

### Description
- [x] Here are some details about my PR, (no UI changes)
Description is in above Jira. This PR creates a hook in contrib directory to integrate airflow with aws kinesis firehose for inserting batch items. 

### Tests
- [x] My PR adds the following unit tests 

1. test_aws_firehose_hook
This unit test checks airflow integration with AWS Kinesis Firehose. 1. checks if the connection is established using client API 2. checks batch insertion of data. We have to first create a kinesis firehose stream and then insert data

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

2017-09-08 22:30 UTC, sid88in commented
@bolkedebruin resolved commits. thanks

2017-09-08 22:30 UTC, sid88in commented
@artwr @criccomini seems like you guys reviewed similar AWS related PR - https://github.com/apache/incubator-airflow/pull/1630

Would be great if you could help review my PR. Any inputs are welcome (this is my first contribution to airflow) :)

2017-09-10 18:19 UTC, bolkedebruin commented
Can you please stop opening/closing your PRs? If you want to trigger a build please do this on your own Github account. Now you are taking build time away from other PRs and spamming email boxes.

2017-09-10 18:27 UTC, sid88in commented
@bolkedebruin sorry, I'll take care of this. I didn't know right way to trigger builds (new to the process).

2017-10-06 03:32 UTC, sid88in commented
@bolkedebruin @saguziel is this PR good to go?

2018-04-25 06:55 UTC, r39132 requested changes
Please see comments.. rebase and I'll test this out.

2018-04-25 06:55 UTC, r39132 commented on airflow/contrib/hooks/__init__.py
> +    'aws_dynamodb_hook': ['AwsDynamoDBHook']
`aws_dynamodb_hook`? The hook in this PR refers to the AWS firehose hook correct?

2018-04-25 14:08 UTC, sid88in commented
@r39132 yeah this requires rebasing. Maybe I'll create a fresh PR. Will look into it this week.

Thanks for revisiting this PR.

2018-04-25 18:45 UTC, r39132 commented
Let's keep this PR open.. just rebase and ensure that you register the appropriate hook in the file above.

2018-04-27 16:43 UTC, r39132 commented
@sid88in Ok.. feel free to open a fresh PR. Closing this.

2018-04-27 16:44 UTC, closed without merging

2018-04-28 14:42 UTC, sid88in commented
thanks @r39132 - I have created new PR here - https://github.com/apache/incubator-airflow/pull/3275