Feature/warn cli UI secrets backend
apache/airflow pull request #27034
Opened 2022-10-13 13:40 UTC by RNHTTR

I accidentally closed #24679 when I moved the code to a new branch in my fork, and I can't seem to be able to point the existing PR to the new branch & re-open the PR. So, I just opened this PR instead.

---
The Airflow CLI and UI don't show Variables or Connections that are stored in a secrets backend. This can be really confusing if you don't already know that. This PR adds a warning to CLI commands and a warning banner to the list connections and list variables views in the UI when a user has enabled a secrets backend. The warning just explains that connections and variables stored in secrets backends won't be displayed using the CLI or UI.

Closes: https://github.com/apache/airflow/issues/10867

2022-10-13 20:34 UTC, o-nikolas commented
CC: @blag @Taragolis

2022-10-23 16:29 UTC, potiuk commented
It's cool and it will remove a source of confusion for our users. 

First of all - you will need to rebase @RNHTTR - there are some conflicts.

One general comment I have - the warning message mentions EnvironmentVariablesBackend but this one is not really part of custom secret backends so the use of it is not really detected. 

I thought we should really treat Environment variables a little differently than other custom secrets. As opposed to all other secrets we can actually check if any custom connection/variable is defined in Environment and print the warning when it is. We just have to check if there are anny AIRFLOW__CONNECTION__ env variables or AIRFLOW__VARIABLES__.* 

If you do it this way (additionally to checking if there is a custom backend defined), the warning will **also** be printed when  there are any custom variables defined via env variables (and you can slightly modify the warning message to explain it).

I think that would be a more comple solution to the problem.

2022-11-16 01:36 UTC, uranusjr requested changes
Also need to update against the newest changes in main.

2022-11-16 01:36 UTC, uranusjr commented on airflow/cli/commands/connection_command.py
> +        )
```suggestion
        airflow_console.print(f"WARNING: {warning}", style="magenta")
```

2022-11-16 01:36 UTC, uranusjr commented on airflow/cli/commands/variable_command.py
> +CUSTOM_BACKEND: bool = True if get_custom_secret_backend() else False
This shouldn’t need to be repeated. Should we instead extract this to somewhere shared between both modules?

2022-11-16 01:36 UTC, uranusjr commented on airflow/cli/commands/variable_command.py
> +        )
```suggestion
        airflow_console.print(f"WARNING: {warning}", style="magenta")
```

2022-11-17 17:43 UTC, potiuk commented
Static checks ?

2022-12-03 03:04 UTC, potiuk commented
Still working on it @RNHTTR  ? needs rebase and fixes :(

2023-01-24 00:11 UTC, closed without merging