#27282: Read logs from all containers in pod for KubernetesPodOperator
apache/airflow pull request #27802
Opened 2022-11-20 10:06 UTC by mlnsharma

Implemented changes to collect logs from all containers (except airflow_xcom_sidecar container) of pod, when using KubernetesPodOperator in a DAG with get_logs=True option.

2022-11-20 10:37 UTC, mlnsharma commented
Hi @jedcunningham This PR fixes the issue from #27282

2022-11-20 11:14 UTC, bdsoha requested changes

2022-11-20 11:14 UTC, bdsoha commented on airflow/providers/cncf/kubernetes/utils/pod_manager.py
> +                    self.log.info('[%s] %s', container_name, message)
Use double quotes:

```suggestion
                    self.log.info("[%s] %s", container_name, message)
```

2022-11-20 11:14 UTC, bdsoha commented on airflow/providers/cncf/kubernetes/utils/pod_manager.py
> +            if(container_spec.name != 'airflow-xcom-sidecar'):
```suggestion
            if(container_spec.name != "airflow-xcom-sidecar"):
```

2022-11-20 11:17 UTC, bdsoha commented
@mlnsharma It seems like you have failing tests related to k8s.

https://github.com/apache/airflow/actions/runs/3507624185/jobs/5875524186#step:7:463

2022-11-20 15:24 UTC, XD-DENG reviewed
This change changes the behavior without "backward compatibility".

For example, what if I as a user still prefer to read log ONLY from he base container?

2022-11-21 07:28 UTC, mlnsharma commented
Thanks @bdsoha @XD-DENG @pulquero for your comments.
I will fix the double quotes, test failures. Regarding the backward compatibility. Do you all agree with the below solution:
- 'log_containers' will be a new parameter in KubernetesPodOperator of type string array, with the default value being ['base']. This will work only if 'get_logs=True' is passed. If the 'log_containers' value is passed as any empty array [], then all containers excluding airflow-xcom-sidecar container logs will be displayed. If the value contains any other set of container names, all those container logs will only be captured.  This new param will also be added to documentation.
- Since Airflow defaults the name of the first container to 'base', if the 'log_containers' param value consists of the actual name provided in the 'pod_template_file', all the 'log_containers' names will be checked against the actual container names in the pod. If a container name is not present in the actual pod, it will be treated as the 'base' container.

Please let me know your thoughts on the param name and any of the above statements.

2022-11-21 07:35 UTC, bdsoha commented
> Thanks @bdsoha @XD-DENG @pulquero for your comments. I will fix the double quotes, test failures. Regarding the backward compatibility. Do you all agree with the below solution:
> 
> * 'log_containers' will be a new parameter in KubernetesPodOperator of type string array, with the default value being ['base']. This will work only if 'get_logs=True' is passed. If the 'log_containers' value is passed as any empty array [], then all containers excluding airflow-xcom-sidecar container logs will be displayed. If the value contains any other set of container names, all those container logs will only be captured.  This new param will also be added to documentation.
> * Since Airflow defaults the name of the first container to 'base', if the 'log_containers' param value consists of the actual name provided in the 'pod_template_file', all the 'log_containers' names will be checked against the actual container names in the pod. If a container name is not present in the actual pod, it will be treated as the 'base' container.
> 
> Please let me know your thoughts on the param name and any of the above statements.

The proposed `log_containers` argument should allow for a `list[str] | bool`, when the value is set to `True` all containers will be logged. This simplifies the API, IMO.

2022-11-25 21:57 UTC, potiuk commented
Errors in tests.

2022-12-03 15:22 UTC, mlnsharma commented
Hi @bdsoha @potiuk I fixed the code as per comments, implemented a new log_containers option, added a couple of unit tests for the same. 
When I was testing with 'get_logs=False' option, I noticed that the airflow-xcom-sidecar container was not getting started and pod changed to NotReady state. I fixed the await_container_completion code and then it started working, I included that change also in the PR.
Can you please run the tests workflow? and review my commits?

PS: I am not sure how to squash all my commits in the PR.

2022-12-03 15:49 UTC, potiuk commented
> PS: I am not sure how to squash all my commits in the PR.

For example you can use GitHubDesktop - but there are many other guides in the internet you can find:

https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/squashing-commits

2022-12-03 17:07 UTC, XD-DENG commented
Eventually when we merge in the GitHub UI, we can choose "Squash and Merge" option. That should be sufficient?

2022-12-03 17:40 UTC, potiuk commented
> Eventually when we merge in the GitHub UI, we can choose "Squash and Merge" option. That should be sufficient?

When we merge yes. But squashing is really helpful when you continue rebasing stuff while new commits are coming on main. The problem when you `merge` using the UI rather than rebase is that your PR history gets like this:

<img width="744" alt="Screenshot 2022-12-03 at 18 30 39" src="https://user-images.githubusercontent.com/595491/205453863-8b1ae5c0-13e5-441f-8e32-5905516e2cb9.png">

Not a problem just yet in this case - but with a number of merge commits for the past, this leads to the problem that you cannot easily rebase any more because those past merges are often conflicting with current main.

So  in our case where you keep on rebasing, that becomes more and more problematic (and then eventually we cannot help by rebasing the PR while reviewing it using "Update with rebase". 

<img width="444" alt="Screenshot 2022-12-03 at 18 35 33" src="https://user-images.githubusercontent.com/595491/205454063-0313d842-d1ee-48f5-9186-92e01bb5c5c0.png">

This is often useful, when we fix things in main - we can rebase a PR without asking a contributor to do so. This is  for exmple #26970 - I have to always ask the author to do it now.

On the other hand, when you squash those changes (including past merges)  and rebase, further rebasing becomes painless - because you effectively remove all those merges and what remains is only your change - solving conflicts on rebasing then is much simpler.

2022-12-04 10:37 UTC, mlnsharma commented
Hi @potiuk @XD-DENG @bdsoha Thanks for your comments. I squashed all the commits into one commit now. Can you please review it again?

2022-12-07 12:02 UTC, mlnsharma commented
Hi @potiuk @XD-DENG @bdsoha Can you please review my code changes, all the tests are passed and the code is ready for review/merge ?

2022-12-16 02:52 UTC, mlnsharma commented
Hi @potiuk @XD-DENG @bdsoha Can you please review my code changes, please let me know if anything is pending from my end?

2022-12-26 04:29 UTC, mlnsharma commented
Hi @potiuk @jedcunningham @XD-DENG @bdsoha 
Can you please review my code changes?

2023-01-02 05:03 UTC, mlnsharma commented
Hi @potiuk @jedcunningham @XD-DENG @bdsoha
Can you please review my code changes?

2023-01-09 04:29 UTC, mlnsharma commented
Hi @potiuk @jedcunningham @XD-DENG @bdsoha
Can you please review my code changes?

2023-01-11 15:29 UTC, ashb commented
/cc @dstandish Another Kube logging PR for you 😈

2023-01-16 21:58 UTC, potiuk commented
CAn you solve the conflicts please @mlnsharma before others can take a look at it?

2023-01-17 05:30 UTC, closed without merging