27811 Add  s3 object get
apache/airflow pull request #27812
Opened 2022-11-21 06:13 UTC by Lee2532

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragement file, named `{pr_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

2022-11-21 06:15 UTC, uranusjr commented
Please follow the contributor guides, run linters locally with pre-commit, and fix the errors.

2022-11-21 09:32 UTC, Taragolis commented
@Lee2532 You need to add tests. Because looks like this operator wouldn't work with default XCom backend
- boto3.resources.factory.s3.Object - not JSON serializable
- boto3.resources.factory.s3.Object - not `pickle`ble

2022-11-22 15:53 UTC, vincbeck commented
Please also add documentation for this new operator. You likely need to update this [file](https://github.com/apache/airflow/blob/main/docs/apache-airflow-providers-amazon/operators/s3.rst)

2022-11-22 16:34 UTC, vincbeck requested changes

2022-11-22 16:34 UTC, vincbeck commented on docs/apache-airflow-providers-amazon/operators/s3.rst
> +======================
```suggestion
Get Amazon S3 object
======================
```

2022-11-22 16:34 UTC, vincbeck commented on docs/apache-airflow-providers-amazon/operators/s3.rst
> +To one Amazon S3 object within an Amazon S3 bucket you can use
```suggestion
To read one Amazon S3 object within an Amazon S3 bucket you can use
```

2022-11-22 16:34 UTC, vincbeck commented on docs/apache-airflow-providers-amazon/operators/s3.rst
> +
```suggestion
.. _howto/operator:S3GetObjectOperator:

```

2022-11-22 16:34 UTC, vincbeck commented on airflow/providers/amazon/aws/operators/s3.py
> +class S3GetObejectOperator(BaseOperator):
```suggestion
class S3GetObjectOperator(BaseOperator):
```

2022-11-22 16:34 UTC, vincbeck commented on airflow/providers/amazon/aws/operators/s3.py
> +
```suggestion

.. seealso::
        For more information on how to use this operator, take a look at the guide:
        :ref:`howto/operator:S3GetObjectOperator`
 
```

2022-11-22 16:37 UTC, vincbeck commented
I actually should have asked this question before commenting on this PR but what is your use case here? This operator returns the object specified in `s3_bucket` and `s3_key` but can you describe a DAG where this operator would be used? A S3 file can be big and Xcom should not be used to share large amount of data  between operators. If what you are trying to achieve is reading data from S3 bucket and send it to another source, maybe a transfer operator would be more suitable for this use case.

2022-11-25 22:22 UTC, potiuk commented
Would be great to fix all the comments/typos.

2022-12-13 08:41 UTC, shubham22 commented
@Lee2532 - I'm wondering if you're still looking into this. Let us know if you need any help. Also, if you get chance, can you clarify the use case as @vincbeck asked?

2022-12-13 16:17 UTC, potiuk commented
Closing then

2022-12-13 16:17 UTC, closed without merging