check jenkins result state
apache/airflow pull request #28659
Opened 2022-12-31 18:19 UTC by tnyz

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

2022-12-31 18:46 UTC, eladkal commented
Is this related to https://github.com/apache/airflow/issues/28465 ?

2022-12-31 19:26 UTC, tnyz commented
No, I think what was described in that ticket is about scheme instead of schema `scheme://user:password@host%2Flocation:1234/schema?__extra__=%7B%22my_val%22%3A+%5B%22list%22%2C+%22of%22%2C+%22values%22%5D%2`

2023-01-02 18:13 UTC, tnyz commented
@eladkal any chance you can review this? thanks

2023-01-02 21:40 UTC, uranusjr requested changes
Also you need to fix CI errors.

2023-01-02 21:40 UTC, uranusjr commented on airflow/providers/jenkins/hooks/jenkins.py
> +            raise AirflowException(f"Jenkins call failed with error : {err}")
Do not catch this, let the Jenkins error bubble. (Same for other functions.)

2023-01-02 21:40 UTC, uranusjr commented on airflow/providers/jenkins/sensors/jenkins.py
> +            raise AirflowException("The build result does not meet the target states.")
Can this be more specific? Can the user do something to fix this, or is this an impossible situation the user should tell the Jenkins admin?

2023-01-04 06:02 UTC, uranusjr commented on tests/providers/jenkins/sensors/test_jenkins.py
> -            ),
Why is this case removed?

2023-01-04 06:02 UTC, uranusjr approved these changes

2023-01-04 06:02 UTC, uranusjr commented
Need to fix static checks.

2023-01-04 07:57 UTC, tnyz commented
> Need to fix static checks.

Good to merge

2023-01-06 03:57 UTC, uranusjr approved these changes

2023-01-06 08:16 UTC, potiuk approved these changes

2023-01-06 08:16 UTC, merged