Added samba hook remove & copyfile functionalities
apache/airflow pull request #28923
Opened 2023-01-13 12:52 UTC by venufix

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

2023-01-15 10:40 UTC, Taragolis requested changes
- Static checks failed, please follow this [Guide](https://github.com/apache/airflow/blob/main/STATIC_CODE_CHECKS.rst)
- Tests need to be fixed

2023-01-15 10:40 UTC, Taragolis commented on airflow/providers/samba/hooks/samba.py
> +        return smbclient.copyfile(self.__join_path(src), self.__join_path(dst), **self._conn_kwargs)
```suggestion
        return smbclient.copyfile(self._join_path(src), self._join_path(dst), **self._conn_kwargs)
```

2023-02-18 20:04 UTC, Taragolis commented
@venufix, do you have a plan to continue work on this PR?

2023-02-18 23:30 UTC, venufix commented
Unfortunately no, found another solution you fan actually get the samba client args from the hook and run the function

2023-02-19 09:42 UTC, Taragolis commented
> Unfortunately no, found another solution you fan actually get the samba client args from the hook and run the function

No problem at all.

2023-02-19 09:42 UTC, closed without merging