Add ttlSecondsAfterFinished to migrateDatabaseJob and createUserJob
apache/airflow pull request #29314
Opened 2023-02-02 13:09 UTC by alexandermalyga

related: #27561

Adds the [ttlSecondsAfterFinished](https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/) parameter  to `migrateDatabaseJob` and `createUserJob`, so job objects can be automatically deleted after execution.

2023-02-02 16:40 UTC, alexandermalyga commented on chart/templates/jobs/create-user-job.yaml
> +  {{- if not (kindIs "invalid" .Values.createUserJob.ttlSecondsAfterFinished) }}
Checking specifically for `not nil` because `0` is a valid value for this field and it would evaluate to false normally.

2023-02-13 08:22 UTC, potiuk commented
Ach I missed that one and it's a better fix than mine #29439

2023-02-13 08:23 UTC, potiuk reviewed
This is better than mine - also @hussein-awala suggest that we could rename the jobs so that it will also work even if update is done quickly.

2023-02-13 08:24 UTC, potiuk commented on chart/values.yaml
> +  ttlSecondsAfterFinished: ~
I think we should come up with reasonable default (I had 300 in #29439)

2023-02-13 08:25 UTC, potiuk requested changes
OK. Pending the two small comments @dstandish @jedcunningham - in case you think there is a reason why job name cannot be changed, pleas shout :)

2023-02-13 11:52 UTC, alexandermalyga commented
> This is better than mine - also @hussein-awala suggest that we could rename the jobs so that it will also work even if update is done quickly. See [#29439 (review)](https://github.com/apache/airflow/pull/29439#pullrequestreview-1294842286)

I tried and this affects a lot of tests, let's do it in a separate PR?

2023-02-13 11:56 UTC, potiuk commented
> > This is better than mine - also @hussein-awala suggest that we could rename the jobs so that it will also work even if update is done quickly. See [#29439 (review)](https://github.com/apache/airflow/pull/29439#pullrequestreview-1294842286)
> 
> I tried and this affects a lot of tests, let's do it in a separate PR?

I am fine with it.

2023-02-13 11:56 UTC, potiuk approved these changes

2023-02-20 01:02 UTC, merged