fix update_mask in patch variable route
apache/airflow pull request #29711
Opened 2023-02-22 23:38 UTC by hussein-awala

closes: #29702 

---
`patch_variable` route does not allow updating the variable description. This PR updates the method and uses the same pattern used in the other routes to dynamically update all the fields which are not `non_update_fields`.

2023-02-23 06:37 UTC, uranusjr reviewed
Minor code improvements

2023-02-23 06:37 UTC, uranusjr commented on airflow/api_connexion/endpoints/variable_endpoint.py
> +        data = data_
```suggestion
        data_ = {}
        for field in update_mask:
            field = field.strip()
            if field in data and field not in non_update_fields:
                data_[field] = data[field]
            else:
                raise BadRequest(detail=f"'{field}' is unknown or cannot be updated.")
        data = data_
```

2023-02-23 06:37 UTC, uranusjr commented on airflow/api_connexion/endpoints/variable_endpoint.py
> +        setattr(variable, key, data[key])
```suggestion
    for key, val in data.items():
        setattr(variable, key, val)
```

2023-02-23 19:54 UTC, dimberman requested changes, later dismissed

2023-02-23 19:54 UTC, dimberman commented on airflow/api_connexion/endpoints/variable_endpoint.py
> +        data = data_
This seems like a lot of nesting. Can you break this out into a separate function?

2023-03-03 14:46 UTC, hussein-awala commented
@dimberman Can you please review my last commit?

2023-03-09 06:01 UTC, uranusjr commented on airflow/api_connexion/endpoints/variable_endpoint.py
> +    session.commit()
Don’t need this, the session is comitted when the function returns.

2023-03-10 18:32 UTC, potiuk commented
@dimberman ? Is your "request changes" still valid ? I think it has been addressed but I would not want to dismiss the review without you confirming.

2023-03-18 21:02 UTC, potiuk commented
Since you have not responded @dimberrman, I will simply dismiss it. 2 weeks and no response despite pinging seems to be enough. We can always have a follow-up if the "request for changes" is still not resolved.

2023-03-18 21:03 UTC, potiuk approved these changes

2023-03-18 21:03 UTC, merged