Add prettier formatting for www
apache/airflow pull request #29768
Opened 2023-02-25 20:27 UTC by pierrejeambrun

**Issue**:
Formatting with eslint is too permissive. 2 different formatting style can be considered 'valid' for eslint but quite different in practice. Also formatting with eslint is not the most common so switching for prettier might be helpful. (most front-end dev have their IDE already working with prettier)

**Solution**:
This introduce an opinionated formatter to have better consistency in our front-end code base.

- Integrate with our `eslint` config
- Integrate with our `stylelint` config
- Add the prettier formatting step to the pre-commit hook, and rename/clarify the hook id/description

2023-02-25 20:29 UTC, potiuk approved these changes

2023-02-25 20:37 UTC, pierrejeambrun commented on airflow/www/.prettierrc
> +{
This is necessary because prettier is otherwise using the default config in `.editorconfig` that will format with an indent size of 4 the json files.

2023-02-25 20:37 UTC, pierrejeambrun commented on airflow/www/.prettierignore
> +*.md
Don't prettier format yaml and md. Those are handled by other dedicated pre-commit hook.

2023-02-27 01:46 UTC, bbovenzi requested changes
Looking good! Let's update the [contributing documentation](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#installing-yarn-and-its-packages-manually) too.

2023-02-27 18:17 UTC, bbovenzi approved these changes

2023-02-27 20:06 UTC, merged

2023-03-08 01:15 UTC, jedcunningham commented
(Kicking this to 2.6)