feat: add extra annotations pgbouncer
apache/airflow pull request #30168
Opened 2023-03-17 18:33 UTC by dim-ops

Add extra annotations for pgbouncer deployment

2023-03-20 17:58 UTC, dim-ops commented
Hello @josh-fell, I'm not sure to understand why `Tests / Static checks`fails, can you explain me ?

2023-03-20 20:41 UTC, dim-ops commented
I think I finally figured out the error in the IC `E501 Line too long` means I have too many characters on one line, I formatted my code another way.

I have another solution otherwise @josh-fell

2023-04-04 10:32 UTC, dim-ops commented
@joshfell is it possible to merge ?

2023-04-04 12:26 UTC, josh-fell commented
> @JoshFell is it possible to merge ?

I wouldn't be the best person to review this PR as I have never worked with the charts. (I just noticed there seemed to be very similar PRs open between yours and another.) I'd feel more comfortable if the code owners weighed in. 

I did kick off CI for you which was waiting for approval to run.

2023-04-08 04:18 UTC, jedcunningham requested changes

2023-04-08 04:18 UTC, jedcunningham commented on chart/values.yaml
> +  extraAnnotations: {}
```suggestion
  podAnnotations: {}
```

Let's use podAnnotations instead for consistency across components.

2023-04-08 04:18 UTC, jedcunningham commented on tests/charts/test_pgbouncer.py
> +    def test_pgbouncer_deployment_extra_annotations(self):
Can you add coverage [here](https://github.com/apache/airflow/blob/0fe73c2e8c0ca90faf54b39139ffab5769f4cca1/tests/charts/test_annotations.py#L371) instead?

2023-04-08 04:18 UTC, jedcunningham commented on chart/templates/pgbouncer/pgbouncer-deployment.yaml
> +{{- end }}
```suggestion
      {{- if .Values.pgbouncer.extraAnnotations }}
        {{- toYaml .Values.pgbouncer.extraAnnotations | nindent 8 }}
      {{- end }}
```

Let's indent it like this instead.

2023-04-08 04:21 UTC, jedcunningham commented on chart/templates/pgbouncer/pgbouncer-deployment.yaml
> +{{- end }}
Just to add a little more color here, there is nothing wrong with how you have it, we just had a few other PRs recently that did some formatting cleanup and I'd like to keep things consistent 👍

2023-04-10 15:12 UTC, jedcunningham approved these changes

2023-04-10 16:29 UTC, merged

2023-04-10 16:30 UTC, jedcunningham commented
Thanks @dim-ops! Congrats on your first commit 🎉