[AIRFLOW-2099] Handle getsource() calls gracefully
apache/airflow pull request #3032
Opened 2018-02-11 19:45 UTC by night0wl

There are several scenarios where Task Instance view tries to render
Python callables where 'x' is not the correct artefact to target.

This commit adds a helper fuction to test for known scenarios, and
derives the source from the correc artefact or as a default returns
'No source available for <type>'. This means that even in unknown or
unfixable edge cases, the Task Instance view still renders instead of
displaying an exception.

Make sure you have checked _all_ steps below.

### JIRA
- [ ] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-XXX

### Description
- [ ] Here are some details about my PR, including screenshots of any UI changes:

### Tests
- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [ ] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

- [ ] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

2018-02-12 18:52 UTC, ashb commented on tests/core.py
> +        self.assertEquals(response.status_code, 200)
Some kind of tests of the content would be good.

2018-02-12 22:49 UTC, night0wl commented
Fair comment @ashb , I have amended the tests to use `AssertIn` instead, and to check for doc string of expected source code.

2018-02-16 09:57 UTC, bolkedebruin requested changes
Couple of small things, almost ready.

2018-02-16 09:57 UTC, bolkedebruin commented on tests/dags/test_issue_2099.py
> +# -*- coding: utf-8 -*-
Please use a descriptive name for the file and dag. This makes it easier to make out when it fails.

2018-02-16 09:57 UTC, bolkedebruin commented on tests/dags/test_issue_2099.py
> +dag = DAG(dag_id='test_issue_2099_dag', default_args=default_args)
Please use descriptive naming

2018-02-16 09:57 UTC, bolkedebruin commented on airflow/www/views.py
> +def get_python_source(x):
please move this to www/utils.py .

2018-02-25 11:26 UTC, bolkedebruin commented
@night0wl any updates?

2018-04-09 08:18 UTC, bolkedebruin commented
@night0wl Any updates? will close in next 3 days otherwise

2018-04-26 04:32 UTC, closed without merging

2018-04-26 04:34 UTC, r39132 commented
@night0wl Kindly reopen when ready for review.

2018-07-03 12:43 UTC, night0wl commented
Hi @r39132 and @bolkedebruin 

Apologies it has taken me ages to get back onto this.

I have rebased onto master branch, actioned the requests above and opened a new PR
https://github.com/apache/incubator-airflow/pull/3571

All Travis checks are passing.