fix issue: DAG's on_failure_callback is not invoked when task failed during testing dag.
apache/airflow pull request #30965
Opened 2023-04-30 00:59 UTC by mis98zb

The DAG.test() code is as below:
```python
        # Instead of starting a scheduler, we run the minimal loop possible to check
        # for task readiness and dependency management. This is notably faster
        # than creating a BackfillJob and allows us to surface logs to the user
        while dr.state == State.RUNNING:
            schedulable_tis, _ = dr.update_state(session=session)
            for ti in schedulable_tis:
                add_logger_if_needed(ti)
                ti.task = tasks[ti.task_id]
                _run_task(ti, session=session)
        if conn_file_path or variable_file_path:
            # Remove the local variables we have added to the secrets_backend_list
            secrets_backend_list.pop(0)
```
When exception occurred in a task, the exception will be raised from `_run_task(ti, session=session)`.
In the loop, there is no try...except, so the function is terminated immediately.
This is the reason why DAG's on_failure_callback cannot be invoked during testing.

2023-05-02 12:05 UTC, potiuk requested changes
Could we also add some actual test running this scenario (those tests are in "models/test_dag.py".

2023-05-04 02:20 UTC, mis98zb commented
got it.

2023-05-22 04:55 UTC, mis98zb commented
Sorry for late. I have added the actual test for dag.test() with failure.

2023-05-25 06:25 UTC, mis98zb commented
I have removed the wrong test code. Can anyone help to approve the testing?
thanks & best regards.

2023-05-25 06:28 UTC, uranusjr commented on airflow/models/dag.py
> +                self.log.info("Task failed, continue looping. DAG will be marked as failed at the end of looping.")
```suggestion
                self.log.info(
                    "Task failed. DAG will continue to run until finished "
                    "and be marked as failed."
                )
```

2023-05-25 06:29 UTC, uranusjr commented on airflow/models/dag.py
> +                self.log.info("Task failed, continue looping. DAG will be marked as failed at the end of looping.")
This wording is likely better than “looping”.

2023-05-30 06:15 UTC, uranusjr commented on airflow/models/dag.py
> +                )
Should we add the exception to the log so the user knows what happened? Or would that be unhelpful? (Not sure.)

2023-05-30 06:16 UTC, uranusjr commented on airflow/models/dag.py
> +                )
```suggestion
                self.log.info(
                    "Task failed. DAG will continue to run until finished "
                    "and be marked as failed.",
                    exc_info=True,
                )
```

If we want to include the exception.

2023-05-30 06:16 UTC, uranusjr approved these changes

2023-05-30 08:57 UTC, mis98zb commented on airflow/models/dag.py
> +                )
I see. Thank you for the advise.

2023-06-06 03:40 UTC, mis98zb commented
@potiuk I have added some tests for the code change. May I know if the is enough? Thanks & Best Regards.

2023-06-06 07:15 UTC, uranusjr approved these changes

2023-06-06 14:07 UTC, potiuk approved these changes

2023-06-09 06:00 UTC, mis98zb commented
Don't know why the build keep failing, ToT
Seems the failed test is not related to the code change in this PR....

2023-06-09 06:02 UTC, mis98zb commented
May I know how can I format code in local machine?

I tried `--config .\pyproject.toml airflow`, but it cannot get the same result in the build...

2023-06-09 06:07 UTC, uranusjr commented
Please set up pre-commit as described in the contributor’s guide.

2023-06-09 09:04 UTC, potiuk commented
> Please set up pre-commit as described in the contributor’s guide.

The instructions were actually printed by pre-commit, but could be lost in see of messages - I made PR to display far more prominent https://github.com/apache/airflow/pull/31813

2023-06-09 09:05 UTC, potiuk approved these changes

2023-06-09 09:05 UTC, merged