Decrease trigger ending log message level to info
apache/airflow pull request #31802
Opened 2023-06-08 18:35 UTC by hussein-awala

closes: #31799

I searched in the history about the reason to use 100 as log level, but it seems that it was just for debugging, where there is no logical need to log an error here, sine we need to stop the trigger after each run.

This line was added by #29482 which restored #27758

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

2023-06-08 18:36 UTC, potiuk commented
I think @dstandish should have a say on this one.

2023-06-08 18:36 UTC, potiuk approved these changes

2023-06-08 18:38 UTC, hussein-awala commented
> I think @dstandish should have a say on this one.

Indeed, I was going to mention him.

2023-06-09 04:21 UTC, dstandish requested changes
nope can't do this.

this is a special log message that signals to the wrapper "this handler can be closed" so we need it.

it's filtered out so user should never see it.

perhaps we should add a clarifying comment instead?

if you are seeing it then something is probably not working right let me review the issue

2023-06-09 08:08 UTC, potiuk commented
> perhaps we should add a clarifying comment instead?

Clearly we need it as none of us had a clue about it :)

2023-06-28 22:51 UTC, closed without merging