[AIRFLOW-2254] Put header as first row in unload
apache/airflow pull request #3180
Opened 2018-04-01 08:33 UTC by sathyaprakashg

Currently, data is ordered by first column in descending order
Header row comes as first only if the first column is integer
This fix puts header as first row regardless of first column data type

Make sure you have checked _all_ steps below.

### JIRA
- [x ] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-2254

### Description
- [x ] Here are some details about my PR, including screenshots of any UI changes:
In RedshiftToS3Operator, data was ordered by first column in descending order. Header row comes as first only if the first column is integer. Additional column called sort order is used to order the rows such that header row is always comes first in the file regardless of first column data type. This additional column is used only for sorting and not part of the output

### Tests
- [x ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
TestRedshiftToS3Transfer - Updated test case to reflect the change 

### Commits
- [x ] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

- [ x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

2018-04-06 06:40 UTC, sekikn commented
Tested the PR with a real Redshift cluster and confirmed that it worked.
It would be better if it was documented that the header is output into only the first file and users have to specify `PARALLEL OFF` to unload_options if they wants to load the output files back to Redshift correctly.

2018-04-09 07:45 UTC, Fokko requested changes
For readability sake, could we format the huge string using a dict?

2018-04-09 07:45 UTC, Fokko commented on tests/operators/test_redshift_to_s3_operator.py
> +                UNLOAD ('SELECT {0} FROM
What is the impact of omitting the quotes?

2018-04-10 05:20 UTC, sathyaprakashg reviewed
Are you referring to single quotes in `UNLOAD ('SELECT {0} FROM`. If so, yes this single quotes required as part of the syntax. Please refer here https://docs.aws.amazon.com/redshift/latest/dg/r_UNLOAD.html

Regarding formatting the huge string using a dict, i feel keeping this way makes this SQL statement more readable. Incase if you still feel otherwise :), i will go ahead and change it, please let me know.

2018-04-10 07:16 UTC, Fokko commented
For me this is much more readable: https://github.com/apache/incubator-airflow/pull/3161/files#diff-29783382cba0dab86c4000024aa7a95aR75

2018-04-12 20:21 UTC, sathyaprakashg commented
@sekikn I added a parameter called include_header. Only if this is true, header will be included part of the file. Also, if include_header is true then `PARALLEL OFF` command will be automatically included if it was not provided in unload_options

2018-04-12 20:24 UTC, sathyaprakashg commented
@Fokko Now I understood what you meant. :) I made the changes. Please review it. Thanks.

2018-04-13 04:58 UTC, sekikn commented
> I added a parameter called include_header. Only if this is true, header will be included part of the file.

Thanks for updating @sathyaprakashg, that's really nice improvement. I confirmed that both of include_header=True and False work as expected with a real Redshift cluster.
Just one comment, defaulting include_header=False changes the default behaviour and introduces backward incompatibility, so would you add an entry about that to UPDATING.md? +1 other than that.

2018-04-13 07:54 UTC, sathyaprakashg commented
@sekikn Thanks for testing it. I updated UPDATING.md as well. This is my first pull request to GitHub so forgive me for not knowing to update the UPDATING.md :)

2018-04-13 09:22 UTC, Fokko requested changes
One minor nit, apart from that LGTM. Nice addition.

2018-04-13 09:22 UTC, Fokko commented on UPDATING.md
> +###Redshift to S3 Operator
Please add a space here

2018-04-14 04:15 UTC, sathyaprakashg commented
@Fokko I added space in UPDATING.md

2018-04-16 08:10 UTC, sekikn commented
BTW, I've just noticed `include_header=False` also resolves [AIRFLOW-1270](https://issues.apache.org/jira/browse/AIRFLOW-1270) and [AIRFLOW-1862](https://issues.apache.org/jira/browse/AIRFLOW-1862). I confirmed that precision loss for timestamp and cast error for boolean doesn't occur with that option. Great work @sathyaprakashg!

2018-04-16 08:21 UTC, Fokko approved these changes
Thanks @sathyaprakashg, LGTM!

2018-04-16 08:22 UTC, closed without merging