[AIRFLOW-2333] Add Segment Hook with unit tests
apache/airflow pull request #3237
Opened 2018-04-18 04:42 UTC by jzucker2

Make sure you have checked _all_ steps below.

### JIRA
- [ ] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-2333
    - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a JIRA issue.

### Description
- [ ] Here are some details about my PR, including screenshots of any UI changes:
Add Segment Hook to store Segment Analytics access
token with encryption in metadata database.

### Tests
- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
Unit test added.

### Commits
- [ ] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
    - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality
- [ ] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

2018-04-18 08:37 UTC, Fokko requested changes
Thanks @jzucker2 for the contribution.

I looked into Segment and really like it. But contributing only a hook, doesn't really make sense to me. The hooks represent connections to the backend (in this case Segment). The hook comes with an operator, which is used by the developer to interact with. Sometimes, the more advanced Airflow users, also use hooks on its own. Could you explain what you are trying to achieve?

2018-04-18 08:37 UTC, Fokko commented on airflow/contrib/hooks/segment_hook.py
> +        if self.segment_debug_mode:
Please remove this if, if you are logging in debug mode, then you should just show everything.

2018-04-18 08:37 UTC, Fokko commented on airflow/contrib/hooks/segment_hook.py
> +        :type segment_debug_mode: False
Type is boolean I guess.

2018-04-21 18:33 UTC, tedmiston commented
@jzucker2 Are you open to adding a `SendTrackEventOperator` that takes a name and a dict to pass through to `analytics.track(...)`?

I'd be curious to know if you find other event types useful here as well, maybe `SendIdentifyEventOperator` would be nice?

2018-04-26 04:28 UTC, r39132 commented
@jzucker2 please respond to comments and rebase.

2018-04-26 04:31 UTC, jzucker2 commented
@tedmiston I am definitely interested in adding the `SendTrackEventOperator`

@r39132 sorry for the delay. Been busy with some work emergencies, should have time to give this another pass with the suggested operators from @tedmiston by end of next week.

2018-04-26 14:49 UTC, tedmiston commented
Sounds great.  Happy to help test this as well.

2018-05-05 21:18 UTC, r39132 commented
@jzucker2 ping.. just a friendly reminder.

2018-05-07 18:13 UTC, r39132 commented
Closing this for now. Please re-open when ready

2018-05-07 18:15 UTC, closed without merging

2018-05-07 18:34 UTC, jzucker2 commented
@r39132 woah! I didn't even get a work day to respond. I was actually working on rebasing while you closed this.

2018-05-07 21:17 UTC, jzucker2 commented
@r39132 I added an operator and got all unit tests passing but I'm waiting on you to reopen this pull request.

2018-05-09 01:03 UTC, tedmiston commented
I see some PRs like https://github.com/apache/incubator-airflow/pull/3197 https://github.com/apache/incubator-airflow/pull/3319 preface their title with [WIP] to make it clear to maintainers that it's still being actively developed.  Not sure if that's helpful or if we've got a standard here.

I've also seen other repos with a bot to close open PRs after e.g., 30 days of no activity.

2018-05-09 01:11 UTC, jzucker2 commented
@tedmiston I am done with this and want to merge it but I see no way to reopen this pull request in the UI. I appreciate the discussion of [WIP] but my last comment clearly indicates I am not WIP but in fact done.

As far as inactivity, this was inactive for less than half the 30 days discussed.

2018-05-09 16:46 UTC, r39132 commented
@jzucker2 Open a new PR and reference this if there is a need to keep the history.