Cloudbatch
apache/airflow pull request #32606
Opened 2023-07-14 14:47 UTC by fdemiane

Add Google Cloud Batch Operators

2023-07-19 12:09 UTC, fdemiane commented on tests/providers/google/cloud/operators/test_cloud_batch.py
> +CLOUD_BUILD_HOOK_PATH = "airflow.providers.google.cloud.operators.cloud_batch.CloudBatchHook"
Comment to self: Rename to CLOUD_BATCH_HOOK_PATH

2023-07-20 08:02 UTC, fdemiane commented on airflow/providers/google/cloud/operators/cloud_batch.py
> +                    polling_period_seconds=self.polling_period_seconds
comment to self: pass timeout_seconds

2023-07-24 20:50 UTC, fdemiane commented on tests/providers/google/cloud/triggers/test_cloud_batch.py
> +        Tests the CloudBuildCreateBuildTrigger fires once the job execution times out with an error message.
Comment to self: CloudBatch*

2023-07-25 12:03 UTC, fdemiane commented on tests/providers/google/cloud/hooks/test_cloud_batch.py
> +
Comment to self: CloudBathcAsyncHook isn't covered

2023-07-26 08:42 UTC, fdemiane commented on airflow/providers/google/cloud/operators/cloud_batch.py
> +        deferrable: bool = False,
Comment to self: deferrable: bool = conf.getboolean("operators", "default_deferrable", fallback=False)

Run pre-commit hook

2023-07-27 14:05 UTC, ahidalgob requested changes
Please make sure pre-commit is ran, or manually run `breeze static-checks --all-files`.

2023-07-27 14:05 UTC, ahidalgob commented on airflow/providers/google/cloud/hooks/cloud_batch.py
> +        return result
This method is equivalent to `list(itertools.islice(jobs, limit))`

2023-07-27 14:05 UTC, ahidalgob commented on airflow/providers/google/cloud/hooks/cloud_batch.py
> +            self._client = BatchServiceClient()
```suggestion
            self._client = BatchServiceClient(credentials=self.get_credentials())
```

2023-07-27 14:05 UTC, ahidalgob commented on airflow/providers/google/cloud/hooks/cloud_batch.py
> +        return self.get_conn().get_job(name=f"{job_name}")
```suggestion
        return self.get_conn().get_job(name=job_name)
```

Also present in other places

2023-07-27 14:05 UTC, ahidalgob commented on airflow/providers/google/cloud/hooks/cloud_batch.py
> +            self._client = BatchServiceAsyncClient()
Also credentials

2023-07-27 14:05 UTC, ahidalgob commented on airflow/providers/google/cloud/hooks/cloud_batch.py
> +        self._client: BatchServiceAsyncClient = BatchServiceAsyncClient()
```suggestion
        self._client: BatchServiceAsyncClient | None = None
```
We leave the client instantiation out of the constructor.

2023-07-27 14:05 UTC, ahidalgob commented on airflow/providers/google/cloud/hooks/cloud_batch.py
> +    async def get_build_job(
Why is it "build"? I think this is a bit confusing, the same for 'submit_build_job`

2023-08-07 19:41 UTC, ahidalgob commented on airflow/config_templates/default_airflow.cfg
> -
:smiley:

2023-08-07 19:41 UTC, ahidalgob commented on tests/system/providers/google/cloud/cloud_batch/example_cloud_batch.py
> +    ((submit1, submit2) >> list_tasks >> assert_tasks >> list_jobs >> get_name >> (delete_job1, delete_job2))
Most code uses [ ] instead of ( )

2023-08-07 19:41 UTC, ahidalgob commented on docs/apache-airflow-providers-google/operators/cloud/cloud_batch.rst
In Google operators doc we include `/operators/_partials/prerequisite_tasks.rst` as prerequisites

2023-08-07 19:41 UTC, ahidalgob commented on airflow/providers/google/cloud/triggers/cloud_batch.py
> +                    self.log.info("Sleeping for %s seconds.", self.polling_period_seconds)
Maybe better to join into only one log statement

2023-08-07 19:41 UTC, ahidalgob commented on airflow/providers/google/cloud/operators/cloud_batch.py
> +    def execute(self, context):
Missing type hints

2023-08-07 19:41 UTC, ahidalgob commented on airflow/providers/google/cloud/operators/cloud_batch.py
> +    def execute(self, context):
Missing type hints

2023-08-07 19:41 UTC, ahidalgob commented on airflow/providers/google/cloud/hooks/cloud_batch.py
> +    def submit_build_job(
Why is it "build" job?

2023-08-10 17:26 UTC, potiuk commented
Rebased to account for some flaky test failures.

2023-08-15 21:14 UTC, fdemiane commented
Hello @potiuk,
I need a reviewer to review and accept the pull request. @ahidalgob already reviewed it. I would appreciate your assistance.
Thanks!

2023-08-16 07:03 UTC, ahidalgob approved these changes

2023-08-16 12:38 UTC, eladkal commented on airflow/providers/google/cloud/hooks/cloud_batch.py
> +        super().__init__(gcp_conn_id=gcp_conn_id, impersonation_chain=impersonation_chain)
Lets not add this to new operators.
same reasoning as https://github.com/apache/airflow/pull/33067#discussion_r1295712293

2023-08-18 14:53 UTC, fdemiane commented
> There are some failures you need to look at, I rebased it to account for any potential issues you could have from past runs, but you need to take a look and let us know when they are solved.

@potiuk thank you for the comment, I fixed all the issues and now all checks look green

2023-08-18 18:59 UTC, potiuk approved these changes

2023-08-18 19:00 UTC, merged