enable db access for dag run listeners
apache/airflow pull request #32876
Opened 2023-07-27 07:14 UTC by mis98zb

2023-07-27 07:20 UTC, uranusjr commented
This breaks backward compatibility. Not sure if it is a good idea. What’s the problem with opening a session in the hook instead?

2023-07-27 07:23 UTC, mis98zb commented
I tried with `@provide_session`, it will got exception with HA configuration:
```
UNEXPECTED COMMIT - THIS WILL BREAK HA LOCKS
```

2023-07-27 07:32 UTC, mis98zb commented
And, there are similar exception when I use hook inside the dag_run_listener.
By investigating, I found that hooks will use `Connection.get_connection_from_secrets(conn_id)` to get connection.
There are two default secret back ends: EnvironmentVariablesBackend and MetastoreBackend.
The MetastoreBackend uses `@provide_session` to open a new session, and do commit.
The exception is raised on committing...

For this, I have to change to use environment variables to set connection.
But this is not encrypted.
Do you have suggestions for this?

2023-08-15 10:47 UTC, mis98zb commented
Thank you for the answer!

But seems this does not work for me.
The `@provide_session` will call submit() when the function exit, and it's inside the `@provide_session` of scheduler.
This will cause the `UNEXPECTED COMMIT - THIS WILL BREAK HA LOCKS` exception...

Maybe run the listeners inside the scheduler loop is not so good.
If it is run as a task, that should be great...

2023-08-17 18:34 UTC, potiuk commented
I agree, this is a very bad idea to allow db access here. There are multiple reasons (HA locks is the most important one) why "user provided code" should not mess around the sessions and DB while  dag runs are processed by the scheduler. We heavily rely on those db operations to be performant, have very strictly demarcated session boundaries. Adding a DB code run by user in some crucial moments, might cause a number of subtle problems that might be extremely difficult to diagnose. Basicaly by opening this option you are shooting yourself in the foot (and actually more likely you will be passing the problems on maintainers when some unintended side-effects kick in).

Alos listener by definition should avoid doing any "heavy" work. It just listens, by implementing some database/heavy processing in it, you are likely impacting scheduler's performance a lot. Don't do it.

IMHO trying to run DB operations and reading Xcom here is doubly wrong:

* You should use Airflow REST API to access XCom information
*  You should not run any heavy workload in your listeners. Your listerners should at most trigger (for example) a lambda  function in AWS to perform such summary.

2023-08-17 18:35 UTC, potiuk requested changes
Unless there are some new points,  I am strongly -1 on passing session to listeners for the reasons explained in my comment.

2023-08-22 09:06 UTC, mis98zb commented
Got it.
I'll change to call restful api in listener. And let the api it call airflow rest api to get error details.

However, there is still a problem:
To call restful api, airflow need get connections. If the connections are stored in airflow db, the `UNEXPECTED COMMIT` exception will be thrown.
That is, connections for restful api which used in listener cannot be stored in airflow db.
Fortunately, there is workaround for this. We can store connections in places other than airflow db. For example, in environment variables...

2023-08-22 11:34 UTC, potiuk commented
> Fortunately, there is workaround for this. We can store connections in places other than airflow db. For example, in environment variables...

Or secret backends, or even filesystem secret backend. I wouldn't even call it workaround it's pretty standard approach. 

Also there is no particular reason to store the API credentials as connection in the DB for such API call. It does not even have to use "Connection" mechanism. You can simply make a regular env variable, mounted as secret in K8S for that. The calls to the API  via Airflow Python client are not assuming you are going to use Connection for it. It has never meant to be used with Airflow Connections actually, as the whole idea is to call it from "outside" of Airflow (in this case you will call it from "inside" but this is accidental). So credentials can be passed from any source - Connection seems like unnecessary abstraction to use for it.

2023-08-23 02:30 UTC, mis98zb commented
Yes, you are right.
There are variable ways to call external APIs.

Previously I used airflow web UI to add connections, which are used in tasks.
So the connections are stored in airflow db...
Currently I'm using environment variables for connections.
Everything working fine, except that I cannot see connections in web UI anymore, :)

2023-08-23 03:01 UTC, closed without merging

2023-08-23 03:01 UTC, mis98zb commented
instead of read xcom in listener, read xcom via airflow restful api from backend service.