Fixing typo in Dockerfile
apache/airflow pull request #33180
Opened 2023-08-07 16:54 UTC by amoghrajesh

Fixing a small typo noticed in the Dockerfile

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

2023-08-07 18:47 UTC, potiuk approved these changes

2023-08-07 18:50 UTC, potiuk requested changes
Actually - you need to correct it in the source files (in scripts/docker/ - If you look a few pages  above, this part of the Dockerfile is in-lined by pre-commit, so in order to update it in the Dockerfile you need to updated it where the source it, run commit (with pre-commit) and let pre-commit inline it.

2023-08-08 04:44 UTC, uranusjr approved these changes

2023-08-08 07:18 UTC, potiuk approved these changes

2023-08-08 07:19 UTC, merged