AWS Authentication docs updated with correct path for credentials file
apache/airflow pull request #33182
Opened 2023-08-07 20:52 UTC by jaketerrito

The documentation for AWS authentication specifies that aws credentials should be in /home/.aws/.

Based off the [home directory in the airflow docker file](https://github.com/apache/airflow/blob/main/Dockerfile#L44), the configuration file should actually be in /home/airflow/.aws.

This pull request updates the documentation to reflect the correct path.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

2023-08-07 21:44 UTC, potiuk requested changes
I think both are wrong. This should be `${HOME}/.aws` where `${HOME}` is the home director of the user airflow is run with. We should not makea assumptions and asume that everyone uses the container image of Airflow - this is not true, there are many people who use Airflow just by installing it in  virtual machine, and use different user names, so assuming `/home/airflow` is not good.  There are also differences base on the the OS - for example on MacOS HOME is `/Users/<user_name`. I think `${HOME}` is the only universal and generic documentation we can have here.

2023-08-08 15:22 UTC, vincbeck approved these changes

2023-08-08 15:22 UTC, vincbeck commented
@potiuk Is it good now?

2023-08-08 16:43 UTC, potiuk approved these changes

2023-08-08 16:43 UTC, merged