Adding support for internalIpOnly to DataprocClusterCreateOperator
apache/airflow pull request #3458
Opened 2018-06-04 12:20 UTC by piffall

Make sure you have checked _all_ steps below.

### JIRA
- [ ] [AIRFLOW-2560](https://issues.apache.org/jira/browse/AIRFLOW-2560)

### Description
- [ ] Add support for GceClusterConfig.internalIpOnly for dataproc cluster creation.

### Tests
- [ ] Implementation of tests:

### Commits
- [ ] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
    - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality
- [ ] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

2018-06-05 09:02 UTC, kaxil requested changes

2018-06-05 09:02 UTC, kaxil commented on airflow/contrib/operators/dataproc_operator.py
> +    :param internal_ip_only: Restriction only available if subnetwork_uri is defined,
Can you add more details over here i.e. when would you use this parameter?

You can use the details over here:
https://cloud.google.com/dataproc/docs/reference/rest/v1/projects.regions.clusters#gceclusterconfig

>Optional. If true, all instances in the cluster will only have internal IP addresses. By default, clusters are not restricted to internal IP addresses, and will have ephemeral external IP addresses assigned to each instance. This internalIpOnly restriction can only be enabled for subnetwork enabled networks, and all off-cluster dependencies must be configured to be accessible without external IP addresses.

2018-06-05 09:02 UTC, kaxil commented on airflow/contrib/operators/dataproc_operator.py
> +                raise AirflowException("Set internal_ip_only to true is only valid"
Can you also please reword this? "Set `internal_ip_only` to true only when you pass a `subnetwork_uri `  ".

2018-06-05 09:02 UTC, kaxil commented on tests/contrib/operators/test_dataproc_operator.py
> +            self.assertEqual(cluster_data['config']['gceClusterConfig']['internalIpOnly'],
Can you also add tests to check the conditions when `internal_ip_only` is set without `subnetwork_uri` and see if it raises the exception or not?

2018-06-06 06:39 UTC, piffall commented
Hello @kaxil 
I think that I've fixed it all you comment. Thank you.

2018-06-06 09:02 UTC, kaxil commented on tests/contrib/operators/test_dataproc_operator.py
> +            # Guiven
Nit: typo

2018-06-06 09:08 UTC, kaxil requested changes

2018-06-06 09:08 UTC, kaxil commented on tests/contrib/operators/test_dataproc_operator.py
> +
Can you also just add another line to actually check if the Exception message contains "Set internal_ip_only to true only when you pass a subnetwork_uri."?

2018-06-06 09:08 UTC, kaxil commented on tests/contrib/operators/test_dataproc_operator.py
> +
Once that is done I think it can be merged.

2018-06-06 09:53 UTC, piffall commented
I think all is fixed. Waiting for test results.

2018-06-06 11:04 UTC, kaxil commented
@piffall  Please don't open-close the PR to re-trigger the build. We have been warned by the Apache Infra team for utilizing high resources for travis CI. Please do local testing or use docker. You can find instructions over here: https://github.com/apache/incubator-airflow/blob/master/CONTRIBUTING.md#development-and-testing

2018-06-06 11:09 UTC, piffall commented
@kaxil I'm sorry, I'll do local hereinafter.

2018-06-06 11:48 UTC, piffall commented
Hi again @kaxil , It seems that tests fails trivially on sqlite backend, caused by a system permission denied. It is possible to merge it without re-trigger the build to check all tests?
Thanks.

2018-06-06 11:50 UTC, kaxil commented
@piffall No worries. You don't need to apologize as you were unaware. :) Hope to merge this PR once it passes the tests.

One alternate approach is you can run Travis on your cloned Git Repo and just paste the link of the build over here. 👍

2018-06-06 12:04 UTC, kaxil approved these changes
LGTM

2018-06-06 12:07 UTC, closed without merging

2018-06-06 12:07 UTC, kaxil commented
Thank you for your contribution.