[AIRFLOW-1762] Implement key_file support in ssh_hook create_tunnel
apache/airflow pull request #3473
Opened 2018-06-07 10:45 UTC by NielsZeilemaker

Switched to using sshtunnel package instead of popen approach

Make sure you have checked _all_ steps below.

### JIRA
- [ ] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-1762
    - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a JIRA issue.

### Description
- [X] Here are some details about my PR, including screenshots of any UI changes:
The ssh_hook.create_tunnel was opening a tunnel using a popen. Moreover, it had the local port as a required argument. This PR refactored it to use the sshtunnel package build ontop of paramiko.

### Tests
- [X] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [X] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [] In case of new functionality, my PR adds documentation that describes how to use it.
    - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality
- [X] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

2018-06-09 20:29 UTC, Fokko requested changes
I have to take a deeper looks since this, but some quick observations:
- One thing that will break the API right now, is the removal of the `__enter__` and `__exit__` methods.
- I do like that the subprocess stuff is removed.
- Maybe add some documentation on the changes as well.
- I strongly feel we should have some actual tests here instead of only mocking. Since this is such an important operator.

The ssh is one of the most used hook/operator, so we have to be careful when making changes here.

2018-06-09 20:29 UTC, Fokko commented on setup.py
> +ssh = ['paramiko>=2.1.1', 'pysftp>=0.2.9', 'sshtunnel']
Maybe lock on a major version?

2018-06-09 20:29 UTC, Fokko commented on tests/contrib/hooks/test_ssh_hook.py
> +class SSHHookTest(unittest.TestCase):\
`\` typo?

2018-06-13 19:38 UTC, NielsZeilemaker commented
@Fokko I guess this one is ready to be merged. I put some effort in making it backwards compatible with the previous hook, and added some deprecation warnings etc.

2018-06-24 23:24 UTC, kaxil commented on airflow/contrib/hooks/ssh_hook.py
> +            client.connect(hostname=self.remote_host,
This would not work if the private key has passphrase. I tried to do that and it fail. Can you please add `key_filename=self.key_file` to this if statement as well? That worked for me and I don't want to create a separate PR if it can be sorted out here itself.

2018-06-25 13:59 UTC, NielsZeilemaker commented on airflow/contrib/hooks/ssh_hook.py
> +            client.connect(hostname=self.remote_host,
Hi kaxil, I added the key_file for both ssh and the tunnel. The SSHTunnel package has the same behaviour as paramiko and will also use the provided password for the key_file

2018-06-25 14:42 UTC, kaxil commented on airflow/contrib/hooks/ssh_hook.py
> +            client.connect(hostname=self.remote_host,
Thanks @NielsZeilemaker 👍

2018-07-21 12:29 UTC, kaxil commented
Can you please resolve the conflicts?

2018-07-21 12:47 UTC, NielsZeilemaker commented
I'll have a go at it on Monday.

2018-07-23 08:12 UTC, NielsZeilemaker commented
@kaxil I've fixed the conflicts

2018-07-23 23:59 UTC, kaxil commented
Codewise this looks good to me. @Fokko Can you also please have a look and see if you have some comments?

2018-07-24 07:27 UTC, Fokko approved these changes
LGTM, but please remove the print statements from the tests.

2018-07-24 07:27 UTC, Fokko commented on tests/contrib/hooks/test_ssh_hook.py
>          print("Setting up tunnel")
Can your remove the print statements please?

2018-07-24 08:44 UTC, Fokko approved these changes
@NielsZeilemaker Thanks! merging

2018-07-24 08:44 UTC, closed without merging