Combined the `in_container_utils.sh with run_docs_build.sh
apache/airflow pull request #35192
Opened 2023-10-26 07:21 UTC by KesharwaniArpita

Combined the `in_container_utils.sh with run_docs_build.sh` to eliminate the dependency of the latter on the former in relation with the issue #26019 . The file is still in bash which will be converted to `.py` files once modified and approved.

2023-10-26 07:37 UTC, potiuk commented
I do not think this is needed at alll

1) even if that script includes the common file - it does not seem to use any of it so at most i'd just **REMOVE** using the common script (and test it as well) 

2) This "run_docs_build.sh" simply executes python command and hardly does anything else. I do not think we should rewrite it. We should only rewrite scripts that contain some complex-ish logic in it. Having a script that is just wrapping execution of python command to simplify setting environment variables etc. seems like a legitimate use of bash script IMHO.

2023-10-26 07:39 UTC, potiuk requested changes
It's pretty much not what the inteion of rewriting the bash scripts is about

2023-10-29 07:20 UTC, KesharwaniArpita commented
Do you think, `run_generate_constraints.sh` can be a good candidate?

2023-10-29 13:38 UTC, potiuk commented
> Do you think, `run_generate_constraints.sh` can be a good candidate?

Yes. I'd say there are three good candidates. In order of complexity from simplest to most comples:

* check_environment.sh
* run_generate_constraints.sh
* run_prepare_provider_packages.sh

2023-11-03 13:55 UTC, KesharwaniArpita commented
@potiuk 
@amoghrajesh 
Your suggestions, Please?

2023-11-03 16:26 UTC, potiuk commented
I think you realy "included" the whole script there, which was not the intention of my proposal - just leave whatever is needed in the target script - there is really little value in copying code that is not really used - you need to just leave there what is "really used"  (which is almost nothing ig you look at the code).

2023-11-03 16:28 UTC, potiuk commented on scripts/in_container/run_docs_build.sh
> +
Almost all of it can be removed as it is not used + there are some left-overs (like shellcheck above) that are not needed any more

2023-11-03 16:28 UTC, potiuk commented on scripts/in_container/run_anything.py
> +#!/usr/bin/env python
Do we need that?

2023-11-03 16:46 UTC, potiuk commented on scripts/in_container/check_environment.sh
> +        if [ -z "${FILES_DIR+x}" ]; then
I am not sure if in this case it's worth incorporating check environment in. What I really meant to is ratheer to rewrite the configure_environment.sh and run it from here. It makes little sense to increase duplication of the check_environment.sh into other scripts

2023-11-16 04:36 UTC, amoghrajesh requested changes
I am a little confused with the intention of this PR. The title vs the changes makes it confusing. 

From what I understand, the task was to rewrite: check_environment.sh into python. 
Instead of changing multiple files at once, we should go small and step by step in my opinion. Make changes to check_environment.sh for instance and test it well.

2023-11-16 06:15 UTC, KesharwaniArpita commented
OKAY!

2024-01-08 00:12 UTC, closed without merging