Add support for adding securityContext in the initContainer of the da…
apache/airflow pull request #35593
Opened 2023-11-12 21:52 UTC by shohamy7

---
This PR resolve this issue #34595 
closes: #34595

2023-11-13 17:24 UTC, jedcunningham requested changes
Looks good. Can you also add to `values.schema.json`, like [this](https://github.com/apache/airflow/blob/4cc98ba6648b4a350f9093c4e22ad6cff87ac5e4/chart/values.schema.json#L2603-L2628)?

2023-11-13 20:13 UTC, shohamy7 commented
looks like it is already implemented

2023-11-14 00:19 UTC, jedcunningham approved these changes

2023-11-14 00:21 UTC, merged

2023-11-14 00:22 UTC, jedcunningham commented
Thanks @shohamy7! Congrats on your first commit 🎉