Allow raising error if ``DagRun`` fails when running ``dag test``
apache/airflow pull request #36517
Opened 2023-12-31 16:53 UTC by kaxil

**Motivation**:

Currently, when using `airflow dags test`, there is no easy way to know programmatically if a DagRun fails since the state is not stored in DB. The way to do know relies on log lines as below:

```bash
state=$(airflow dags test exception_dag | grep "DagRun Finished" | awk -F, '{for(i=1;i<=NF;i++) if ($i ~ / state=/) print $i}' | awk -F= '{print $2}') if [[ $state == "failed" ]]; then exit 1 else exit 0 fi
```

This PR adds `--fail-on-dagrun-failure` flag to `airflow dags test` command which will return an exit code of 1 if DagRun fails and makes it easy to integrate in CI for testing.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

2023-12-31 18:30 UTC, potiuk approved these changes

2023-12-31 19:06 UTC, jscheffl requested changes
I am a bit wondering why we add another CLI parameter. If the DAG test fails and exit code 0 is returned I'd rather see this as a bug.

Is there a reason adding a new CLI param? Please convince me. Else it would even be leaner w/o additional parameter

2024-01-01 06:06 UTC, dirrao commented
> I am a bit wondering why we add another CLI parameter. If the DAG test fails and exit code 0 is returned I'd rather see this as a bug.
> 
> Is there a reason adding a new CLI param? Please convince me. Else it would even be leaner w/o additional parameter

I agree with @jscheffl. The default behavior of the cli command should be the status of the DAG run/runs.

2024-01-01 09:21 UTC, potiuk commented
Once concern is backwards compatibility (and I think that's where @kaxil's solution came from).

But yeah, I think you are right @jscheffl @dirrao - probably return value is not **teally** compatibility  promise (and we can treat it as bugfix). We've already done the same in https://github.com/apache/airflow/pull/35378 (and It was me who proposed skipping the flag and treating it as bugfix :D ... Now I remember .

2024-01-01 10:36 UTC, jscheffl commented
> Once concern is backwards compatibility (and I think that's where @kaxil's solution came from).
> 
> But yeah, I think you are right @jscheffl @dirrao - probably return value is not **teally** compatibility promise (and we can treat it as bugfix). We've already done the same in #35378 (and It was me who proposed skipping the flag and treating it as bugfix :D ... Now I remember .

So if we had it two times already would be even a good "quality excercise" to double check that all CLI commands exit with a proper error code in case of error :-D

2024-01-02 10:00 UTC, kaxil commented
>I am a bit wondering why we add another CLI parameter. If the DAG test fails and exit code 0 is returned I'd rather see this as a bug.

Yeah I tried to think more on it to keep backwards-compat but I think we are ok -- will remove the param and make it the default behavior

2024-01-02 10:04 UTC, kaxil commented
@jscheffl Done

2024-01-02 10:19 UTC, jscheffl approved these changes
Thanks for the fix!

2024-01-02 10:38 UTC, merged

2024-01-02 10:40 UTC, kaxil commented
The failed test is unrelated to the PR and succeeds locally:

```
=========================== short test summary info ============================
FAILED tests/cli/test_cli_parser.py::TestCliSubprocess::test_airflow_config_contains_providers - AssertionError: assert 'celery_config_options' in ''
 +  where '' = <bound method Path.read_text of PosixPath('/root/airflow/airflow.cfg')>()
 +    where <bound method Path.read_text of PosixPath('/root/airflow/airflow.cfg')> = PosixPath('/root/airflow/airflow.cfg').read_text
===== 1 failed, 304 passed, 1050 skipped, 1 xfailed, 9 warnings in 18.30s ======

```