prevent celery command autoscale misconfig
apache/airflow pull request #36576
Opened 2024-01-04 05:56 UTC by Bowrna

closes: #35332 
related: #35332 

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

2024-01-04 08:11 UTC, dirrao requested changes
Static checks are failing. I would request you to use pre commit hooks or breeze CLI static checks.
https://github.com/apache/airflow/blob/main/STATIC_CODE_CHECKS.rst#:~:text=available%20bash%20scripts.-,Pre%2Dcommit%20hooks,on%20and%20make%20them%20fast.

2024-01-04 08:11 UTC, dirrao commented on airflow/cli/commands/celery_command.py
> +
```suggestion
    max_worker, min_worker = [int(x) for x in autoscale.split("-")]
    if min_worker > max_worker:
          raise SystemExit("The option for worker autoscale should be max_concurrency,min_concurrency")
```
This validation should be done for default configuration as well.

2024-01-05 04:26 UTC, dirrao requested changes
Existing test cases are failing. Can you update the existing ones and add the new test case?

2024-01-05 11:00 UTC, Bowrna commented
hi @dirrao yes the static checks are expected to fail. I will need response for this comment https://github.com/apache/airflow/issues/35332#issuecomment-1876874115 to proceed further with this.

2024-01-28 18:43 UTC, Bowrna commented
i have fixed some parts in documentation alone here in this PR. The actual issue is not an issue and therefore I just enhanced the docs alone

2024-01-28 19:17 UTC, potiuk approved these changes

2024-01-28 19:17 UTC, merged