Update public interface doc re operators
apache/airflow pull request #36767
Opened 2024-01-14 01:44 UTC by dstandish

Base classes such as BaseOperator and BaseSensorOperator are public in the traditional sense.  We publish them explicitly for the purpose of being extended.

But I think that derivatives of them are published only as end products, in that their behavior and signature should be subject to semver, but not their structure, which should be considered "internal" and not user-facing.  Users can extend these classes but they should do so at their own risk, with the knowledge that we might refactor.  Otherwise the "public interface" is just unreasonably big.

2024-01-14 09:27 UTC, potiuk approved these changes
LGTM.  The original text was far too long and detailed anyway.

2024-01-14 09:28 UTC, potiuk commented
Some spellchecking :)/build errors.

2024-01-14 10:10 UTC, dirrao requested changes
Some doc checks are failing. can you check and fix them?

2024-01-14 10:37 UTC, Taragolis commented on docs/apache-airflow/public-airflow-interface.rst
> +Subclasses of BaseOperator which are published in Apache Airflow are public in behavior but not in structure.  That is to say, the Operator's parameters and behavior is governed by semver but the met
It feels like the last sentence was cut off in the middle.

2024-01-15 08:09 UTC, eladkal commented
> Otherwise the "public interface" is just unreasonably big.

Might be but it does not limit us with providers.
It doesn't cost us anything to make a major release for the sake of clarity.

I am very OK with the approach you suggest to simplify things but I do think we should consider as part of the clarification to adding note in change log that we "break" something.

2024-01-15 08:10 UTC, eladkal approved these changes

2024-01-15 08:11 UTC, eladkal commented on docs/apache-airflow/public-airflow-interface.rst
> +Subclasses of BaseOperator which are published in Apache Airflow are public in behavior but not in structure.  That is to say, the Operator's parameters and behavior is governed by semver but the met
yes

2024-01-15 11:42 UTC, amoghrajesh approved these changes
Looks about right, pending suggestion from @Taragolis and green build

2024-01-15 15:42 UTC, vincbeck approved these changes

2024-01-16 16:29 UTC, dstandish commented
> > Otherwise the "public interface" is just unreasonably big.
> 
> Might be but it does not limit us with providers. It doesn't cost us anything to make a major release for the sake of clarity.

@eladkal it's a good point.  I do see how the major release can be helpful with messaging that.

However, I do also think it potentially dilutes the meaning of the major release.  If we create a major release every time we rename some internal method, then user the major release is diminished as a signal of when there's an actual breaking change in behavior of the operator.  So, in this way I think we can see a benefit to "reserving" the major release for chose behavior changes.

It also does add a little friction when it comes to refactors and such when there's a method rename involved.

All of that having been said, do you think this should go to the mailing list?

2024-01-16 18:15 UTC, potiuk commented
> Nop. We can just add disclaimer that release manager have descrtion on the matter when we do release cut.

I strongly believe this should be the case. P

eople often mix the "method parameter name, or renaming the method" as being a sign of breaking change in SemVer. It's not as easy and straightforward - I will keep on repeating it. SemVer does not define that adding or removing a parameter is /is not breaking. They leave to discretion of those who define the AP  and we are pretty free to define our API as we see fit - mostly taking into account the usage patterns we `expect` our users will have. 

And it is really hard and borderline impossible to define it

a) comprehensively enough
b) in a non-ambiguous way (which can be interpreted in various ways)

As Hyrum's law (correctly IMHO) says - in a complex change pretty much any change is breaking someone's workflow. It's up to us to assess if such change is "breaking enough" to be classified as such. We shoudl communicate our intentions to our users and in case of doubt interpret and classify the changes by human - who can make a jugment, not by code that tells it objectively breaking/not breaking. At the end SemVer is about intentions, not about renaming methods.

2024-01-18 13:02 UTC, dirrao approved these changes

2024-01-19 17:51 UTC, merged