feat: Fall back to datasets' "extra" if arg extra is empty
apache/airflow pull request #37491
Opened 2024-02-16 17:40 UTC by ZhengLin-Li

fix: https://github.com/apache/airflow/issues/37006

Fall back to datasets' "extra" if arg extra is empty

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

2024-02-16 19:26 UTC, hussein-awala reviewed
Could you add a test for this change?

2024-02-16 23:27 UTC, ZhengLin-Li commented
@hussein-awala Thanks for your review. I have added some test cases.

2024-02-17 00:43 UTC, jedcunningham commented on airflow/datasets/manager.py
Personally, I don't think the dataset extra is a good fallback for a dataset event's extra. I see those extras as being different.

2024-02-17 02:26 UTC, dirrao requested changes
Looks like extras are reserved for future use. May be its worth to pass information about partition.

2024-03-05 10:22 UTC, closed without merging