Fix BigQueryTablePartitionExistenceTrigger partition query
apache/airflow pull request #37655
Opened 2024-02-23 15:19 UTC by Silviu-Surcica

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

2024-02-24 03:33 UTC, dirrao requested changes
Can you add the test cases for this change?

2024-03-06 09:21 UTC, Silviu-Surcica commented
@dirrao can you review this or add another reviewer ? Thank you!

2024-03-06 13:27 UTC, moiseenkov approved these changes

2024-03-06 16:58 UTC, eladkal approved these changes

2024-03-06 16:59 UTC, merged