Modify ssl verification in druid operator
apache/airflow pull request #37673
Opened 2024-02-24 11:52 UTC by danielbe11

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

2024-02-25 02:45 UTC, dirrao requested changes
Can you add the test case for this change?

2024-02-26 06:28 UTC, danielbe11 commented
@dirrao the backwards compatibility and get_verify methods are tested, I will add a small test for 'conn' method today

2024-02-26 09:35 UTC, danielbe11 commented
> @dirrao the backwards compatibility and get_verify method are tested, I will add a small test for 'conn' method today

I have added `test_conn_property`

2024-03-03 07:46 UTC, eladkal approved these changes

2024-03-03 07:46 UTC, merged