[OpenLineage] feat: Add OpenLineage support for File lineage entity as inlet/outlet
apache/airflow pull request #37744
Opened 2024-02-27 12:30 UTC by kacpermuda

When using inlets/outlets with OpenLineage, only Table entity was supported (without schema). This PR adds support for Table's schema and File entity.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

2024-02-28 03:28 UTC, dirrao requested changes
I believe good to add example DAG.

2024-02-28 08:38 UTC, kacpermuda commented
> I believe good to add example DAG.

There is one [here](https://openlineage.io/docs/integrations/airflow/manual#example), and also when #37620 is merged, it will be in provider docs - then I'll update the information, that the File is also supported 😉

2024-02-28 14:14 UTC, mobuchowski approved these changes

2024-02-29 09:47 UTC, kacpermuda commented
I added support for File, Column and User entities and adjusted the documentation to reflect that change. It should be good to go now 🚀

2024-02-29 10:40 UTC, merged