[AIRFLOW-XXX] Refine web UI authentication-related docs
apache/airflow pull request #3863
Opened 2018-09-07 14:50 UTC by XD-DENG

Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-XXX
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

Now in Airflow 1.10 we're already providing older version of web UI and new FAB-based UI at the same time. But the documentation is not differentiated very well. For example,
- this doc https://airflow.apache.org/security.html#password is only applicable for old web UI only, but it's not hightlighted.
- command line tool `create_user`  is only for new FAB-based UI only, it's not highlighted as well.

This may be confusing to users, especially given not everyone is aware of the existence of two UIs.

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
Doc change only

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

2018-09-09 23:22 UTC, XD-DENG commented
Hi @kaxil , may you take a look? Thanks!

2018-09-15 03:23 UTC, XD-DENG commented
Hi @kaxil , a gentle ping. This PR may be help make the authentication-related docs clearer, especially given we have two UIs available concurrently at this moment.

2018-09-15 16:27 UTC, kaxil requested changes

2018-09-15 16:27 UTC, kaxil commented on docs/security.rst
> +uses `bcrypt` before storing passwords.
You need two double back-ticks for highlighting in Sphinx

```
``bcrypt``
```

2018-09-15 16:27 UTC, kaxil commented on docs/security.rst
> +   please use command line interface `create_user` to create accounts, or do that in the FAB-based UI itself.
You need two double back-ticks for highlighting in Sphinx

```
``create_user ``
```

2018-09-15 16:27 UTC, kaxil commented on docs/security.rst
> +   please use command line interface `create_user` to create accounts, or do that in the FAB-based UI itself.
For multiline `note`:
```
.. note::

   This is for older version of the web UI only. If you are using FAB-based web UI with RBAC feature,
   please use command line interface `create_user` to create accounts, or do that in the FAB-based UI itself.
```

2018-09-15 16:27 UTC, kaxil commented on docs/security.rst
> +   please use command line interface `create_user` to create accounts, or do that in the FAB-based UI itself.
Instead of `older version of web UI`, I would call it `flask-admin based Web UI`

2018-09-15 16:42 UTC, XD-DENG commented
Thank you @kaxil for providing your inputs.

I have addressed accordingly. Kindly take another look. Thanks.

2018-09-15 16:58 UTC, kaxil commented
Can you also create a Jira issue? Any change that spans more than 1 line should have a jira.

2018-09-16 01:30 UTC, XD-DENG commented
Hi @kaxil , sorry I though no ticket is required as long as it's only documentation change.

I have raised a JIRA ticket (https://issues.apache.org/jira/browse/AIRFLOW-3070) and updated the PR subject, PR message body, and commit msg subject accordingly.

Thanks.

2018-09-16 12:35 UTC, kaxil approved these changes
LGTM.

2018-09-16 12:38 UTC, kaxil commented
@XD-DENG Hey, No worries :-) . The idea behind there is no point in creating a Jira where we are just fixing typos or a single line document change. Everything other than that should have a Jira :) 

Really appreciate all of your contributions. Keep contributing 🎉  and thanks for this PR as well.

2018-09-16 12:38 UTC, merged

2018-09-16 13:51 UTC, XD-DENG commented
Thanks @kaxil . Appreciate the time you guys contributed as well. Especially now, a Sunday :) 

A nice afternoon ahead.