[AIRFLOW-3103] Update flask-login.
apache/airflow pull request #3937
Opened 2018-09-23 03:54 UTC by jmcarp

Note: depends on https://github.com/dpgaspar/Flask-AppBuilder/pull/811 being merged and released, at which point we'll also bump `flask-appbuilder` in `setup.py`.

Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/issues/AIRFLOW-3103) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-XXX
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.

### Description

- [ ] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [ ] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

2018-09-23 04:15 UTC, jmcarp commented
Build failures expected until flask-appbuilder is updated.

2018-10-03 14:02 UTC, ashb commented
FAB has been released, am re-running the tests to see if they pass.

2018-10-03 15:02 UTC, ashb commented
@jmcarp Looks like something else needs an update:

```
   AttributeError: <module 'flask_login' from '/app/.tox/py27-backend_mysql-env_docker/local/lib/python2.7/site-packages/flask_login/__init__.pyc'> does not have the attribute '_get_user'
```

2018-10-03 16:32 UTC, ashb commented on setup.py
> +            'flask-appbuilder>=1.12, <2.0.0',
Could you add `[AIRFLOW-3147]` in to your commit message too please?

2018-10-03 16:33 UTC, ashb commented on tests/www/test_utils.py
> +    @mock.patch("flask_login.utils._get_user")
Thanks -I see what I did wrong and came to fix it to find you'd done it already :)

2018-10-03 16:40 UTC, ashb commented
You need this too:

```
diff --git a/tests/www_rbac/test_security.py b/tests/www_rbac/test_security.py
index 67ea5b30..6e0b5726 100644
--- a/tests/www_rbac/test_security.py
+++ b/tests/www_rbac/test_security.py
@@ -109,7 +109,7 @@ class TestSecurity(unittest.TestCase):

     def test_get_user_roles(self):
         user = mock.MagicMock()
-        user.is_anonymous.return_value = False
+        user.is_anonymous = False
         roles = self.appbuilder.sm.find_role('Admin')
         user.roles = roles
         self.assertEqual(self.security_manager.get_user_roles(user), roles)
@@ -144,7 +144,7 @@ class TestSecurity(unittest.TestCase):
         self.security_manager.init_role(role_name, role_vms, role_perms)
         role = self.security_manager.find_role(role_name)
         user.roles = [role]
-        user.is_anonymous.return_value = False
+        user.is_anonymous = False
         mock_get_all_permissions_views.return_value = {('can_dag_read', 'dag_id')}

         mock_get_user_roles.return_value = [role]
@@ -154,7 +154,7 @@ class TestSecurity(unittest.TestCase):
     @mock.patch('airflow.www_rbac.security.AirflowSecurityManager._has_view_access')
     def test_has_access(self, mock_has_view_access):
         user = mock.MagicMock()
-        user.is_anonymous.return_value = False
+        user.is_anonymous = False
         mock_has_view_access.return_value = True
         self.assertTrue(self.security_manager.has_access('perm', 'view', user))
```

2018-10-03 16:42 UTC, feng-tao commented
Cool. Great to see this pr :)

2018-10-03 16:44 UTC, ashb requested changes
Could you also please add this section to the UPDATING.md:

```
### Custom auth backends interface change

We have updated the version of flask-login we depend upon, and as a result any
custom auth backends might need a small change: `is_active`,
`is_authenticated`, and `is_anonymous` should now be properties. What this means is if
previously you had this in your user class

    def is_active(self):
      return self.active

then you need to change it like this

    @property
    def is_active(self):
      return self.active

```

2018-10-03 23:31 UTC, feng-tao commented
@ashb , I think this pr is ready. And it needs to be checked in to unblock the CI.

2018-10-04 07:20 UTC, merged