Workaround for asyncio cancelled error for DataprocCreateClusterOperator
apache/airflow pull request #39446
Opened 2024-05-06 20:05 UTC by sunank200

[PR #39130](https://github.com/apache/airflow/pull/39130) introduces a method for handling asyncio.CancelledError in a try/except block. However, this method is deemed unsafe, and it affects `DataprocCreateClusterOperator` operators, which enables external job cancellation if the triggerer restarts or crashes. This can cause weird behaviour like rescheduling deferred operators, as Airflow remains unaware of job cancellations. 

As a workaround, capturing `asyncio.CancelledError` cancels the job only if the TaskInstance is not in a running or deferred state. This prevents premature external job termination.

More details at: https://github.com/apache/airflow/issues/36090#issuecomment-2094972855

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

2024-05-07 08:48 UTC, Lee-W commented
Just have a quick discussion with @sunank200. We'll yield the event if CancelError was raised , and handle the TaskInstance state check and cancelation in `execute_complete`

2024-05-07 10:24 UTC, sunank200 commented
> Just have a quick discussion with @sunank200. We'll yield the event if CancelError was raised , and handle the TaskInstance state check and cancelation in `execute_complete`

That won't work as the `execute_on_complete` won't be called when the task is cancelled. I have used task_instance from `BaseTrigger` instead.

2024-05-07 10:26 UTC, Lee-W approved these changes
We probably should add a test to this. But others look good to me

2024-05-07 10:47 UTC, dirrao commented on airflow/providers/google/cloud/triggers/dataproc.py
> +    def safe_to_cancel(self) -> bool:
When it is reattempted, does this attached to the existing external job or will it create new job?

2024-05-07 10:47 UTC, dirrao requested changes
Can you add the test case for this change?

2024-05-07 13:26 UTC, sunank200 commented on airflow/providers/google/cloud/triggers/dataproc.py
> +    def safe_to_cancel(self) -> bool:
It attaches to an existing job that is triggered in the instance when it reattempts

2024-05-07 14:51 UTC, Lee-W commented on airflow/providers/google/cloud/triggers/dataproc.py
> +        return task_instance.state != TaskInstanceState.DEFERRED
I feel like we probably could make this check through SQL 🤔

2024-05-07 14:51 UTC, Lee-W commented on airflow/providers/google/cloud/triggers/dataproc.py
> +        return task_instance.state != TaskInstanceState.DEFERRED
not really a blocker, but is an optimization we should do eventually

2024-05-07 14:53 UTC, Lee-W reviewed
Left a short nitpick. We could create an issue and work on that later, but we'll need test cases for this PR

2024-05-07 15:20 UTC, sunank200 commented on airflow/providers/google/cloud/triggers/dataproc.py
> +        return task_instance.state != TaskInstanceState.DEFERRED
I can create a separate PR for the optimization

2024-05-07 16:28 UTC, sunank200 commented
> Can you add the test case for this change?

Added the test.

2024-05-08 05:45 UTC, pankajkoti approved these changes

2024-05-08 07:42 UTC, merged