remove deprecations mssql
apache/airflow pull request #39734
Opened 2024-05-21 07:21 UTC by Bowrna

Related: #39485
Removing deprecated MsSqlOperator from docs and tests and replacing with SQLExecuteQueryOperator

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

2024-05-21 13:15 UTC, dirrao approved these changes
LGTM

2024-05-21 19:38 UTC, RNHTTR requested changes
I think this should refer to the SQLExecuteQueryOperator?

2024-05-21 19:38 UTC, RNHTTR commented on docs/apache-airflow-providers-microsoft-mssql/operators.rst
> +To use the mssql operator to carry out SQL request, two parameters are required: ``sql`` and ``conn_id``.
```suggestion
To use the SQLExecuteQueryOperator to execute SQL queries against an MSSQL database, two parameters are required: ``sql`` and ``conn_id``.
```

2024-05-22 00:28 UTC, Bowrna commented on docs/apache-airflow-providers-microsoft-mssql/operators.rst
> +To use the mssql operator to carry out SQL request, two parameters are required: ``sql`` and ``conn_id``.
yes @RNHTTR

2024-05-22 09:08 UTC, Taragolis approved these changes

2024-05-22 12:41 UTC, RNHTTR approved these changes

2024-05-24 18:31 UTC, vincbeck approved these changes

2024-05-24 18:31 UTC, vincbeck commented
Please resolve conflict

2024-06-01 08:20 UTC, Bowrna commented
I have resolved the conflicts in this PR

2024-06-01 09:57 UTC, potiuk approved these changes

2024-06-01 09:57 UTC, merged