Bump google-ads version
apache/airflow pull request #40079
Opened 2024-06-05 22:41 UTC by molcay

Update the version of `google-ads` library

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

2024-06-06 09:25 UTC, ahidalgob commented
Hi, is this because of a new API version? should we update also the `default_api_version` in `GoogleAdsHook`?

2024-06-06 11:47 UTC, potiuk approved these changes

2024-06-06 11:50 UTC, potiuk requested changes
Requesting changes here -  yeah, we need to know the reason for that bump? Similarly to https://github.com/apache/airflow/pull/40073 - we generally do not bump deps unless we have a reason for it.

2024-06-07 09:46 UTC, molcay commented
Hi @ahidalgob,
> Hi, is this because of a new API version?

Yes, we have a new API version on Google Ads.

> should we update also the `default_api_version` in `GoogleAdsHook`?

Since it is a minor version upgrade this is not possible. Otherwise, we are also updating the `default_api_version` variable.

But it seems like we already have a new version (which is a major version upgrade): v17 https://developers.google.com/google-ads/api/docs/sunset-dates

Hi @potiuk,
The Google Ads API tends to be deprecated too quickly. So we are trying to keep up by upgrading the API versions preemptively. Actually, there is already a new version v17 and this version(v16.1) marked as deprecated. Here is the link for the version's timetable: https://developers.google.com/google-ads/api/docs/sunset-dates

So I think this PR can close without merge I will prepare a new PR with the new API version.

2024-06-07 09:46 UTC, closed without merging

2024-06-07 09:55 UTC, potiuk commented
> So I think this PR can close without merge I will prepare a new PR with the new API version.

Yeah. Thanks for the context. Agree. Seems like Google Ads should be bumped earlier rather than later :)

2024-06-10 11:52 UTC, molcay commented
Yes, definitely. I created the v17's PR already :)