[AIRFLOW-2744] Allow RBAC to accept plugins for views and links.
apache/airflow pull request #4036
Opened 2018-10-11 15:01 UTC by oliviersm199

### Description

Airflow Users that wish to create plugins for the new www_rbac UI can not add plugin views or links. This PR fixes that by letting a user specify their plugins for www_rbac and maintains backwards compatibility with the existing plugins system.

Adds two additional members of an AirflowPlugin class to cover role based views and role based menu items. Specifies that the user can create a dictionary which has the metadata necessary to create a FlaskAppBuilder BaseView or MenuItem. This lets the plugins manager extend to the new www_rbac GUI.

### Tests

Adds unit tests under the plugins manager to test that the www_rbac views and menu links get added successfully.

### Documentation

Demonstrates in the plugins page how a user would create plugins for the new UI with an example.

2018-10-11 15:08 UTC, ashb reviewed
Nice!

2018-10-11 15:08 UTC, ashb commented on airflow/plugins_manager.py
> +    role_based_menu_items = []
Lets call these `appbuilder_views` etc. The "role" is just the reason we switched to FAB.

2018-10-11 16:24 UTC, oliviersm199 commented on airflow/plugins_manager.py
> +    role_based_menu_items = []
Changed it to use appbuilder_views etc.

2018-10-12 00:31 UTC, oliviersm199 commented
not sure why the code coverage has changed so drastically, I added some test cases but it looks like the hits and misses are changing abnormally? Did I miss something?

2018-10-12 04:15 UTC, Fokko commented
@oliviersm199 It could be that you've worked from an old master.

2018-10-12 04:18 UTC, Fokko commented
@jgao54 Any thoughts on this? :)

2018-10-12 13:56 UTC, oliviersm199 commented
Yes merging in master helped fix the code coverage report! Thank you @Fokko.

2018-10-15 16:45 UTC, oliviersm199 commented
Hello have the core committers had time to look at this? I know @Fokko requested input from @jgao54, let me know if you need anything from me.

2018-10-22 09:15 UTC, felipegasparini commented
hey guys,

is there any ETA for this PR?

2018-10-23 09:24 UTC, ashb requested changes
Few minor nits then this looks good to merge.

2018-10-23 09:24 UTC, ashb commented on tests/plugins/test_plugin.py
> +    static_url_path="/static/test_plugin")
Style nit: please remove un-related changes like this from the PR.

2018-10-23 09:24 UTC, ashb commented on tests/plugins/test_plugin.py
> +    @expose("/")
Style nit: please remove un-related changes like this from the PR.

2018-10-23 09:24 UTC, ashb commented on docs/plugins.rst
> +
Remove empty lines.

2018-10-23 09:24 UTC, ashb commented on docs/plugins.rst
> +AirflowTestPlugin class were added for specifically adding views and links to FlaskAppBuilder.
Please say here what the fields are.

2018-10-23 09:24 UTC, ashb commented on docs/plugins.rst
> +-------
The `-----` should match the length of the line above otherwise RST will complain at us.

2018-10-23 14:13 UTC, oliviersm199 commented
Made the requested changes.

2018-10-23 14:22 UTC, ashb commented on docs/plugins.rst
> +-------
This one still needs doing I think?

2018-10-23 14:34 UTC, oliviersm199 commented on docs/plugins.rst
> +-------
Hey I thought I changed it but must have made a mistake with git. Please check again :)

2018-10-23 14:39 UTC, ashb approved these changes

2018-10-23 15:25 UTC, ashb commented
Tests failed due to flake8 style violation:

> ./tests/plugins/test_plugin.py:96:33: E261 at least two spaces before inline comment

2018-10-23 15:35 UTC, ashb commented on tests/plugins/test_plugin.py
> +    template_folder='templates', # registers airflow/plugins/templates as a Jinja template folder
This double space is required by flake8.

2018-10-23 16:21 UTC, merged

2018-10-25 18:30 UTC, c4milo commented
@ashb would it be possible to backport this PR into 1.10.x? It would be ideal for us.

2018-10-26 08:58 UTC, ashb commented
@c4milo yeah it will be in 1.10.1 - check the "Fix Version" on a Jira to see what will be back-ported https://issues.apache.org/jira/browse/AIRFLOW-2744

2019-01-07 21:46 UTC, feng-tao commented
@oliviersm199 , it seems that PluginRBACTest fails(currently it is disabled) if re-enable. Do you think you have time to fix the test?

2019-01-07 23:00 UTC, felipegasparini commented
We also need to fix the example in the documentation (https://airflow.apache.org/plugins.html#example). It is currently broken: import fails, wrong method name in the view and missing path for templates.

I made a sample project to make this plugin integration work: https://github.com/felipegasparini/airflow_plugin_rbac_test/blob/dbaa049a9996df275b1d90f74b93ffbf206bb1d5/airflow/plugins/test_plugin/test_plugin.py

I will submit a PR to fix the doc later, but just posting it here since it may be useful for others.