[AIRFLOW-1970] Let empty Fernet key or special `no encryption` phrase.
apache/airflow pull request #4038
Opened 2018-10-11 22:41 UTC by exploy

### Jira

My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW-1970) issues and references them in the PR title. 

### Description

Once the user has installed Fernet package then the application enforces setting valid Fernet key.
This change will alter this behavior into letting empty Fernet key or special `no encryption` phrase and interpreting those two cases as no encryption desirable.

### Tests

My PR adds no tests as of now.

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":

### Code Quality

- [ ] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

2018-10-12 04:24 UTC, Fokko requested changes
Maybe add this to the docs as well? https://github.com/apache/incubator-airflow/blob/master/docs/howto/secure-connections.rst

2018-10-12 04:24 UTC, Fokko commented on airflow/models.py
> +    no_encryption_phrase = \
Why this `no_encryption_phrase`. If you don't want to use Fernet encryption, omitting the key would make more sense to me, instead of setting it to a value like `cryptography_not_found_storing_passwords_in_plain_text`. Maybe get rid of this logic?

2018-10-12 08:06 UTC, ashb commented on airflow/models.py
> +    no_encryption_phrase = \
This is the value that airflow.configuration renders in to the template. That constant (if we keep it, vs just commenting out the file and using an empty string) should be shared/imported between both modules

2018-10-12 12:19 UTC, Fokko commented on airflow/models.py
> +    no_encryption_phrase = \
Ah I see, returning `None` instead of `cryptography_not_found_storing_passwords_in_plain_text` would be my preference as well

2018-10-26 11:18 UTC, exploy commented
@Fokko I made the change to the docs. Would you take a look?

2018-10-26 11:51 UTC, exploy commented
If someone can restart tests on Travis I'd be very grateful. Looks like one combination failed which looks like random error

2018-10-26 12:28 UTC, Fokko approved these changes
Thanks @exploy Looks good! 👍

2018-10-26 12:29 UTC, merged

2018-10-26 12:36 UTC, exploy commented
@Fokko gr8 thx!