Adding Paypal. We use airflow in ML Platform.
apache/airflow pull request #42174
Opened 2024-09-11 19:00 UTC by kaddynator

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

2024-09-11 19:04 UTC, kaddynator commented
@RNHTTR !

2024-09-11 19:07 UTC, RNHTTR requested changes

2024-09-11 19:07 UTC, RNHTTR commented on INTHEWILD.md
> +1. [PayPal](https://www.paypal.com/)  [@kaddynator](https://github.com/kaddynator)], [[@r39132](https://github.com/r39132) & [@jhsenjaliya](https://github.com/jhsenjaliya)]
```suggestion
1. [PayPal](https://www.paypal.com/)  [[@kaddynator](https://github.com/kaddynator)], [@r39132](https://github.com/r39132) & [@jhsenjaliya](https://github.com/jhsenjaliya)]
```

2024-09-11 19:19 UTC, RNHTTR requested changes

2024-09-11 19:19 UTC, RNHTTR commented on INTHEWILD.md
> +1. [PayPal](https://www.paypal.com/)  [[@kaddynator](https://github.com/kaddynator)], [@r39132](https://github.com/r39132) & [@jhsenjaliya](https://github.com/jhsenjaliya)]
```suggestion
1. [PayPal](https://www.paypal.com/)  [[@kaddynator](https://github.com/kaddynator), [@r39132](https://github.com/r39132) & [@jhsenjaliya](https://github.com/jhsenjaliya)]
```

2024-09-11 19:39 UTC, jedcunningham commented on INTHEWILD.md
> +1. [PayPal](https://www.paypal.com/)  [[@kaddynator](https://github.com/kaddynator)], [@r39132](https://github.com/r39132) & [@jhsenjaliya](https://github.com/jhsenjaliya)]
```suggestion
1. [PayPal](https://www.paypal.com/) [[@kaddynator](https://github.com/kaddynator)], [@r39132](https://github.com/r39132) & [@jhsenjaliya](https://github.com/jhsenjaliya)]
```

2024-10-03 22:24 UTC, RNHTTR approved these changes

2024-10-03 22:25 UTC, RNHTTR requested changes

2024-10-03 22:25 UTC, RNHTTR commented on INTHEWILD.md
> +1. [PayPal](https://www.paypal.com/) [[@kaddynator](https://github.com/kaddynator)], [@r39132](https://github.com/r39132) & [@jhsenjaliya](https://github.com/jhsenjaliya)]
```suggestion
1. [PayPal](https://www.paypal.com/) [[@kaddynator](https://github.com/kaddynator), [@r39132](https://github.com/r39132) & [@jhsenjaliya](https://github.com/jhsenjaliya)]
```

2024-10-11 13:48 UTC, RNHTTR approved these changes

2024-10-26 14:44 UTC, amoghrajesh approved these changes
LGTM +1
@RNHTTR observed that some places have the format: `a,b & c` while some have `a, b, c`. Can be unified

2024-10-26 16:49 UTC, eladkal commented
> @RNHTTR observed that some places have the format: a,b & c while some have a, b, c. Can be unified

We can always re-organize this if needed. I'll merge when CI is green

2024-10-26 16:50 UTC, eladkal approved these changes

2024-10-26 20:25 UTC, merged