core operator python: check virtualenv is importable by importing
apache/airflow pull request #43403
Opened 2024-10-26 16:39 UTC by thisiswhereitype

This imports the module to check for `ModuleNotFoundError`. A soft import is possible but then we importlib anyway and this will be most robust. This change is needed as a system `virtualenv` is not always available in a venv that airflow is not running in.

Closes #40420

2024-10-26 20:15 UTC, potiuk commented
Actually - this is not correct/complete - is really a breaking change. 

So var PythonVirtualenv operator used "virtualenv" package to create the venvs, not the built-in venv.  Also there is a dedicated `[virtualenv]` extra to install the package. The package is here: https://pypi.org/project/virtualenv/

Note that virtualenv is stil maintained till today, even if venv became available 

This is mostly due to historical reasons, but also because `virtualenv` created venv behaves slightly differently than the built-in venv one (one of the differences for example is that it cannot be relocatable).

I do not think we are bound to any specifics of `venv` vs `virtualenv` - however when customers use PythonVirtualenvOperat (and `virtualenv` under the hood) they might rely on some internals and differences of `virtualenv` vs `venv`.

So while I sympathise with the change - since `venv` is now built-in in Python since 3.3 - I think a change to use `venv` instead of `virtualenv` needs to be discussed in devlist, ending up as a potentially breaking change in Airflow 3 and newsfragment.

Also this change is plainly wrong - creating virtualenv currently actually uses "virtualenv" command line not `venv` module - so if we accept it as it is, it will check for `venv` but actually will use for `virtualenv`.

2024-10-26 20:16 UTC, potiuk requested changes
Requesting changes until the actual scope of the change and whether we want to change from virtualenv to venv (and it should be complete change if we do).

2024-10-27 14:11 UTC, thisiswhereitype commented
Thanks for taking a look, I, for some reason though venv and virtualenv were the same. As you say this would be breaking.

2024-10-27 22:05 UTC, potiuk approved these changes
This is better (and I do recognise a need of synchronizing the check with the venv creation command), but not necessary ideal. 

The actual virtualenv creation happens by

```python
cmd = [sys.executable, "-m", "virtualenv", tmp_dir]
```

While the check for importing virtualenv is good and "sys.executable" should **generally** provide good results, but I can imagine some cases where your PYTHONPATH is modified after running the interpreter where it can still provide different results.

Maybe a better check will be checking if that works:

```bash 
python -m virtualenv --version
```

which means runing this:

```python
cmd = [sys.executable, "-m", "virtualenv", "--help"]
```

WDYT?

2024-10-27 22:06 UTC, potiuk requested changes
approved accidentally

2024-10-31 23:42 UTC, potiuk commented
Switching to venv in https://github.com/apache/airflow/pull/43568 - closing that one

2024-10-31 23:42 UTC, closed without merging