Remove Provider Deprecations in SSH
apache/airflow pull request #44544
Opened 2024-12-01 19:36 UTC by jscheffl

In Airflow 3 Dev Call we discussed and made a LAZY CONSENSUS to remove all deprecation's in providers prior 2.11 release in https://lists.apache.org/thread/lhy7zhz8yxo3jjpln0ds8ogszgb9b469.

This PR is the first for the provider **SSH**

2024-12-01 20:14 UTC, gopidesupavan approved these changes

2024-12-02 16:01 UTC, vincbeck requested changes
Please edit the changelog of this provider to call out breaking changes

2024-12-02 18:44 UTC, jscheffl commented
relates to #44559

2024-12-02 21:00 UTC, vincbeck approved these changes

2024-12-02 22:35 UTC, merged