Upgrade cryptography package to fix vulnerable OpenSSL
apache/airflow pull request #45040
Opened 2024-12-18 16:05 UTC by gsingh935

Upgrade cryptography package to fix vulnerable OpenSSL

https://github.com/advisories/GHSA-h4gh-qq45-vh27

2024-12-18 17:34 UTC, pierrejeambrun approved these changes
@potiuk nothing more to do about constraints ? That will just be fixed in next patch release ?

2024-12-18 17:50 UTC, potiuk requested changes
Those are completely different requirements - they are not airflow depdendencies - if you read README those dev/requirments.txt  are  only used for dev tooling - why do you want to add cryptoghraphy there @gsingh935 ? This makes no sense whatsoever. Was it some AI -generated change?

2024-12-18 18:52 UTC, potiuk commented
BTW. That issue picked my interest - and I looked closely - it seems that the "constraint" cryptography is held by yandexcloud - and I created an issue for them to address it https://github.com/yandex-cloud/python-sdk/issues/131 

I think it's an important one and we should even consider suspending Yandexcloud if they cannot lift the limitation. But FYI @gsingh935 -> if you are not using yandexcloud, you are absolutely free to upgrade cryptography on your own. Our constraints are just constraints, not requirements, and if you think you should upgrade a dependency for whatever reason and airflow does not "hold" the dependency as a requirement - you are on your own to do it, we are not preventing it, you just need to make sure to test if it will work for you.

2024-12-18 18:53 UTC, potiuk commented
I am closing this issue as this was really wrongly addressing the issue.

2024-12-18 18:53 UTC, closed without merging

2024-12-18 20:02 UTC, gsingh935 commented
@potiuk - seems like the cryptography version for yandex-cloud has already been bumped to 43.0.1 which should address the issues.
https://github.com/yandex-cloud/python-sdk/pull/127/files

2024-12-19 00:11 UTC, pierrejeambrun commented
I should have looked closer.  Thanks for checking @potiuk