Add MessageDeduplicationId support to AWS SqsPublishOperator
apache/airflow pull request #45051
Opened 2024-12-18 18:07 UTC by Prab-27

related : #44876

Currently, the `SqsPublishOperator` in Airflow does not support the `MessageDeduplicationId` parameter for deduplication of messages sent to AWS SQS FIFO queues. Users are forced to rely solely on `ContentBasedDeduplication`, which may not be suitable for all scenarios. 

This PR aims to add support for `MessageDeduplicationId ` and test for deduplication to provide more flexibility and control over message deduplication.

(https://boto3.amazonaws.com/v1/documentation/api/1.35.6/reference/services/sqs/client/send_message.html))

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

2024-12-18 18:24 UTC, vincbeck approved these changes

2024-12-19 08:20 UTC, eladkal requested changes
Needs also a test for the success scenario.
You can add the needed changes to `test_execute_success` or write a separated test if needed

2024-12-22 03:28 UTC, Prab-27 commented
> Needs also a test for the success scenario. You can add the needed changes to `test_execute_success` or write a separated test if needed

Done! Is it okay ?

2025-01-06 15:49 UTC, vincbeck commented
@eladkal ?

2025-01-07 09:45 UTC, eladkal approved these changes

2025-01-07 10:06 UTC, merged