[AIRFLOW-3698] Add region param for EMR jobflow sensor
apache/airflow pull request #4514
Opened 2019-01-13 21:59 UTC by danabananarama

Make sure you have checked _all_ steps below.

### Jira

- [ ] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-3698

### Description

- [ ] Here are some details about my PR, including screenshots of any UI changes:
This PR is to allow setting the AWS region in the `EmrJobFlowSensor` so that we can sense EMR job flow completion in any region.

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
Amending [test](https://github.com/danabananarama/incubator-airflow/blob/d51a5e48a6ec015e365fdc754fbbe9875747dfc9/tests/contrib/sensors/test_emr_job_flow_sensor.py), did not add new test for functionality as it's essentially just persisting a new init param. Let me know if a new test needs to be added!

### Commits

- [ ] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.
  - All the public functions and the classes in the PR contain docstrings that explain what it does

### Code Quality

- [ ] Passes `flake8`

2019-01-14 09:47 UTC, ashb reviewed
I'm not sure this is required - it is possibly to specify the region via the extra field of the connection: `{"region_name": "ap-southeast-2"}`

2019-01-14 23:08 UTC, danabananarama commented
Thanks for looking @ashb! And thanks for the tip, it does the trick. Did I miss this in the documentation? (or if not, where would you recommend as a sensible place to add it? [Here](https://airflow.readthedocs.io/en/stable/howto/manage-connections.html?highlight=connection#connection-types)?)

2019-01-15 20:52 UTC, ashb commented
You probably didn't miss it - it's a whole in the docs :(

2019-01-16 23:53 UTC, danabananarama commented
I've updated the PR to add a bit in the _Managing Connections_ page in the docs, please let me know if there's a more suitable home for it or if anything needs rewording (:

2019-01-17 14:56 UTC, mik-laj commented
Could you provide a description on how to set up a connection via environment variables?
Similar to GCP: https://github.com/apache/airflow/pull/4523/files

2019-01-17 22:18 UTC, danabananarama commented
@mik-laj Oh cool, I didn't know you could do that! I'm afraid I haven't set up the AWS Connection that way before so I'm not aware of any AWS-specific things you might need to specify when setting it up that way.

2019-01-18 00:08 UTC, mik-laj commented
@mik-laj What specific things do you need? 
`schema` part must be equals `aws`. Query parameters must cotanins extra parameters. For example:  `aws_access_key_id=AA&aws_secret_access_key=BB&CC=aws_account_id'.
You should also write what the default `con_id` is in hooks and operators for this platforms.

2019-01-18 00:37 UTC, danabananarama commented
Since the query parameter bit is the same as for other Connection types, perhaps it makes more sense for the general case to be documented in the "Creating a Connection with Environment Variables" section to avoid repetition?

I'll add the general default `conn_id`, but I'm not sure it's worth including all of the hooks and operators for this, there are quite a lot and it would be tough to ensure this doc section is completely maintained going forward.

2019-01-18 00:44 UTC, mik-laj commented
This is already described when my PR is accepted.

2019-01-18 00:53 UTC, mik-laj commented
I do not think that it is worth writing a list of operators and hooks. just mention the default conn_id is enough

2019-01-21 16:23 UTC, ashb requested changes

2019-01-21 16:23 UTC, ashb commented on docs/howto/manage-connections.rst
> +    * **aws_secret_access_key**: AWS secret access key of the connection
I would rather we didn't document the key_id and access_key in extra, as those really belong in the login and password.

2019-01-21 16:23 UTC, ashb commented on docs/howto/manage-connections.rst
> +Authentication may be performed using any of the `boto3 options <https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html#configuring-credentials>`_. Alternatively, one can pa
Could you add this paragraph:

> To use IAM instance profile create an "empty" connection (that is one with no Login or Password) specified.

2019-01-21 16:23 UTC, ashb commented on docs/howto/manage-connections.rst
> +    Specify the extra parameters (as json dictionary) that can be used in ssh
`ssh` :D

2019-01-21 16:29 UTC, XD-DENG commented on docs/howto/manage-connections.rst
> +Extra (optional)
it may be good to mention that users can specify endpoint in `Extra` section by giving "host". This will be useful in cases like they're using S3-compatible services (but not AWS service.)

2019-01-21 21:46 UTC, danabananarama commented on docs/howto/manage-connections.rst
> +    Specify the extra parameters (as json dictionary) that can be used in ssh
d'oh ><

2019-01-21 21:48 UTC, danabananarama commented on docs/howto/manage-connections.rst
> +Extra (optional)
ah I missed that, thanks for the spot!

2019-01-21 21:55 UTC, danabananarama commented
Thanks for the feedback @ashb, @XD-DENG , I think I've addressed all the comments. Please let me know if anything else needs tweaking!

2019-01-22 16:24 UTC, ashb approved these changes
I'm happy. Any further comments @XD-DENG?

2019-01-22 16:31 UTC, XD-DENG commented
@ashb , LGTM.

Thanks @danabananarama

2019-01-22 16:34 UTC, XD-DENG approved these changes

2019-01-22 17:23 UTC, merged