Migrate trigger form params to new UI
apache/airflow pull request #45270
Opened 2024-12-29 16:16 UTC by jscheffl

After @shubhamraj-git has added the trigger form to the new React UI, this PR now adds the flexible trigger form - Based on the logic of the former AIP-50 implementation - using DAG ParamsDict to render form fields based on field definitions.

Note that the form rendering was made as a component by intent as it will be re-used in Connection Forms in future to render connection extra fields.

DRAFT as still WIP. Open items notes in the code. Especially after fields have changed, the JSON dict need to be updated.

2024-12-30 19:16 UTC, shubhamraj-git commented
Thanks @jscheffl for working on this.
Had the first look.

Its going good. 
As mentioned in TODO, we will support the accordion and not flat.

Some points which i noticed, just writing it down incase we don't miss.
1. There is no live changes to conf json onBlur
2. Should have a validation for integer inputs.
3. Dropdown not working for select values
4. we should have a time picker.
5. Length check not working
6. JSON inputs should have a code view? (Just a opinion)
7. List should have multi lines

Overall this is going in right direction.

Should we have inbuilt scroll for the dynamic form? since the modal seems very long.

2025-01-02 15:52 UTC, jscheffl commented
> Thanks @jscheffl for working on this. Had the first look. Looks great. The base is almost ready.
> 
> As mentioned in TODO, we will support the accordion and not flat.
> 
> Some points which i noticed, just writing it down incase we don't miss.
> 
>     1. There is no live changes to conf json onBlur
> 
>     2. Should have a validation for integer inputs.
> 
>     3. Dropdown not working for select values
> 
>     4. we should have a time picker.
> 
>     5. Length check not working
>        ~6. JSON inputs should have a code view? (Just a opinion)~
> 
>     6. List should have multi lines
> 
> 
> Overall this is going in right direction.
> 
> Should we have inbuilt scroll for the dynamic form? since the modal seems very long.
> 
> EDIT: Just saw a todo for point 6 (json code view) and most of the above issues as todo.

(1) I recommend to make into a separate PR - as also discussed 1:1
(2,3,5,6) fixed.
(4) would need a component fix in react for Chrome... and a workaround for Firefox. Firfox time picking is "just broken" - would make this to a separate PR as well.

So... for the Layout part I'd say... ready for review!

2025-01-03 16:49 UTC, shubhamraj-git reviewed
Thanks @jscheffl ! Overall it looks good. Just few comments.
When clicking on trigger run, the modal pops up with all the options at front.
Should we consider them in a accordion and if needed user can view?
Apart from it, had some general comments, which is similar for all files.

2025-01-03 16:49 UTC, shubhamraj-git commented on airflow/ui/src/components/FlexibleForm/FlexibleFormFieldAdvancedArray.tsx
> +
I see many utility func in each component.
Can we have a separate file to have all that one ? Maybe `FlexibleFormUtility` , no hard suggestions.
This will remove the warnings too..
```
Fast refresh only works when a file only exports components. Use a new file to share constants or functions between components.
```

2025-01-03 16:49 UTC, shubhamraj-git commented on airflow/ui/src/components/FlexibleForm/FlexibleFormFieldBool.tsx
> +    defaultChecked={param.value as boolean}
Let's use `Boolean(param.value)` to avoid any runtime issues.

2025-01-03 16:49 UTC, shubhamraj-git commented on airflow/ui/src/components/FlexibleForm/FlexibleFormFieldDate.tsx
> +    defaultValue={param.value as string}
Should we check the type of param.value or it will be for sure string?
If No, we should consider using `typeof param.value === "string" ? param.value : "";`

2025-01-04 16:11 UTC, jscheffl commented on airflow/ui/src/components/FlexibleForm/FlexibleFormFieldDate.tsx
> +    defaultValue={param.value as string}
Added a bit of safety net in all default parameters taking this from `param.value` - can you take a look again?

2025-01-04 16:11 UTC, jscheffl commented on airflow/ui/src/components/FlexibleForm/FlexibleFormFieldBool.tsx
> +    defaultChecked={param.value as boolean}
Thanks! adjusted.

2025-01-04 16:12 UTC, jscheffl commented on airflow/ui/src/components/FlexibleForm/FlexibleFormFieldAdvancedArray.tsx
> +
Oh, yeah - also saw this. Now I re-located all selector functions... I thought of keeping the logic of field and selection together... for the future to have maybe a plugin mechanism... but yeah can be reworked in future as well.

2025-01-05 14:42 UTC, shubhamraj-git approved these changes
Found one glitch, which can be taken in further work.

Also, few things to add in list of TODO:
1. Reset button should reset everything on the Form, including the flexible form, and it should ask a validation pop up, since if by mistake user press it, it's lot to loose.
2. Accordion should be there for flexible form fields.
3. And of course connection between conf and flexible form.

2025-01-05 14:42 UTC, shubhamraj-git commented on airflow/ui/src/components/FlexibleForm/FlexibleFormFieldString.tsx
> +      defaultValue={String(param.value)}
In case of null default value, it will convert that into "null" value, which when clicked on trigger won't show error. It should check for null and convert to empty string on UI and we can use field set to check the required criteria (Can refer Add variables page).

2025-01-05 18:10 UTC, shubhamraj-git commented on airflow/ui/src/components/FlexibleForm/FlexibleFormFieldDate.tsx
> +    defaultValue={param.value as string}
Yes, it's good to have

2025-01-07 18:47 UTC, bbovenzi commented on airflow/ui/src/components/FlexibleForm/FlexibleFormFieldObject.tsx
> +        border: "1px solid #CBD5E0",
It's best if we avoid hard coded hex colors.

Instead we can access the chaklra color themes like so:

```
useToken("colors", [
    "red.100",
    "red.800",
    "red.500",
    "red.400",
  ]);
  ```

2025-01-07 18:49 UTC, bbovenzi reviewed
1. I would argue against putting the form inside of an Accordion because it would hide required fields from the user.

<img width="278" alt="Screenshot 2025-01-07 at 1 42 39 PM" src="https://github.com/user-attachments/assets/3b798e8d-50c8-4fa4-9193-c313cd50778b" />
2. Let's remove the `FlexibleForm` prefix from these components. It's too hard to read and is redundant with their parent folder.

2025-01-08 22:07 UTC, jscheffl commented on airflow/ui/src/components/FlexibleForm/FlexibleFormFieldObject.tsx
> +        border: "1px solid #CBD5E0",
Adjusted via chakra variable - is this also OK?

2025-01-08 22:07 UTC, jscheffl commented on airflow/ui/src/components/FlexibleForm/FlexibleFormFieldString.tsx
> +      defaultValue={String(param.value)}
Will fix... probably tomorrow.

2025-01-11 19:58 UTC, jscheffl commented
Had a few "sleeps" over the discussion I had in Slack with @shubhamraj-git about Accordion.. and after Pierre also assigned it to the Note for Clear tasks... I am somewhat open and ajusted... as forms can get long. All is not (last commit) in one accordion group. Looks like this and parts are nicely folding:

![image](https://github.com/user-attachments/assets/f39c2a4d-94bc-4591-9dc8-3fa3a3a5d857)

Changing to Advanced options:

![image](https://github.com/user-attachments/assets/c56f7ee1-7af2-49a1-8d14-0b11595e686d)

WDYT?

2025-01-14 19:48 UTC, bbovenzi requested changes
Sorry this took me a bit to review.

Now I see how sections work with the accordions so ignore my previous comment.

It is a bit of a nitpick, but coudl we rename the field components? Along the lines of `NumberInput` instead of `FieldNumber`? 


I'm excited we're finally able to migrate all of this to react! Great work!

2025-01-14 19:48 UTC, bbovenzi commented on airflow/ui/src/components/TriggerDag/TriggerDAGForm.tsx
> +                        border: "1px solid var(--chakra-colors-border)",
Oh, this is much better than what I suggested.

2025-01-14 19:48 UTC, bbovenzi commented on airflow/ui/src/components/FlexibleForm/index.tsx
In the new UI, `index` files should not contain any logic and simply export functions we want to use elsewhere.
In this case, we should rename this file to `FlexibleForm.tsx` and then make a new `index.tsx` that exports the form and all the fields

I probably should add a style guide to our contributing docs.

2025-01-14 19:48 UTC, bbovenzi commented on airflow/ui/src/components/FlexibleForm/FieldMultiSelect.tsx
> +      aria-label="Select one or multiple Values"
```suggestion
      aria-label="Select one or multiple values"
```

2025-01-14 19:48 UTC, bbovenzi commented on airflow/ui/src/components/FlexibleForm/SelectElement.tsx
> +  } else if (isFieldDropdown(fieldType, param.schema)) {
We can consolidate Date, DateTime and Time components into one and just pass different values for `placeholder` and `type`

2025-01-14 19:48 UTC, bbovenzi commented on airflow/ui/src/queries/useDagParams.ts
> +};
We should update the API to  already have these types instead of manually creating the types here.

 But I am fine if we clean that up in another PR.

2025-01-14 19:48 UTC, bbovenzi commented on airflow/ui/src/components/FlexibleForm/SelectElement.tsx
> +  } else if (isFieldDropdown(fieldType, param.schema)) {
I think the same is true for StringArray and MultilineText. We only have to change the value we pass to it.

2025-01-14 19:48 UTC, bbovenzi commented on airflow/ui/src/components/FlexibleForm/FieldString.tsx
> +      placeholder={param.schema.examples ? "Start typing to see proposal values." : undefined}
```suggestion
      placeholder={param.schema.examples ? "Start typing to see options." : undefined}
```

2025-01-14 19:48 UTC, bbovenzi commented on airflow/ui/src/components/FlexibleForm/index.tsx
> +  readonly key: string;
```suggestion
```

`key` is a reserved prop. We don't need to include it in our types.

2025-01-14 19:48 UTC, bbovenzi commented on airflow/ui/src/components/FlexibleForm/Row.tsx
> +  );
```suggestion
export const Row = ({ name, param }: FlexibleFormElementProps) =>
  isHidden(param.schema) ? (
    <Hidden name={name} param={param} />
  ) : (
    <NormalRow name={name} param={param} />
  );
```

2025-01-14 19:48 UTC, bbovenzi commented on airflow/ui/src/components/FlexibleForm/NormalRow.tsx
> +    <Stack css={{ "flex-basis": "70%" }}>
```suggestion
    <Stack flexBasis="30%">
      <Field.Label flexBasis="0" fontSize="md">
        {param.schema.title ?? name} <Field.RequiredIndicator />
      </Field.Label>
    </Stack>
    <Stack flexBasis="70%">
```

2025-01-14 19:48 UTC, bbovenzi commented on airflow/ui/src/components/FlexibleForm/NormalRow.tsx
> +export const NormalRow = ({ key, name, param }: FlexibleFormElementProps) => (
```suggestion
export const NormalRow = ({ name, param }: FlexibleFormElementProps) => (
```

2025-01-14 19:48 UTC, bbovenzi commented on airflow/ui/src/components/FlexibleForm/NormalRow.tsx
> +      <SelectElement key={key} name={name} param={param} />
```suggestion
      <SelectElement name={name} param={param} />
```

2025-01-14 19:48 UTC, bbovenzi commented on airflow/ui/src/components/FlexibleForm/SelectElement.tsx
> +    return <FieldBool key={key} name={name} param={param} />;
We should remove all references to `key` in this file. It's not necessary

2025-01-14 19:48 UTC, bbovenzi commented on airflow/ui/src/components/FlexibleForm/index.tsx
> +                  title="Population of changes in trigger form fields is not implemented yet. Please stay tuned for upcoming updates... and change the run conf in the 'Advanced Options' conf section
```suggestion
                  title="Work In Progress, use the 'Advanced Options' conf section below to actually edit dag run parameters for now."
```

2025-01-14 19:48 UTC, bbovenzi commented on airflow/ui/src/queries/useDagParams.ts
> +};
Also, after looking at the actual dag params returned it looks like `undefined` might be a more accurate type than `null`

2025-01-14 19:48 UTC, bbovenzi commented on airflow/ui/src/components/FlexibleForm/index.tsx
> +                      .filter(([, param]) => param.schema.section === currentSection)
We can simplify this component a lot:

```suggestion
      {Object.entries(params)
        .map(([, secParam]) => {
          const currentSection = secParam.schema.section ?? "Run Parameters";

          if (processedSections.has(currentSection)) {
            return undefined;
          } else {
            processedSections.set(currentSection, true);

            return (
              <Accordion.Item key={currentSection} value={currentSection}>
                <Accordion.ItemTrigger cursor="button">{currentSection}</Accordion.ItemTrigger>
                <Accordion.ItemContent>
                  <Stack separator={<StackSeparator />}>
                    {Object.entries(params)
                      .filter(
                        ([, param]) =>
                          param.schema.section === currentSection ||
                          (currentSection === "Run Parameters" && !Boolean(param.schema.section)),
                      )
```

2025-01-14 19:48 UTC, bbovenzi commented on airflow/ui/src/components/FlexibleForm/Hidden.tsx
> +export const Hidden = ({ name, param }: FlexibleFormElementProps) => (
I think `HiddenInput` is more description

2025-01-14 19:48 UTC, bbovenzi commented on airflow/ui/src/components/FlexibleForm/NormalRow.tsx
> +export const NormalRow = ({ key, name, param }: FlexibleFormElementProps) => (
I think something like `FlexibleField` is more descriptive than `NormalRow`

2025-01-14 19:48 UTC, bbovenzi commented on airflow/ui/src/components/FlexibleForm/SelectElement.tsx
> +export const SelectElement = ({ key, name, param }: FlexibleFormElementProps) => {
Let's rename this. I thought it was a dropdown select at first.

Maybe `FieldInput`?

2025-01-14 19:48 UTC, bbovenzi commented on airflow/ui/src/components/FlexibleForm/FlexibleFormFieldObject.tsx
> +        border: "1px solid #CBD5E0",
yes great call!

2025-01-14 22:39 UTC, jscheffl commented on airflow/ui/src/components/FlexibleForm/index.tsx
Good point, adjusted

2025-01-14 22:40 UTC, jscheffl commented on airflow/ui/src/components/FlexibleForm/SelectElement.tsx
> +  } else if (isFieldDropdown(fieldType, param.schema)) {
Adjusted for Date/Time/DateTime.

But explicitly _not_ consolidated for Multiline text and StringArray... I assume different logic is needed later for parsing. Let's see how this will go, maybe later we can re-visit.

2025-01-14 22:41 UTC, jscheffl commented on airflow/ui/src/queries/useDagParams.ts
> +};
Added a TODO. I am okay to check in a sepearate PR

2025-01-14 22:41 UTC, jscheffl commented on airflow/ui/src/components/FlexibleForm/index.tsx
> +  readonly key: string;
Learning something new... every day :-D

2025-01-14 22:42 UTC, jscheffl commented on airflow/ui/src/components/FlexibleForm/NormalRow.tsx
> +    <Stack css={{ "flex-basis": "70%" }}>
I attempted the adjust the `flex-basis`as proposed but this destroyed the layout... do you have an idea why? Just does NOT parse the flex setting to the element when I inspect the outcome rendered :-(

2025-01-14 22:43 UTC, jscheffl commented on airflow/ui/src/components/FlexibleForm/index.tsx
> +                      .filter(([, param]) => param.schema.section === currentSection)
Cool optimization! Did not get to this point. Was a hard point getting this "compiled" but much better now! Thanks!

2025-01-14 22:46 UTC, jscheffl commented on airflow/ui/src/components/FlexibleForm/SelectElement.tsx
> +export const SelectElement = ({ key, name, param }: FlexibleFormElementProps) => {
Named it ` FieldSelector` - is that OK and describes what it does?

2025-01-14 22:47 UTC, jscheffl commented on airflow/ui/src/components/FlexibleForm/NormalRow.tsx
> +export const NormalRow = ({ key, name, param }: FlexibleFormElementProps) => (
With "Normal Row" I wanted to say that this is "not hidden" - maybe there will be more complex field types int he future... "Normal" for me is a label plus some entry.

We have too many components with "Fields" already... this here renders a row. Would `FormRow` be also OK?

2025-01-14 22:48 UTC, jscheffl commented
> Sorry this took me a bit to review.
> 
> Now I see how sections work with the accordions so ignore my previous comment.
> 
> It is a bit of a nitpick, but coudl we rename the field components? Along the lines of `NumberInput` instead of `FieldNumber`?
> 
> I'm excited we're finally able to migrate all of this to react! Great work!

Uff, this was a very good review! Learned something new. I assume now it needs a second iteration review from the rework...
Had some challenges with the `flex-basis` - which is much cleaner in your proposal... but somehow not working. Any idea why?

2025-01-15 02:53 UTC, bbovenzi commented on airflow/ui/src/components/FlexibleForm/NormalRow.tsx
> +    <Stack css={{ "flex-basis": "70%" }}>
Actually we only need the `flexBasis="70%"` all the others can be removed. but what are you seeing when you do that?

2025-01-15 03:07 UTC, bbovenzi reviewed
Found two things with the datetime field.

Also, did you see my comment on renaming the Fields and NormalRow?

2025-01-15 03:07 UTC, bbovenzi commented on airflow/ui/src/components/FlexibleForm/FieldDateTime.tsx
> +export const FieldDateTime = ({ name, param, subType }: DateTimeElementProps) => (
```suggestion
export const FieldDateTime = ({ name, param, ...rest }: FlexibleFormElementProps & InputProps) => (
```

we can just use the existing InputProps. And the pre-existing placeholders are actually fine:

<img width="843" alt="Screenshot 2025-01-14 at 10 03 21 PM" src="https://github.com/user-attachments/assets/946f46df-a415-4496-95d7-5cab138705c7" />

2025-01-15 03:07 UTC, bbovenzi commented on airflow/ui/src/components/FlexibleForm/FieldSelector.tsx
> +  fieldType === "string" && fieldSchema.format === "date";
```suggestion
  fieldType === "string" && fieldSchema.format === "time";
```

2025-01-15 03:09 UTC, bbovenzi commented on airflow/ui/src/components/FlexibleForm/FieldDateTime.tsx
> +export const FieldDateTime = ({ name, param, subType }: DateTimeElementProps) => (
These are US defaults for me, are the placeholders different for you based on your locale?

2025-01-15 22:47 UTC, jscheffl commented on airflow/ui/src/components/FlexibleForm/FieldSelector.tsx
> +  fieldType === "string" && fieldSchema.format === "date";
Great catch!

2025-01-15 22:58 UTC, jscheffl commented on airflow/ui/src/components/FlexibleForm/NormalRow.tsx
> +    <Stack css={{ "flex-basis": "70%" }}>
Yeah, one point is right - the definition with 70% is sufficient!

But if I change from `<Stack css={{ "flex-basis": "70%" }}>` to `<Stack flex-basis="70%">`

The form switches to
![image](https://github.com/user-attachments/assets/881acd33-490a-41e2-868a-1b9f89b5dacb)

Reverting back to the ugly/complex/indirect CSS statement it makes it clean/pretty. Maybe I am just too stupid but with your proposed approach the inspector does not show the `flex-basis` at the generated `<div>` at all :-O 
![image](https://github.com/user-attachments/assets/16843024-d1ce-4603-8df7-a12d227c0878)

2025-01-15 23:07 UTC, jscheffl commented on airflow/ui/src/components/FlexibleForm/FieldDateTime.tsx
> +export const FieldDateTime = ({ name, param, subType }: DateTimeElementProps) => (
Nope, the placeholders are hard-coded. Do you know any chakra localizable option?

I just checked but also using @orange_digital/chakra-datepicker is not a better option in my view... short research tells me... or I am blind - don't see better components available?
Maybe we start the the US placeholders and rework later? Otherwise ideas welcome. (not an expert in this :-( are there localization libs?)

2025-01-15 23:11 UTC, jscheffl commented
> Found two things with the datetime field.
> 
> Also, did you see my comment on renaming the Fields and NormalRow?

Next round of reviews applied.
Saw the request to rename "NormalRow" ... renamed it to proposed "FieldRow" - is this OK?
The other comment about renaming the Fields... I did not understand. Can you help me what you wanted me to rename to?

2025-01-15 23:27 UTC, jscheffl commented on airflow/ui/src/components/FlexibleForm/FieldDateTime.tsx
> +export const FieldDateTime = ({ name, param, subType }: DateTimeElementProps) => (
Just noticed that the placehodlers not needed at all for date+time pickers. They are generated by the browser.

I removed the complexity.

And also realized that if I switch my system locale to German (I use EN-US per default) then in Firefox the date and time placeholders are correct.

2025-01-16 15:36 UTC, bbovenzi approved these changes
Actually, this all looks pretty good. Let's get this merged and continue working on the rest

2025-01-16 15:37 UTC, bbovenzi commented on airflow/ui/src/components/FlexibleForm/NormalRow.tsx
> +    <Stack css={{ "flex-basis": "70%" }}>
Ok let's leave it as-sis then

2025-01-16 15:37 UTC, bbovenzi commented on airflow/ui/src/components/FlexibleForm/NormalRow.tsx
> +export const NormalRow = ({ key, name, param }: FlexibleFormElementProps) => (
FormRow is a good descriptor!

2025-01-16 15:51 UTC, merged