[AIRFLOW-2955] Fix kubernetes pod operator to set requests and limits on task pods
apache/airflow pull request #4551
Opened 2019-01-18 11:21 UTC by suensummit

Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-XXX
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.

### Description

- [x] Fix `kubernetes_pod_operator` to set resources requests/limits with a dictionary instead of passing an entire class `Resource()` to the operator. Also add test method `test_pod_resources` for it.

### Tests

- [x] My PR adds the following unit tests: `test_pod_resources`

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.
  - All the public functions and the classes in the PR contain docstrings that explain what it does

### Code Quality

- [x] Passes `flake8`

2019-01-21 06:45 UTC, feng-tao commented
PTAL @dimberman

2019-01-25 03:32 UTC, suensummit commented
Thanks @feng-tao 
Is there anything need to fix yet? @dimberman

2019-02-27 06:25 UTC, suensummit commented
Just resolved conflicts that due to merge order; PTAL @dimberman thanks.

2019-04-10 08:42 UTC, galuszkak requested changes

2019-04-10 08:42 UTC, galuszkak commented on airflow/contrib/operators/kubernetes_pod_operator.py
> +            pass
That `else` is unnecessary?

2019-04-12 16:08 UTC, dimberman commented
Besides the nit from @galuszkak this all LGTM. Please address that comment, rebase/clean up commits, and then I'd be glad to merge :).

2019-04-30 09:18 UTC, suensummit commented
@dimberman Just rebase and clean up commits, please check it after the CI passed, thanks.

2019-04-30 17:20 UTC, dimberman requested changes
Just mine and @galuszkak 's nits and this is good to go

2019-04-30 17:20 UTC, dimberman commented on airflow/contrib/operators/kubernetes_pod_operator.py
> +        if resources is not None:
you can just write "if resources:" here

2019-05-02 03:21 UTC, suensummit commented on airflow/contrib/operators/kubernetes_pod_operator.py
> +        if resources is not None:
OK cool, thanks.

2019-05-09 03:15 UTC, suensummit commented on airflow/contrib/operators/kubernetes_pod_operator.py
> +        if resources is not None:
Hi @dimberman PTAL thanks

2019-05-09 16:46 UTC, dimberman approved these changes

2019-05-09 16:47 UTC, merged