AIRFLOW-3783 Switch to HEADER option being provided already by Redshift
apache/airflow pull request #4610
Opened 2019-01-29 10:02 UTC by shrechak

Make sure you have checked _all_ steps below.

### Jira

- [ ] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-3783

### Description

- [ ] Here are some details about my PR, including screenshots of any UI changes:

    Redshift has added a new HEADER option to the UNLOAD operation parameters.So we can remove the default PARALLEL OFF in the existing RedshiftToS3Transfer operator. The unload operation can now run parallely, hence faster, along with headers, if required.

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.
  - All the public functions and the classes in the PR contain docstrings that explain what it does

### Code Quality

- [ ] Passes `flake8`

2019-04-06 15:39 UTC, kurtqq commented
is this goes in next release?

2019-04-08 09:26 UTC, Fokko commented
@kurtqq No, the `v1.10.3` is in RC2, and therefore we won't add any new functionality. You could speed up the process by giving the operator a try.

@shrechak Could you rebase?

2019-04-08 09:47 UTC, ashb commented
Does this need a certain version of Redshift cluster? i.e. will this still work on clusters that have been around for some time?

2019-05-01 18:03 UTC, kurtqq commented
@ashb  to answer your question - yes.
"Versions 1.0.3945, 1.0.4081, 1.0.4222
Time period: September 19–October 10, 2018
Features and Improvements
    Amazon Redshift: You can specify the HEADER option in the UNLOAD command to add a specific header row to each created output file. The header row contains the column names created by the unload query.
"
https://docs.aws.amazon.com/redshift/latest/mgmt/rs-mgmt-cluster-version-notes.html

also info on stackoverflow (see fez answer):
https://stackoverflow.com/questions/24681214/unloading-from-redshift-to-s3-with-headers

2019-05-01 22:36 UTC, ashb commented
In which case this probably needs to be an option (that can default to on) to continue working with older clusters, right? Or do clusters auto/forcibly get upgraded?

2019-05-20 18:15 UTC, kurtqq commented
@ashb It's auto/forcibly update:

`Amazon Redshift provides a setting, Allow Version Upgrade, to specify whether to automatically upgrade the Amazon Redshift engine in your cluster if a new version of the engine becomes available. This setting doesn't affect the database version upgrades, which are applied during the maintenance window that you specify for your cluster. Amazon Redshift engine upgrades are major version upgrades, and Amazon Redshift database upgrades are minor version upgrades. You can disable automatic version upgrades for major versions only. For more information about maintenance windows for minor version upgrades, see Maintenance Windows. `
https://docs.aws.amazon.com/redshift/latest/mgmt/working-with-clusters.html

The 1.0 is the cluster version which the user can control if he wants to update or not. 
but the user have no control over the database version update. Redshift force update this in the maintenance windows. 
Since all users run the same cluster version (1.0)  this PR is safe to be merged in my opinion.

2019-05-28 16:48 UTC, ashb approved these changes
Not familiar with RedShift but the logic seems sensible.

2019-06-02 10:26 UTC, OmerJog commented
@shrechak  Can you please rebase ?

2019-06-17 06:56 UTC, OmerJog commented
@shrechak you have minor style errors to fix

flake8

./tests/operators/test_redshift_to_s3_operator.py:50:20: E999 TabError: inconsistent use of tabs and spaces in indentation





mypy

tests/operators/test_redshift_to_s3_operator.py:50: error: inconsistent use of tabs and spaces in indentation

2019-06-21 15:21 UTC, ashb requested changes
Fix the style issues.

2019-06-21 15:21 UTC, ashb commented on tests/operators/test_redshift_to_s3_operator.py
> +	columns_query = """
```suggestion
        columns_query = """
```

2019-06-27 20:27 UTC, OmerJog commented
@shrechak if you don't mind fixing the minor styles maybe this PR will make it to the next release

2019-07-30 02:56 UTC, OmerJog commented
@shrechak ping

2019-10-11 14:27 UTC, feluelle commented
Closed in favor of #6309

2019-10-11 14:27 UTC, closed without merging