synchronize airflow execution timeout and aws batch job timeout
apache/airflow pull request #5035
Opened 2019-04-04 12:26 UTC by bovoleg

Make sure you have checked _all_ steps below.

### Jira

- [ ] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-XXX
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [ ] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [ ] Passes `flake8`

2019-04-04 13:15 UTC, XD-DENG commented
Hi @bovoleg , I haven't checked your code change yet. But may you read the PR template carefully and create JIRA then add details accordingly?

Your PR is a code change, which needs a JIRA to be created.

2019-04-04 16:09 UTC, bovoleg commented
created Jira ticket AIRFLOW-4239
synchronize airflow task execution timeout and aws batch timeout
but not sure how to link with PR

2019-04-04 21:49 UTC, ashb requested changes
At the very least the parameter will need adding to the doc string, and it should mention the behaviour.

I'm not sure that setting the execution_timeout of the task to _exactly_ the same value is right either - that will stop the task a little before the timeout on Batch (due to other processing). Not sureif that is a problem though.

2019-04-05 07:01 UTC, bovoleg commented
Hello,

   The “execution_timeout” argument is the parameter of the every airflow job. It is already well described in the documentation and in the BaseOperator class.
My suggested changes does not override its behavior, but just setup the AWS Batch execution timeout to the same value, which allows to synch task execution expectations between airflow and AWS Batch.
Without this changes Airflow may fail the task in 20 minutes when AWS batch may have timeout to 1 hours continues execution and success.

Oleg.


Від: Ash Berlin-Taylor <notifications@github.com>
Надіслано: 5 апреля 2019 г. 0:50
Кому: apache/airflow <airflow@noreply.github.com>
Копія: Oleg Burlachenko <oleg.burlachenko@zorallabs.com>; Mention <mention@noreply.github.com>
Тема: Re: [apache/airflow] [AIRFLOW-4239] Synchronize airflow execution timeout and aws batch job timeout (#5035)


@ashb requested changes on this pull request.

At the very least the parameter will need adding to the doc string, and it should mention the behaviour.

I'm not sure that setting the execution_timeout of the task to exactly the same value is right either - that will stop the task a little before the timeout on Batch (due to other processing). Not sureif that is a problem though.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/apache/airflow/pull/5035#pullrequestreview-223019365>, or mute the thread<https://github.com/notifications/unsubscribe-auth/Ak52oFIJGVBGr-5TtjyU6zHS--L1f_krks5vdnORgaJpZM4ccq-j>.

2019-04-05 12:17 UTC, Fokko commented on airflow/contrib/operators/awsbatch_operator.py
> +        self.execution_timeout = kwargs.get('execution_timeout', timedelta(seconds=3600))
I would suggest not pulling this from the `kwargs` and make it an argument with a default value. WDYT?

2019-04-07 18:42 UTC, bovoleg commented
The goal of this change is to setup AWS batch timeout to the same value as airflow batch timeout.

This value is already exists in the BatchOperator declaration
    :param execution_timeout: max time allowed for the execution of
        this task instance, if it goes beyond it will raise and fail.

So I think if add additional parameter we still may have a situation when AWS batch timeout and airflow timeout has different values, which I think we should avoid.

Oleg Burlachenko

Від: Fokko Driesprong <notifications@github.com>
Надіслано: 5 апреля 2019 г. 15:18
Кому: apache/airflow <airflow@noreply.github.com>
Копія: Oleg Burlachenko <oleg.burlachenko@zorallabs.com>; Mention <mention@noreply.github.com>
Тема: Re: [apache/airflow] [AIRFLOW-4239] Synchronize airflow execution timeout and aws batch job timeout (#5035)


@Fokko commented on this pull request.

________________________________

In airflow/contrib/operators/awsbatch_operator.py<https://github.com/apache/airflow/pull/5035#discussion_r272560358>:

> @@ -75,7 +76,7 @@ def __init__(self, job_name, job_definition, job_queue, overrides, max_retries=4

         self.job_queue = job_queue

         self.overrides = overrides

         self.max_retries = max_retries

-

+        self.execution_timeout = kwargs.get('execution_timeout', timedelta(seconds=3600))

I would suggest not pulling this from the kwargs and make it an argument with a default value. WDYT?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/apache/airflow/pull/5035#pullrequestreview-223240666>, or mute the thread<https://github.com/notifications/unsubscribe-auth/Ak52oMbGYxoIFCT9DbznewjYQzHRHt3aks5vdz79gaJpZM4ccq-j>.

2019-11-27 17:48 UTC, closed without merging