add region_name to emr add step operator
apache/airflow pull request #5267
Opened 2019-05-10 03:05 UTC by natsumehu

Make sure you have checked _all_ steps below.

### Jira

- [ ] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW-4493) issues and references them in the PR title. 

### Description

- [ ] We add an extra parameter region_name to the EmrAddStepsOperator.

### Tests

- [ ] My PR quiet simple. We tested on our prod environment and can get the job flow id if our cluster located in no default region.

### Commits

### Documentation

### Code Quality

- [ ] Passes `flake8`

2019-05-21 20:27 UTC, feluelle requested changes
LGTM except the new field is missing in the docs.

(If you don't mind you could also check that the region_name (and all the other args) have been passed to the mocked boto object)

2019-05-21 20:27 UTC, feluelle commented on airflow/contrib/operators/emr_add_steps_operator.py
> +            region_name=None,
Please add this new argument to the docs above :)

2019-06-11 10:32 UTC, ashb commented
This can be specified in side the connection - do we need to add it here too?

2019-06-21 15:25 UTC, ashb commented
Region name can be specified in the extra field of the AWS connection. See https://airflow.apache.org/1.10.3/howto/connection/aws.html

2019-06-21 15:25 UTC, closed without merging