[AIRFLOW-4477] Add models methods to BQHook
apache/airflow pull request #5268
Opened 2019-05-10 10:18 UTC by ryanyuan

Make sure you have checked _all_ steps below.

### Jira

- [ ] My PR addresses the following [Airflow-4477](https://issues.apache.org/jira/browse/AIRFLOW-4477) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"

### Description

- [ ] Here are some details about my PR, including screenshots of any UI changes:
Add v2.models to BigQueryHook
Reference: https://cloud.google.com/bigquery/docs/reference/rest/v2/models

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
test_bigquery_hook.py:TestBigQueryHookModelOperations.test_bigquery_list_model
test_bigquery_hook.py:TestBigQueryHookModelOperations.test_bigquery_get_model
test_bigquery_hook.py:TestBigQueryHookModelOperations.test_bigquery_patch_model
test_bigquery_hook.py:TestBigQueryHookModelOperations.test_bigquery_delete_model

### Commits

- [ ] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [ ] Passes `flake8`

2019-05-10 10:59 UTC, ryanyuan commented
PTAL @kaxil @potiuk

2019-05-14 05:31 UTC, potiuk requested changes
Are you planning to use the models in some Operator? I think you should add it together with the same PR

2019-05-15 15:40 UTC, VFagundes commented on airflow/contrib/hooks/bigquery_hook.py
> +            model = self.service.models().get(
how about instantiate the model outside of your `try/except` block and just leave the execute instruction inside of it?
something like:

```
    model = self.service.models().get( projectId=project_id,
                datasetId=dataset_id,
                modelId=model_id)
    try:
      big_query_model = model.execute(num_retiries=self.num_retries)
        self.log.info('BigQuery model retrieved successfully: In project %s '
                          'Dataset %s Model %s', project_id, dataset_id, model_id)
        return big_query_model
    except HttpError as err:
            raise AirflowException(
                'BigQuery models failed to retrieve. Error was: {}'.format(err.content)
            )
```

what do you think? :)

2019-05-15 15:41 UTC, VFagundes commented on airflow/contrib/hooks/bigquery_hook.py
> +            model = self.service.models().patch(
Same comment about it 
https://github.com/apache/airflow/pull/5268/commits#r284322025
:)

2019-06-12 08:44 UTC, mik-laj commented
@ryanyuan Do you plan to continue working on this change?  I am organizing tickets in JIRA related to GCP  and I would like to know the current status of this change.

2019-06-12 12:51 UTC, ryanyuan commented
@mik-laj I am not going to work on this until there are more endpoints exposed because so far we found we could run the query directly to achieve what the API can do.

2019-06-12 12:56 UTC, mik-laj commented
Do you think it's worth closing the ticket now? Now it is a ticket without a proper use case.  it can introduce noise on Jira

2019-06-12 13:00 UTC, ryanyuan commented
@mik-laj Agree. Closing this PR.

2019-06-12 13:00 UTC, closed without merging