AIRFLOW-4512 - New trigger rule for tasks - At least one successful
apache/airflow pull request #5288
Opened 2019-05-16 05:02 UTC by bharathpalaksha

Make sure you have checked _all_ steps below.

### Jira

- [ ] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW-4512) issues and references them in the PR title. 
 
### Description

- [ ] New trigger rule - atleast_one_success

Trigger rules help in defining better dependencies on up stream tasks. There are good number of rules currently defined which are as below

all_success: (default) all parents have succeeded
all_failed: all parents are in a failed or upstream_failed state
all_done: all parents are done with their execution
one_failed: fires as soon as at least one parent has failed, it does not wait for all parents to be done
one_success: fires as soon as at least one parent succeeds, it does not wait for all parents to be done
none_failed: all parents have not failed (failed or upstream_failed) i.e. all parents have succeeded or been skipped
none_skipped: no parent is in a skipped state, i.e. all parents are in a success, failed, or upstream_failed state
dummy: dependencies are just for show, trigger at will
 

There can be another rule added here which is atleast_one_success - This waits for all parent tasks to be complete and checks if at least one parent is successful and triggers current task. It differs from one_success as it waits for all parents to be done. 

Consider a very common scenario in data pipelines where you have a number of parallel tasks generating some data. As a downstream task to all these generate tasks, you have a task to collate all data into one collection which has to run if any of the upstream generate is successful and also has to wait for all of them to be done. one_success can't be used as it doesn't wait for other tasks.

### Tests

### Commits

### Documentation

### Code Quality

- [ ] Passes `flake8`

2019-05-19 12:14 UTC, OmerJog commented
This PR is missing tests.
You can refer to another PR which added new trigger rule for reference https://github.com/apache/airflow/pull/5032

Also I'm not too crazy about the name `ATLEAST_ONE_SUCCESS`.
The name should reflect the meaning. When viewing `ONE_SUCCESS `and `ATLEAST_ONE_SUCCESS `it will causes confusion between them.

As a general comment if this is merged it will open a window to many many different kinds of trigger rules. Maybe a better approach will be to design a mechanism where you can use more than one trigger rule. So for your need it will be `ALL_DONE `+ `ONE_SUCCESS`. This way there will be less trigger rules to maintain and the functionality will grow dramatically.

2019-05-23 07:17 UTC, milton0825 requested changes

2019-05-23 07:17 UTC, milton0825 commented on docs/concepts.rst
> +* ``atleast_one_success``: fires if at least one parent succceeds, it waits for all parents to be done
I think we should rename it to something like `one_access_wait_all`?  People might not be able to tell the difference between `atleast_one_success` and `one_success` without looking through the docs.

2019-05-23 07:17 UTC, milton0825 commented
Also can we add some tests?

2019-05-31 10:39 UTC, closed without merging

2020-05-22 10:44 UTC, psuanm5030 commented
Curious if there was any progress or other methods of getting this result?

2020-06-22 08:17 UTC, jledru commented
Hello,
Is there any method to achieve the goal of atleast_one_success ?
As I would need this behaviour in one of my DAG.
Thanks,

2020-06-23 18:00 UTC, panas2567 commented
> Hello,
> Is there any method to achieve the goal of atleast_one_success ?
> As I would need this behaviour in one of my DAG.
> Thanks,

Create two mid tasks: 
_check_one_success_ with trigger rule one_success 
_check_all_done_ with trigger rule all_done
Then joining like:
[task1, task2, ..., taskN] >> check_one_success >> task_with_trigger_rule_at_least_one_success
[task1, task2, ..., taskN] >> check_all_done >> task_with_trigger_rule_at_least_one_success