[AIRFLOW-4289] fix spark_binary argument being ignored in SparkSubmit…
apache/airflow pull request #5564
Opened 2019-07-11 20:43 UTC by eladkal

…Hook

### Jira

https://issues.apache.org/jira/browse/AIRFLOW-4289

### Description

Fix bug where the spark_binary argument in the constructor of SparkSubmitHook was overwritten by spark Connection.

2019-07-12 13:38 UTC, ashb requested changes

2019-07-12 13:38 UTC, ashb commented on tests/contrib/hooks/test_spark_submit_hook.py
> +                               spark_binary='custom-spark-submit')
This test should pass without this change (as the spark binary was set in the connection)

We need a _new_ test that passes something _other_ than `custom-spark-binary` here and make sure that is used instead.

2019-07-12 13:38 UTC, ashb commented on tests/contrib/hooks/test_spark_submit_hook.py
> +            '--spark_binary', 'spark-submit',
This isn't a valid option to spark-submit

2019-07-12 13:38 UTC, ashb commented on tests/contrib/hooks/test_spark_submit_hook.py
> +                                     "spark_binary": None,
This is wrong - in this case the spark_binary still needs to by `spark-submit`.

2019-07-26 06:14 UTC, appunni-dishq commented
In spark_default connection we are using spark-binary, I tried spark_binary there and got very confused.

2019-07-29 17:18 UTC, eladkal commented
@ashb I need some help in resolving the failed test:
```
test_resolve_connection_yarn_default (tests.contrib.hooks.test_spark_submit_hook.TestSparkSubmitHook) ... INFO  [airflow.contrib.hooks.spark_submit_hook.SparkSubmitHook] Could not load connection string , defaulting to yarn
INFO  [airflow.contrib.hooks.spark_submit_hook.SparkSubmitHook] Could not load connection string , defaulting to yarn
INFO  [airflow.contrib.hooks.spark_submit_hook.SparkSubmitHook] Spark-Submit cmd: ['spark-submit', '--master', 'yarn', '--name', 'default-name', 'test_application.py']
[31mFAILED[0m
```

Log:

```
[31m======================================================================[0m
[31m22) FAIL: test_resolve_connection_yarn_default (tests.contrib.hooks.test_spark_submit_hook.TestSparkSubmitHook)[0m
[31m----------------------------------------------------------------------[0m
[0m   Traceback (most recent call last):[0m
    [34mtests/contrib/hooks/test_spark_submit_hook.py[0m line [1m[36m246[0m[0m in [36mtest_resolve_connection_yarn_default[0m
      self.assertEqual(connection, expected_spark_connection)
[31m   [31m[1m[31mAssertionError[0m[0m[31m: [0m[31m{'master': 'yarn', 'queue': None, 'deploy_mode': None, 'spark[54 chars]ult'} != {'master': 'yarn', 'spark_binary': 'spark-submit', 'deploy_mo[64 chars]ult'}[0m
[31m     {'deploy_mode': None,[0m
[31m      'master': 'yarn',[0m
[31m      'namespace': 'default',[0m
[31m      'queue': None,[0m
[31m   -  'spark_binary': None,[0m
[31m   +  'spark_binary': 'spark-submit',[0m
[31m      'spark_home': None}[0m
```

The log shows that ` Could not load connection string , defaulting to yarn` Which means that `AirflowException` was raised due to ` conn = self.get_connection(self._conn_id)` as `self._conn_id` is empty string. In such case spark_binary won't be set.
The only solution here is to change 
```

        expected_spark_connection = {"master": "yarn",
                                     "spark_binary": "spark-submit",
                                     "deploy_mode": None,
                                     "queue": None,
                                     "spark_home": None,
                                     "namespace": 'default'}
```

To:
```
        expected_spark_connection = {"master": "yarn",
                                     "spark_binary": None,
                                     "deploy_mode": None,
                                     "queue": None,
                                     "spark_home": None,
                                     "namespace": 'default'}
```

This is required since this PR changed the default value in the contractor. 
Is that OK with you?

2019-07-30 02:08 UTC, eladkal commented
@ashb CI is green. Can you review?

2019-07-30 12:43 UTC, ashb requested changes
Please also add a test that uses `SparkSubmitHook(conn_id='spark_binary_set', spark_submit='spark-submit-from-init')` to ensure that the right value (`spark-submit-from-init`) comes through.

Almost there!

2019-07-30 12:43 UTC, ashb commented on airflow/contrib/hooks/spark_submit_hook.py
> +            connection_cmd = [self._connection['spark_binary'] or "spark-submit"]
```suggestion
            connection_cmd = [self._connection['spark_binary']]
```

This shouldn't be needed here as it's already set in _resolve_connection (lets keep the defaulting to one place)

2019-07-30 12:43 UTC, ashb commented on airflow/contrib/hooks/spark_submit_hook.py
> +                                           "spark-submit")]
```suggestion
```

2019-07-30 12:43 UTC, ashb commented on airflow/contrib/hooks/spark_submit_hook.py
> +                                           self._connection['spark_binary'] or
```suggestion
                                           self._connection['spark_binary']]
```

This shouldn't be needed here as it's already set in _resolve_connection (lets keep the defaulting to one place)

2019-07-30 13:09 UTC, eladkal commented
@ashb Isn't it already covered by `test_resolve_connection_spark_binary_set_connection` it takes
`conn_id='spark_binary_set'` and verify `spark_binary` is set to `custom-spark-submit`
We also have `test_resolve_connection_spark_home_not_set_connection` which verify the default of `spark_binary` is set to `spark-submit`

2019-07-30 13:57 UTC, ashb commented
@eladkal No that test doesn't cover the case where both the spark_submit is specified both in the connection and in the constructor.

I think we're fine without anything in UPDATING.md as this is a bug fix as you say

2019-07-30 19:35 UTC, eladkal commented
Hi @ashb added another test and squashed all commits.

2019-07-31 08:21 UTC, merged

2019-07-31 08:24 UTC, ashb commented
Thanks @eladkal, and just in time to make it in to 1.10.4rc4 too!

2019-09-18 14:33 UTC, boiler commented
@ashb @eladkal there is a bug in patch
'spark-binary' no longer taken from extra parameters

2019-09-19 09:03 UTC, eladkal commented
@boiler i see the problem I will PR a fix

2019-09-23 14:33 UTC, boiler commented
https://issues.apache.org/jira/browse/AIRFLOW-5517