[NO-TICKET] Clarify logic S3Hook
apache/airflow pull request #6313
Opened 2019-10-12 09:31 UTC by louisguitton

Make sure you have checked _all_ steps below.

### Jira

- [ ] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-XXX
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

2019-10-14 09:13 UTC, feluelle reviewed
_Just my opinion:_ I rather create a private function that will be called in public functions. So that you do not rely on another public function (in case the public function gets changed).

2019-10-16 03:13 UTC, milton0825 approved these changes

2019-10-16 06:18 UTC, louisguitton commented
Thank you both for your reviews. I agree with you @feluelle , I'll make the suggested changes

2019-10-16 09:40 UTC, feluelle approved these changes
Nice!

2019-10-16 09:41 UTC, feluelle commented
I restarted the failed travis checks.

2019-10-16 09:44 UTC, potiuk commented
If those are the kubernetes ones - maybe merge it without waiting. We have found with @gerardo a reason why kubernetes tests might timeout and we will fix it shortly - but I do not want to hold it back!

2019-10-16 10:14 UTC, ashb requested changes

2019-10-16 10:14 UTC, ashb commented on airflow/hooks/S3_hook.py
> -        client.upload_fileobj(filelike_buffer, bucket_name, key, ExtraArgs=extra_args)
This appears to have removed extra_args!

2019-10-16 10:15 UTC, ashb commented on airflow/hooks/S3_hook.py
> -        client.upload_fileobj(filelike_buffer, bucket_name, key, ExtraArgs=extra_args)
Oh no I see, I thought at first this was coming from user input but it doesn't.

2019-10-16 10:16 UTC, ashb approved these changes

2019-10-16 15:22 UTC, louisguitton commented
> If those are the kubernetes ones - maybe merge it without waiting. We have found with @gerardo a reason why kubernetes tests might timeout and we will fix it shortly - but I do not want to hold it back!

Yeah the 2 failing tests are the k8s ones :/

2019-10-16 16:48 UTC, feluelle commented
Yes, Jarek I just saw the thread right after I reran the tests. 

I think we can merge it then. 👍

2019-10-16 16:49 UTC, merged