[AIRFLOW-6266] Better asserts in test_views.py
apache/airflow pull request #6837
Opened 2019-12-17 19:26 UTC by potiuk

Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-6266

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

2019-12-17 19:26 UTC, kaxil approved these changes

2019-12-18 15:06 UTC, mik-laj commented on tests/www/test_views.py
> +        assert resp_code == resp.status_code, str(resp_html)
Can you use assertions from [unittest](https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertEqual) package?  Currently, this convention is used throughout the entire project. Keeping one style in the whole project facilitates its development.

2019-12-18 15:16 UTC, mik-laj requested changes
Please stick to the project convention. We should introduce new ideas, but if they relate to a significant part of the code, they should be accepted by the whole community.

2019-12-28 18:41 UTC, nuclearpinguin commented
@potiuk @mik-laj should we close or merge?

2019-12-28 18:47 UTC, potiuk reviewed
I am all for merging now :) @mik-laj ?

2019-12-28 18:58 UTC, mik-laj approved these changes

2019-12-28 19:01 UTC, mik-laj commented
I preferred that we still use the old style of assertion, but if others think otherwise then I will not block. @nuclearpinguin WDYT?

2019-12-28 19:12 UTC, turbaszek reviewed
I think we can achieve the same result using current framework.

2019-12-28 19:12 UTC, nuclearpinguin commented on tests/www/test_views.py
> +        assert resp_code == resp.status_code, str(resp_html)
```suggestion
     self.assertEqual(resp_code, resp.status_code, msg=str(resp_html)
```

2019-12-28 19:12 UTC, nuclearpinguin commented on tests/www/test_views.py
> +        assert resp_code == resp.status_code, str(resp_html)
```suggestion
    self.assertEqual(resp_code, resp.status_code, msg=str(resp_html)
```

2019-12-28 19:13 UTC, nuclearpinguin commented
But to be honest, I see no value in this change. The message will be a big, pure html

2019-12-28 19:19 UTC, potiuk commented
But it's only when the response is wrong . We will see exactly what was returned - I already realised the problem after looking at the response what was the root cause.

2020-04-10 03:37 UTC, closed without merging