[AIRFLOW-5117] Fixed Bug with ISO-8601 Timestamps
apache/airflow pull request #7153
Opened 2020-01-13 14:11 UTC by Bruschkov

#JIRA
https://issues.apache.org/jira/browse/AIRFLOW-5117

# Description
When using the KubernetesPodOperator on an aws kubernetes cluster, the aws-iam-authenticator is used to obatin kubernetes authentication tokens. The aws tokens contain ISO-8601 formatted timestamps, which couldn't be parsed in case of a "Z" (Zulu Time) timezone. This PR fixes this problem by converting the "Z" timezone into a regular +0000 format.

# Test Coverage
Not Needed, very minor fix

2020-01-13 15:32 UTC, potiuk reviewed
I'd still prefer to have a test for that one. This should b e rather easy to add such test.

There is already the tests/kubernetes/test_client.py with two tests and adding a test there would be just great (we need to improve coverage on Kubernetes part and even really small tests like that gradually added help a lot)

Would you be so nice to add it please?

2020-01-14 14:32 UTC, Bruschkov commented
> I'd still prefer to have a test for that one. This should b e rather easy to add such test.
> 
> There is already the tests/kubernetes/test_client.py with two tests and adding a test there would be just great (we need to improve coverage on Kubernetes part and even really small tests like that gradually added help a lot)
> 
> Would you be so nice to add it please?

Hi, thanks for your quick feedback. Added the test and amended the PR.

2020-01-15 09:54 UTC, Bruschkov commented
@potiuk 

Everything solved and build passes now.

Best regards

2020-01-16 16:39 UTC, ashb commented
Change looks good now, but as this JIRA was already released we need a new JIRA please. (We use the Fix Version to know what to pull back to our releases, and as AIRFLOW-5117 is already released we would otherwise miss this change when building 1.10.8)

2020-01-16 22:49 UTC, ashb requested changes
Please create new Jira ticket for this.

2020-01-21 08:48 UTC, Bruschkov commented
@ashb New JIRA created and linked to this PR.

2020-02-02 19:42 UTC, mik-laj commented
Why are these changes being made in this project and not in [the Kubernetes library](https://github.com/kubernetes-client/python-base)? I can't find the ticket in the library repository.

2020-02-03 08:07 UTC, Bruschkov commented
> Why are these changes being made in this project and not in [the Kubernetes library](https://github.com/kubernetes-client/python-base)? I can't find the ticket in the library repository.

https://github.com/apache/airflow/pull/5731#issuecomment-520271784

2020-04-08 11:19 UTC, ashb commented on airflow/kubernetes/refresh_config.py
> +    if ts_str[-1] == 'Z':
Using pendulum (which we already use) might be a better fix than this.

2020-07-17 22:37 UTC, benjaminsky commented
This is still an issue with EKS and Airflow v1.10.10. This PR fixes it. Can we reopen this PR?

2020-07-19 08:11 UTC, potiuk commented
@benjaminsky -> sure, would you mind picking this up? I think this one neds rebase and there is a change requested. Unnless (@Bruschkov wants to do it).

2020-09-11 03:39 UTC, closed without merging

2020-09-30 09:49 UTC, ramsesrm commented
Hi, this is still an issue on Airflow v1.10.12. Can we reopen the PR?