[AIRFLOW-XXXX] Review and cleanup integration tests docs.
apache/airflow pull request #7196
Opened 2020-01-17 11:16 UTC by potiuk

---
Issue link: WILL BE INSERTED BY [boring-cyborg](https://github.com/kaxil/boring-cyborg)

Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Commit message/PR title starts with `[AIRFLOW-NNNN]`. AIRFLOW-NNNN = JIRA ID<sup>*</sup>
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

<sup>*</sup> For document-only changes commit message can start with `[AIRFLOW-XXXX]`.

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

2020-01-17 11:16 UTC, potiuk commented
Hey @efedotova - here is the PR that you can use to review/improve the integration tests docs :)

2020-01-19 12:14 UTC, turbaszek requested changes

2020-01-19 12:14 UTC, nuclearpinguin commented on CONTRIBUTING.rst
> +  additional services running, such as Postgres,Mysql, Kerberos, etc. They are marked using
```suggestion
  additional services running, such as Postgres, Mysql, Kerberos, etc. They are marked using
```

2020-01-27 00:49 UTC, potiuk commented
@efedotova ? Any comments :) ?

2020-02-23 17:12 UTC, potiuk commented
The documentation changes have been already implemented in #7388

2020-02-23 17:12 UTC, closed without merging