[AIRFLOW-6695] Add DAG run configuration to UI
apache/airflow pull request #7312
Opened 2020-01-31 18:56 UTC by dacohen

---
Issue link: WILL BE INSERTED BY [boring-cyborg](https://github.com/kaxil/boring-cyborg)

Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Commit message/PR title starts with `[AIRFLOW-NNNN]`. AIRFLOW-NNNN = JIRA ID<sup>*</sup>
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

<sup>*</sup> For document-only changes commit message can start with `[AIRFLOW-XXXX]`.

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

2020-01-31 21:41 UTC, tooptoop4 approved these changes

2020-02-02 13:35 UTC, potiuk commented
Please rebase to latest master @dacohen  - we had a failing master drama and there is much higher chance the build will succeed. We have still some intermittent errors, but there should be less often.

2020-02-05 15:07 UTC, dacohen commented
@potiuk Rebase is done. Let me know if you need anything else.

2020-02-05 15:39 UTC, potiuk commented
I am not really experienced in that part of the code (UI)? I will let others take a look (@ashb /@kaxil @mik-laj ). ?

2020-02-05 16:55 UTC, ashb commented on airflow/www/templates/airflow/trigger.html
> +{% extends "airflow/master.html" %}
```suggestion
{% extends base_template %}
```

2020-02-05 16:56 UTC, ashb commented on airflow/www/views.py
> +        else:
Since the GET path returns, you can drop the `else:` (and not have to touch the rest of this method (making the diff easier to review.

2020-02-05 16:57 UTC, ashb commented on airflow/www/templates/airflow/trigger.html
> +    <h2>Trigger DAG</h2>
Which dag? We should show that on the page.

2020-02-05 16:57 UTC, ashb commented on airflow/www/templates/airflow/trigger.html
> +      <button class="btn" onclick="window.history.back(); return false">bail.</button>
If we are passing `origin` to the template we should use that rather than `history.back` --(that or drop the origin param alltogther.)

2020-02-05 16:58 UTC, ashb requested changes
You haven't tested that a GET request shows the form -- could you please?

2020-02-06 10:30 UTC, ashb requested changes
Could you also post a screenshot of what this new page looks like please?

2020-02-06 10:30 UTC, ashb commented on airflow/www/views.py
> +                return redirect(url_for('Airflow.trigger', dag_id=dag_id))
Rather than redirecting it would be better to just display the form again -- that input will be re-shown, and origin param preserved etc.

2020-02-06 15:19 UTC, dacohen commented
@ashb Made those changes. Here are screenshots of the page on first load, and after entering an invalid payload.

 
<img width="1440" alt="Screen Shot 2020-02-06 at 10 13 31 AM" src="https://user-images.githubusercontent.com/4705646/73950552-1b7d1f80-48ca-11ea-9d45-2f992122ac98.png">
<img width="1439" alt="Screen Shot 2020-02-06 at 10 14 06 AM" src="https://user-images.githubusercontent.com/4705646/73950559-1e781000-48ca-11ea-8bd7-cfd53964067f.png">

2020-02-06 15:59 UTC, ashb commented on airflow/www/templates/airflow/trigger.html
> +        <input class="form-control" name="conf" type="text" value="{{ conf }}"/>
Let's make this a textarea instead of an input

2020-02-06 15:59 UTC, ashb commented on airflow/www/views.py
> +                flash("Invalid JSON configuration")
```suggestion
                flash("Invalid JSON configuration", "error")
```

2020-02-06 16:13 UTC, dacohen commented
@ashb Updated again. New error screenshot attached.

<img width="1436" alt="Screen Shot 2020-02-06 at 11 11 25 AM" src="https://user-images.githubusercontent.com/4705646/73955684-bc230d80-48d1-11ea-8636-29d8742d7c24.png">

2020-02-06 16:46 UTC, ashb approved these changes

2020-02-06 16:46 UTC, merged

2020-08-12 12:18 UTC, josh-gree commented
Why was this not an optional screen!?

2020-08-12 12:22 UTC, kaxil commented
> Why was this not an optional screen!?

The number of clicks are the same to trigger any job, previously you add a prompt box on the same window, now you need to Trigger button on a different window -- that is the only difference. Would love to hear your use-case where you would like to have this optional.

2020-10-09 03:32 UTC, matthewpick commented
Is there an easy way to view the Configuration for a DAG run after I click Trigger? 
Sometimes I am uncertain how a specific DAG run was triggered (unless I look at the task logs).

2020-10-09 09:52 UTC, kaxil commented
> Is there an easy way to view the Configuration for a DAG run after I click Trigger?
> Sometimes I am uncertain how a specific DAG run was triggered (unless I look at the task logs).

@matthewpick You can go Browse -> DagRun and check the conf column to view what you passed:

![image](https://user-images.githubusercontent.com/8811558/95569416-76e54b80-0a1d-11eb-9ae8-caa0b02344c1.png)

2020-10-20 15:50 UTC, matthewpick commented
@kaxil I see! I had to enable RBAC to see the `Conf` column. We're good now 👍