[AIRFLOW-5575] Cannot use the mark future success/failure feature in the UI
apache/airflow pull request #7626
Opened 2020-03-04 20:35 UTC by crhyatt

There is a bug the version of pendulum that Airflow is dependent on.  This PR updates pendulum to the latest stable version.
---
Issue link: WILL BE INSERTED BY [boring-cyborg](https://github.com/kaxil/boring-cyborg)

Make sure to mark the boxes below before creating PR: [x]

- [X] Description above provides context of the change
- [X] Commit message/PR title starts with `[AIRFLOW-NNNN]`. AIRFLOW-NNNN = JIRA ID<sup>*</sup>
- [X] Unit tests coverage for changes (not needed for documentation changes)
- [X ] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [X] Relevant documentation is updated including usage instructions.
- [X] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

<sup>*</sup> For document-only changes commit message can start with `[AIRFLOW-XXXX]`.

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

2020-04-07 20:42 UTC, dimberman commented
Hi @crhyatt could you please rebase and ping me? Will gladly review when it's up and running :)

2020-04-09 13:56 UTC, crhyatt commented
Hi @dimberman.  I have rebased the PR.  The new Pendulum packages has some slight differences.  Let me know if I need make some changes.

2020-04-10 18:00 UTC, crhyatt commented
@dimberman Can you explain the Codecov report to me?

2020-04-14 16:02 UTC, dimberman commented
@crhyatt I have no idea why it's doing that... can you rebase again? I'm not too worried about codecov here. @kaxil maybe you've seent this before?

2020-04-14 23:49 UTC, kaxil commented
> @crhyatt I have no idea why it's doing that... can you rebase again? I'm not too worried about codecov here. @kaxil maybe you've seent this before?

CodeCov basically tells you what part of the code is not covered by tests but ignore it as it has been unstable off-late.

2020-04-19 21:08 UTC, ashb requested changes
Haven't yet given this a full review, but some changed needed.

Additionally Airflwo-5575 is not the right Jira to target for upgrading pendulum -- it should be AIRFLOW-3391

2020-04-19 21:08 UTC, ashb commented on airflow/models/dag.py
> +                following = dttm.in_timezone(self.timezone).__add__(delta)
Don't do this -- use of `__add__` or any dunder (double underscore) except `__class__` is a huge code smell.

```suggestion
                following = dttm.in_timezone(self.timezone) + delta
```

2020-04-19 21:08 UTC, ashb commented on airflow/models/dag.py
> +                '_schedule_interval', 'partial', '_old_context_manager_dags',
Why did you add this back?

2020-04-19 21:08 UTC, ashb commented on setup.py
> +    'pendulum==2.0.5',
```suggestion
    'pendulum~=2.0',
```

2020-04-19 21:09 UTC, ashb commented on airflow/utils/timezone.py
> +    return pendulum.parse(string, tz=timezone or TIMEZONE, strict=False)
:interrobang:

2020-04-19 21:10 UTC, ashb commented on requirements/requirements-python3.7.txt
> +sendgrid==6.2.2
@potiuk Is it expected that we see changes like this from non-master/cron changes? It's not the end of the world, but it makes it harder to see what caused a version to get upgraded if random PRs update these deps.

2020-04-19 21:11 UTC, ashb commented on tests/models/test_taskinstance.py
> +        period = pendulum.period(ti.end_date.add(seconds=1), ti.end_date.add(seconds=15))
This change shouldn't be needed, right? Cos dt - dt should equal a period?

2020-04-21 16:12 UTC, crhyatt commented on airflow/utils/timezone.py
> +    return pendulum.parse(string, tz=timezone or TIMEZONE, strict=False)
The new version of pendulum defaults strict=True for the parse function.  Which does not allow the parser to fall back to the dateutil parser.  [https://pendulum.eustace.io/docs/#parsing]

When the test tests/www/test_views.py::TestLogView::test_get_file_task_log_0 passes the pendulum parser a datetime default formatted string, like 2017-09-01 00:00:00+00:00.  Which is not a strict ISO8601 or RFC3339 format.

2020-04-21 16:12 UTC, crhyatt commented on setup.py
> +    'pendulum==2.0.5',
ok

2020-04-21 18:58 UTC, crhyatt commented
@Ashb The PR for AIRFLOW-3391 has been created.

2020-04-27 16:35 UTC, crhyatt reviewed
@ashb would you like me to cancel this PR and move to 3391?

2020-04-27 16:35 UTC, crhyatt commented on airflow/models/dag.py
> +                '_schedule_interval', 'partial', '_old_context_manager_dags',
I think this was a bad rebase/merge on my part

2020-04-27 16:36 UTC, ashb commented
> @ashb would you like me to cancel this PR and move to 3391?

Just rename this PR and update the commit

2020-06-09 20:25 UTC, ashb requested changes

2020-06-09 20:25 UTC, ashb commented on tests/www/test_views.py
> +                .format(state) + "The task must be cleared in order to be run"
You have a lot of whitespace-only/formatting-only changes here.

Please remove them from this PR (having unrelated changes in like this in a PR makes it harder to back-port fixes.)

2020-06-09 22:06 UTC, crhyatt commented
@ashb I messed something up with a merge.  I am going to close this PR and just use https://github.com/apache/airflow/pull/9184 .

2020-06-09 22:06 UTC, closed without merging