Simple API endpoint to return a DAG's paused state
apache/airflow pull request #7737
Opened 2020-03-16 13:36 UTC by phigrofi

So far it is possible to set the paused state of a DAG via the experimental API. It would be nice to be also able to query the current paused state of a DAG. 

---
Issue link: WILL BE INSERTED BY [boring-cyborg](https://github.com/kaxil/boring-cyborg)

Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [ ] Commit message/PR title starts with `[AIRFLOW-NNNN]`. AIRFLOW-NNNN = JIRA ID<sup>*</sup>
- [ ] Unit tests coverage for changes (not needed for documentation changes)
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

<sup>*</sup> For document-only changes commit message can start with `[AIRFLOW-XXXX]`.

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

2020-03-17 19:20 UTC, potiuk requested changes
We are working on a new API, but yeah - maybe adding that one is not a big deal.

However you need to add tests to it if we are to merge it.

2020-03-18 07:30 UTC, phigrofi commented
@potiuk Ok, Thank you! 
I changed the test for the endpoint, that sets the paused status. 
First I wanted to have a separate test, but then I could not figure out how to set the paused state of a DAG for the test. 
Please check if it makes sense for you this way.

2020-03-18 07:36 UTC, potiuk approved these changes

2020-03-18 07:37 UTC, potiuk commented
Looks good but you have to follow the commit rules-> create a JIRA issue and make sure description and commit title are following that (see the description of the PR)

2020-03-18 08:08 UTC, phigrofi commented
Ok, done!

2020-03-18 08:45 UTC, potiuk commented
And there are some static check failures now :) .. I recommend installing pre-commits :)

2020-03-18 11:15 UTC, phigrofi commented
Ok, thanks for the guidance! 
Now it seems fine, except the coverage report, but the coverage drop by 54% does not seem valid.

2020-03-18 11:31 UTC, potiuk commented
> Ok, thanks for the guidance!
> Now it seems fine, except the coverage report, but the coverage drop by 54% does not seem valid.

It's OK. Coverage is just guidance. We optimized away some tests to have faster runs and we are only looking (if at all)  at it in the master where all tests are always run

2020-03-18 11:31 UTC, potiuk approved these changes

2020-03-18 11:32 UTC, merged

2020-03-18 11:32 UTC, potiuk commented
Thanks @phigrofi !

2020-03-18 13:43 UTC, ashb commented
cc @mik-laj -- since this appears to be a common/requested operation is it worth having "direct" endpoints to get/set the pause state in your new proposed API?

2020-03-18 13:44 UTC, ashb commented
> > Ok, thanks for the guidance!
> > Now it seems fine, except the coverage report, but the coverage drop by 54% does not seem valid.
> 
> It's OK. Coverage is just guidance. We optimized away some tests to have faster runs and we are only looking (if at all) at it in the master where all tests are always run

@potiuk Should we disable coverage.io if we aren't doing a full run, or do you still think it has some use?

2020-03-18 13:50 UTC, mik-laj commented
@ashb If this is a frequent API request, I will add it to the documentation. In this way, users will be able to use, but we will not have additional code to maintain.

2020-03-18 13:55 UTC, potiuk commented
> @potiuk Should we disable coverage.io if we aren't doing a full run, or do you still think it has some use?

Well. for now a lot of people use it to see if things are complete. I often wait until the coverage message comes to see at the PR. But I think we will be able to either get rid of it or start using it when we switch to Github Actions. I really hope it can be done soon....