Move out sendgrid email from airflow.contrib
apache/airflow pull request #9355
Opened 2020-06-17 21:57 UTC by mik-laj

---
Make sure to mark the boxes below before creating PR: [x]

- [X] Description above provides context of the change
- [X] Unit tests coverage for changes (not needed for documentation changes)
- [X] Target Github ISSUE in description if exists
- [X] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [X] Relevant documentation is updated including usage instructions.
- [X] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

2020-06-18 17:10 UTC, potiuk commented on airflow/utils/helpers.py
> +    """This function is deprecated. Please use `airflow.models.baseoperator.chain`."""
Unrelated ?

2020-06-18 17:10 UTC, potiuk commented on docs/conf.py
> -    # Required by airflow/contrib/plugins
Also unrelated?

2020-06-18 17:12 UTC, potiuk commented on docs/integration.rst
> +* :doc:`Email backends </howto/email-config>`
:+1:

2020-06-18 17:12 UTC, potiuk approved these changes
LGTM - just few unrelated small changes that might be better to split-off

2020-06-19 07:55 UTC, feluelle requested changes

2020-06-19 07:55 UTC, feluelle commented on UPDATING.md
> +email_backend = airflow.providers.sendgrid.utils.emai.send_email
```suggestion
email_backend = airflow.providers.sendgrid.utils.emailer.send_email
```

2020-06-19 07:56 UTC, feluelle commented on UPDATING.md
> +The old configuration is still works but can be abandoned.
```suggestion
The old configuration still works but can be abandoned.
```

2020-06-19 07:59 UTC, feluelle commented on UPDATING.md
> +If your configuration file looks like this.
```suggestion
If your configuration file looks like this:
```

2020-06-19 08:22 UTC, feluelle approved these changes

2020-06-28 10:59 UTC, merged