Add placement_strategy option
apache/airflow pull request #9444
Opened 2020-06-20 14:52 UTC by kanga333

Enable ECSOperator to specify a placement strategy.

The pinback strategy makes it easier to leave free EC2 instances. This makes it easier for you to successfully execute ECS Tasks that require a large amount of space.

More info:
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ecs.html#ECS.Client.run_task
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-placement-strategies.html

---
Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Target Github ISSUE in description if exists
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

2020-07-08 14:08 UTC, potiuk requested changes
Looks good, but can you please add unit tests for that? There are existing tests you can take as an example.

2020-07-17 12:49 UTC, kanga333 commented
Thanks for your review.  I think I've added unit tests. 

In the test, I set a new option to ECS operator and run it. And I'm making sure the options are set up correctly in the mock. 
https://github.com/apache/airflow/pull/9444/files#diff-d5b4e15516001a0aa1fc8f7e6f2ebef6R139

Other options have been tested in a similar way. Should I add a test case?

2020-08-31 11:31 UTC, kanga333 commented
@potiuk  Can you respond to my comment in https://github.com/apache/airflow/pull/9444#issuecomment-660088688? Thank you.

2020-08-31 11:35 UTC, potiuk approved these changes

2020-08-31 11:36 UTC, potiuk commented
LGTM. Sorry - missed that one :)

2020-08-31 11:37 UTC, potiuk commented
Just one small request @kanga333  -> we've applied black formatting so it is likely you will have to do it too (it's done automatically wth pre-commits). It would be great if you rebase it to latest master to make sure that we will not break master when we merge/

2020-08-31 23:44 UTC, kanga333 commented
@potiuk Thanks for your review. I've rebased to the latest master and confirmed that the CI will pass.

2020-08-31 23:50 UTC, merged

2020-08-31 23:50 UTC, potiuk commented
Cool! What's next :)?